namespace PortableDevices

module PDHeaderIndices = 
    open PortableDevices.PDHeader
    
    let GuidNameIndex = 
        dict [ GUID_DEVINTERFACE_WPD, "GUID_DEVINTERFACE_WPD"
               GUID_DEVINTERFACE_WPD_PRIVATE, "GUID_DEVINTERFACE_WPD_PRIVATE"
               GUID_DEVINTERFACE_WPD_SERVICE, "GUID_DEVINTERFACE_WPD_SERVICE"
               WPD_API_OPTIONS_V1, "WPD_API_OPTIONS_V1"
               WPD_APPOINTMENT_OBJECT_PROPERTIES_V1, "WPD_APPOINTMENT_OBJECT_PROPERTIES_V1"
               WPD_CATEGORY_CAPABILITIES, "WPD_CATEGORY_CAPABILITIES"
               WPD_CATEGORY_COMMON, "WPD_CATEGORY_COMMON"
               WPD_CATEGORY_DEVICE_HINTS, "WPD_CATEGORY_DEVICE_HINTS"
               WPD_CATEGORY_MEDIA_CAPTURE, "WPD_CATEGORY_MEDIA_CAPTURE"
               WPD_CATEGORY_NETWORK_CONFIGURATION, "WPD_CATEGORY_NETWORK_CONFIGURATION"
               WPD_CATEGORY_NULL, "WPD_CATEGORY_NULL"
               WPD_CATEGORY_OBJECT_ENUMERATION, "WPD_CATEGORY_OBJECT_ENUMERATION"
               WPD_CATEGORY_OBJECT_MANAGEMENT, "WPD_CATEGORY_OBJECT_MANAGEMENT"
               WPD_CATEGORY_OBJECT_PROPERTIES, "WPD_CATEGORY_OBJECT_PROPERTIES"
               WPD_CATEGORY_OBJECT_PROPERTIES_BULK, "WPD_CATEGORY_OBJECT_PROPERTIES_BULK"
               WPD_CATEGORY_OBJECT_RESOURCES, "WPD_CATEGORY_OBJECT_RESOURCES"
               WPD_CATEGORY_SERVICE_CAPABILITIES, "WPD_CATEGORY_SERVICE_CAPABILITIES"
               WPD_CATEGORY_SERVICE_COMMON, "WPD_CATEGORY_SERVICE_COMMON"
               WPD_CATEGORY_SERVICE_METHODS, "WPD_CATEGORY_SERVICE_METHODS"
               WPD_CATEGORY_SMS, "WPD_CATEGORY_SMS"
               WPD_CATEGORY_STILL_IMAGE_CAPTURE, "WPD_CATEGORY_STILL_IMAGE_CAPTURE"
               WPD_CATEGORY_STORAGE, "WPD_CATEGORY_STORAGE"
               WPD_CLASS_EXTENSION_OPTIONS_V1, "WPD_CLASS_EXTENSION_OPTIONS_V1"
               WPD_CLASS_EXTENSION_OPTIONS_V2, "WPD_CLASS_EXTENSION_OPTIONS_V2"
               WPD_CLASS_EXTENSION_OPTIONS_V3, "WPD_CLASS_EXTENSION_OPTIONS_V3"
               WPD_CLASS_EXTENSION_V1, "WPD_CLASS_EXTENSION_V1"
               WPD_CLASS_EXTENSION_V2, "WPD_CLASS_EXTENSION_V2"
               WPD_CLIENT_INFORMATION_PROPERTIES_V1, "WPD_CLIENT_INFORMATION_PROPERTIES_V1"
               WPD_COMMON_INFORMATION_OBJECT_PROPERTIES_V1, "WPD_COMMON_INFORMATION_OBJECT_PROPERTIES_V1"
               WPD_CONTACT_OBJECT_PROPERTIES_V1, "WPD_CONTACT_OBJECT_PROPERTIES_V1"
               WPD_CONTENT_TYPE_ALL, "WPD_CONTENT_TYPE_ALL"
               WPD_CONTENT_TYPE_APPOINTMENT, "WPD_CONTENT_TYPE_APPOINTMENT"
               WPD_CONTENT_TYPE_AUDIO, "WPD_CONTENT_TYPE_AUDIO"
               WPD_CONTENT_TYPE_AUDIO_ALBUM, "WPD_CONTENT_TYPE_AUDIO_ALBUM"
               WPD_CONTENT_TYPE_CALENDAR, "WPD_CONTENT_TYPE_CALENDAR"
               WPD_CONTENT_TYPE_CERTIFICATE, "WPD_CONTENT_TYPE_CERTIFICATE"
               WPD_CONTENT_TYPE_CONTACT, "WPD_CONTENT_TYPE_CONTACT"
               WPD_CONTENT_TYPE_CONTACT_GROUP, "WPD_CONTENT_TYPE_CONTACT_GROUP"
               WPD_CONTENT_TYPE_DOCUMENT, "WPD_CONTENT_TYPE_DOCUMENT"
               WPD_CONTENT_TYPE_EMAIL, "WPD_CONTENT_TYPE_EMAIL"
               WPD_CONTENT_TYPE_FOLDER, "WPD_CONTENT_TYPE_FOLDER"
               WPD_CONTENT_TYPE_FUNCTIONAL_OBJECT, "WPD_CONTENT_TYPE_FUNCTIONAL_OBJECT"
               WPD_CONTENT_TYPE_GENERIC_FILE, "WPD_CONTENT_TYPE_GENERIC_FILE"
               WPD_CONTENT_TYPE_GENERIC_MESSAGE, "WPD_CONTENT_TYPE_GENERIC_MESSAGE"
               WPD_CONTENT_TYPE_IMAGE, "WPD_CONTENT_TYPE_IMAGE"
               WPD_CONTENT_TYPE_IMAGE_ALBUM, "WPD_CONTENT_TYPE_IMAGE_ALBUM"
               WPD_CONTENT_TYPE_MEDIA_CAST, "WPD_CONTENT_TYPE_MEDIA_CAST"
               WPD_CONTENT_TYPE_MEMO, "WPD_CONTENT_TYPE_MEMO"
               WPD_CONTENT_TYPE_MIXED_CONTENT_ALBUM, "WPD_CONTENT_TYPE_MIXED_CONTENT_ALBUM"
               WPD_CONTENT_TYPE_NETWORK_ASSOCIATION, "WPD_CONTENT_TYPE_NETWORK_ASSOCIATION"
               WPD_CONTENT_TYPE_PLAYLIST, "WPD_CONTENT_TYPE_PLAYLIST"
               WPD_CONTENT_TYPE_PROGRAM, "WPD_CONTENT_TYPE_PROGRAM"
               WPD_CONTENT_TYPE_SECTION, "WPD_CONTENT_TYPE_SECTION"
               WPD_CONTENT_TYPE_TASK, "WPD_CONTENT_TYPE_TASK"
               WPD_CONTENT_TYPE_TELEVISION, "WPD_CONTENT_TYPE_TELEVISION"
               WPD_CONTENT_TYPE_UNSPECIFIED, "WPD_CONTENT_TYPE_UNSPECIFIED"
               WPD_CONTENT_TYPE_VIDEO, "WPD_CONTENT_TYPE_VIDEO"
               WPD_CONTENT_TYPE_VIDEO_ALBUM, "WPD_CONTENT_TYPE_VIDEO_ALBUM"
               WPD_CONTENT_TYPE_WIRELESS_PROFILE, "WPD_CONTENT_TYPE_WIRELESS_PROFILE"
               WPD_DEVICE_PROPERTIES_V1, "WPD_DEVICE_PROPERTIES_V1"
               WPD_DEVICE_PROPERTIES_V2, "WPD_DEVICE_PROPERTIES_V2"
               WPD_DOCUMENT_OBJECT_PROPERTIES_V1, "WPD_DOCUMENT_OBJECT_PROPERTIES_V1"
               WPD_EMAIL_OBJECT_PROPERTIES_V1, "WPD_EMAIL_OBJECT_PROPERTIES_V1"
               WPD_EVENT_ATTRIBUTES_V1, "WPD_EVENT_ATTRIBUTES_V1"
               WPD_EVENT_DEVICE_CAPABILITIES_UPDATED, "WPD_EVENT_DEVICE_CAPABILITIES_UPDATED"
               WPD_EVENT_DEVICE_REMOVED, "WPD_EVENT_DEVICE_REMOVED"
               WPD_EVENT_DEVICE_RESET, "WPD_EVENT_DEVICE_RESET"
               WPD_EVENT_NOTIFICATION, "WPD_EVENT_NOTIFICATION"
               WPD_EVENT_OBJECT_ADDED, "WPD_EVENT_OBJECT_ADDED"
               WPD_EVENT_OBJECT_REMOVED, "WPD_EVENT_OBJECT_REMOVED"
               WPD_EVENT_OBJECT_TRANSFER_REQUESTED, "WPD_EVENT_OBJECT_TRANSFER_REQUESTED"
               WPD_EVENT_OBJECT_UPDATED, "WPD_EVENT_OBJECT_UPDATED"
               WPD_EVENT_OPTIONS_V1, "WPD_EVENT_OPTIONS_V1"
               WPD_EVENT_PROPERTIES_V1, "WPD_EVENT_PROPERTIES_V1"
               WPD_EVENT_PROPERTIES_V2, "WPD_EVENT_PROPERTIES_V2"
               WPD_EVENT_SERVICE_METHOD_COMPLETE, "WPD_EVENT_SERVICE_METHOD_COMPLETE"
               WPD_EVENT_STORAGE_FORMAT, "WPD_EVENT_STORAGE_FORMAT"
               WPD_FOLDER_OBJECT_PROPERTIES_V1, "WPD_FOLDER_OBJECT_PROPERTIES_V1"
               WPD_FORMAT_ATTRIBUTES_V1, "WPD_FORMAT_ATTRIBUTES_V1"
               WPD_FUNCTIONAL_CATEGORY_ALL, "WPD_FUNCTIONAL_CATEGORY_ALL"
               WPD_FUNCTIONAL_CATEGORY_AUDIO_CAPTURE, "WPD_FUNCTIONAL_CATEGORY_AUDIO_CAPTURE"
               WPD_FUNCTIONAL_CATEGORY_DEVICE, "WPD_FUNCTIONAL_CATEGORY_DEVICE"
               WPD_FUNCTIONAL_CATEGORY_NETWORK_CONFIGURATION, "WPD_FUNCTIONAL_CATEGORY_NETWORK_CONFIGURATION"
               WPD_FUNCTIONAL_CATEGORY_RENDERING_INFORMATION, "WPD_FUNCTIONAL_CATEGORY_RENDERING_INFORMATION"
               WPD_FUNCTIONAL_CATEGORY_SMS, "WPD_FUNCTIONAL_CATEGORY_SMS"
               WPD_FUNCTIONAL_CATEGORY_STILL_IMAGE_CAPTURE, "WPD_FUNCTIONAL_CATEGORY_STILL_IMAGE_CAPTURE"
               WPD_FUNCTIONAL_CATEGORY_STORAGE, "WPD_FUNCTIONAL_CATEGORY_STORAGE"
               WPD_FUNCTIONAL_CATEGORY_VIDEO_CAPTURE, "WPD_FUNCTIONAL_CATEGORY_VIDEO_CAPTURE"
               WPD_FUNCTIONAL_OBJECT_PROPERTIES_V1, "WPD_FUNCTIONAL_OBJECT_PROPERTIES_V1"
               WPD_IMAGE_OBJECT_PROPERTIES_V1, "WPD_IMAGE_OBJECT_PROPERTIES_V1"
               WPD_MEDIA_PROPERTIES_V1, "WPD_MEDIA_PROPERTIES_V1"
               WPD_MEMO_OBJECT_PROPERTIES_V1, "WPD_MEMO_OBJECT_PROPERTIES_V1"
               WPD_METHOD_ATTRIBUTES_V1, "WPD_METHOD_ATTRIBUTES_V1"
               WPD_MUSIC_OBJECT_PROPERTIES_V1, "WPD_MUSIC_OBJECT_PROPERTIES_V1"
               WPD_NETWORK_ASSOCIATION_PROPERTIES_V1, "WPD_NETWORK_ASSOCIATION_PROPERTIES_V1"
               WPD_OBJECT_FORMAT_3G2, "WPD_OBJECT_FORMAT_3G2"
               WPD_OBJECT_FORMAT_3G2A, "WPD_OBJECT_FORMAT_3G2A"
               WPD_OBJECT_FORMAT_3GP, "WPD_OBJECT_FORMAT_3GP"
               WPD_OBJECT_FORMAT_3GPA, "WPD_OBJECT_FORMAT_3GPA"
               WPD_OBJECT_FORMAT_AAC, "WPD_OBJECT_FORMAT_AAC"
               WPD_OBJECT_FORMAT_ABSTRACT_CONTACT, "WPD_OBJECT_FORMAT_ABSTRACT_CONTACT"
               WPD_OBJECT_FORMAT_ABSTRACT_CONTACT_GROUP, "WPD_OBJECT_FORMAT_ABSTRACT_CONTACT_GROUP"
               WPD_OBJECT_FORMAT_ABSTRACT_MEDIA_CAST, "WPD_OBJECT_FORMAT_ABSTRACT_MEDIA_CAST"
               WPD_OBJECT_FORMAT_AIFF, "WPD_OBJECT_FORMAT_AIFF"
               WPD_OBJECT_FORMAT_ALL, "WPD_OBJECT_FORMAT_ALL"
               WPD_OBJECT_FORMAT_AMR, "WPD_OBJECT_FORMAT_AMR"
               WPD_OBJECT_FORMAT_ASF, "WPD_OBJECT_FORMAT_ASF"
               WPD_OBJECT_FORMAT_ASXPLAYLIST, "WPD_OBJECT_FORMAT_ASXPLAYLIST"
               WPD_OBJECT_FORMAT_ATSCTS, "WPD_OBJECT_FORMAT_ATSCTS"
               WPD_OBJECT_FORMAT_AUDIBLE, "WPD_OBJECT_FORMAT_AUDIBLE"
               WPD_OBJECT_FORMAT_AVCHD, "WPD_OBJECT_FORMAT_AVCHD"
               WPD_OBJECT_FORMAT_AVI, "WPD_OBJECT_FORMAT_AVI"
               WPD_OBJECT_FORMAT_BMP, "WPD_OBJECT_FORMAT_BMP"
               WPD_OBJECT_FORMAT_CIFF, "WPD_OBJECT_FORMAT_CIFF"
               WPD_OBJECT_FORMAT_DPOF, "WPD_OBJECT_FORMAT_DPOF"
               WPD_OBJECT_FORMAT_DVBTS, "WPD_OBJECT_FORMAT_DVBTS"
               WPD_OBJECT_FORMAT_EXECUTABLE, "WPD_OBJECT_FORMAT_EXECUTABLE"
               WPD_OBJECT_FORMAT_EXIF, "WPD_OBJECT_FORMAT_EXIF"
               WPD_OBJECT_FORMAT_FLAC, "WPD_OBJECT_FORMAT_FLAC"
               WPD_OBJECT_FORMAT_FLASHPIX, "WPD_OBJECT_FORMAT_FLASHPIX"
               WPD_OBJECT_FORMAT_GIF, "WPD_OBJECT_FORMAT_GIF"
               WPD_OBJECT_FORMAT_HTML, "WPD_OBJECT_FORMAT_HTML"
               WPD_OBJECT_FORMAT_ICALENDAR, "WPD_OBJECT_FORMAT_ICALENDAR"
               WPD_OBJECT_FORMAT_ICON, "WPD_OBJECT_FORMAT_ICON"
               WPD_OBJECT_FORMAT_JFIF, "WPD_OBJECT_FORMAT_JFIF"
               WPD_OBJECT_FORMAT_JP2, "WPD_OBJECT_FORMAT_JP2"
               WPD_OBJECT_FORMAT_JPEGXR, "WPD_OBJECT_FORMAT_JPEGXR"
               WPD_OBJECT_FORMAT_JPX, "WPD_OBJECT_FORMAT_JPX"
               WPD_OBJECT_FORMAT_M3UPLAYLIST, "WPD_OBJECT_FORMAT_M3UPLAYLIST"
               WPD_OBJECT_FORMAT_M4A, "WPD_OBJECT_FORMAT_M4A"
               WPD_OBJECT_FORMAT_MHT_COMPILED_HTML, "WPD_OBJECT_FORMAT_MHT_COMPILED_HTML"
               WPD_OBJECT_FORMAT_MICROSOFT_EXCEL, "WPD_OBJECT_FORMAT_MICROSOFT_EXCEL"
               WPD_OBJECT_FORMAT_MICROSOFT_POWERPOINT, "WPD_OBJECT_FORMAT_MICROSOFT_POWERPOINT"
               WPD_OBJECT_FORMAT_MICROSOFT_WFC, "WPD_OBJECT_FORMAT_MICROSOFT_WFC"
               WPD_OBJECT_FORMAT_MICROSOFT_WORD, "WPD_OBJECT_FORMAT_MICROSOFT_WORD"
               WPD_OBJECT_FORMAT_MKV, "WPD_OBJECT_FORMAT_MKV"
               WPD_OBJECT_FORMAT_MP2, "WPD_OBJECT_FORMAT_MP2"
               WPD_OBJECT_FORMAT_MP3, "WPD_OBJECT_FORMAT_MP3"
               WPD_OBJECT_FORMAT_MP4, "WPD_OBJECT_FORMAT_MP4"
               WPD_OBJECT_FORMAT_MPEG, "WPD_OBJECT_FORMAT_MPEG"
               WPD_OBJECT_FORMAT_MPLPLAYLIST, "WPD_OBJECT_FORMAT_MPLPLAYLIST"
               WPD_OBJECT_FORMAT_NETWORK_ASSOCIATION, "WPD_OBJECT_FORMAT_NETWORK_ASSOCIATION"
               WPD_OBJECT_FORMAT_OGG, "WPD_OBJECT_FORMAT_OGG"
               WPD_OBJECT_FORMAT_PCD, "WPD_OBJECT_FORMAT_PCD"
               WPD_OBJECT_FORMAT_PICT, "WPD_OBJECT_FORMAT_PICT"
               WPD_OBJECT_FORMAT_PLSPLAYLIST, "WPD_OBJECT_FORMAT_PLSPLAYLIST"
               WPD_OBJECT_FORMAT_PNG, "WPD_OBJECT_FORMAT_PNG"
               WPD_OBJECT_FORMAT_PROPERTIES_ONLY, "WPD_OBJECT_FORMAT_PROPERTIES_ONLY"
               WPD_OBJECT_FORMAT_QCELP, "WPD_OBJECT_FORMAT_QCELP"
               WPD_OBJECT_FORMAT_SCRIPT, "WPD_OBJECT_FORMAT_SCRIPT"
               WPD_OBJECT_FORMAT_TEXT, "WPD_OBJECT_FORMAT_TEXT"
               WPD_OBJECT_FORMAT_TIFF, "WPD_OBJECT_FORMAT_TIFF"
               WPD_OBJECT_FORMAT_TIFFEP, "WPD_OBJECT_FORMAT_TIFFEP"
               WPD_OBJECT_FORMAT_TIFFIT, "WPD_OBJECT_FORMAT_TIFFIT"
               WPD_OBJECT_FORMAT_UNSPECIFIED, "WPD_OBJECT_FORMAT_UNSPECIFIED"
               WPD_OBJECT_FORMAT_VCALENDAR1, "WPD_OBJECT_FORMAT_VCALENDAR1"
               WPD_OBJECT_FORMAT_VCARD2, "WPD_OBJECT_FORMAT_VCARD2"
               WPD_OBJECT_FORMAT_VCARD3, "WPD_OBJECT_FORMAT_VCARD3"
               WPD_OBJECT_FORMAT_WAVE, "WPD_OBJECT_FORMAT_WAVE"
               WPD_OBJECT_FORMAT_WBMP, "WPD_OBJECT_FORMAT_WBMP"
               WPD_OBJECT_FORMAT_WINDOWSIMAGEFORMAT, "WPD_OBJECT_FORMAT_WINDOWSIMAGEFORMAT"
               WPD_OBJECT_FORMAT_WMA, "WPD_OBJECT_FORMAT_WMA"
               WPD_OBJECT_FORMAT_WMV, "WPD_OBJECT_FORMAT_WMV"
               WPD_OBJECT_FORMAT_WPLPLAYLIST, "WPD_OBJECT_FORMAT_WPLPLAYLIST"
               WPD_OBJECT_FORMAT_X509V3CERTIFICATE, "WPD_OBJECT_FORMAT_X509V3CERTIFICATE"
               WPD_OBJECT_FORMAT_XML, "WPD_OBJECT_FORMAT_XML"
               WPD_OBJECT_PROPERTIES_V1, "WPD_OBJECT_PROPERTIES_V1"
               WPD_OBJECT_PROPERTIES_V2, "WPD_OBJECT_PROPERTIES_V2"
               WPD_PARAMETER_ATTRIBUTES_V1, "WPD_PARAMETER_ATTRIBUTES_V1"
               WPD_PROPERTY_ATTRIBUTES_V1, "WPD_PROPERTY_ATTRIBUTES_V1"
               WPD_PROPERTY_ATTRIBUTES_V2, "WPD_PROPERTY_ATTRIBUTES_V2"
               WPD_RENDERING_INFORMATION_OBJECT_PROPERTIES_V1, "WPD_RENDERING_INFORMATION_OBJECT_PROPERTIES_V1"
               WPD_RESOURCE_ALBUM_ART_Guid, "WPD_RESOURCE_ALBUM_ART_Guid"
               WPD_RESOURCE_ATTRIBUTES_V1, "WPD_RESOURCE_ATTRIBUTES_V1"
               WPD_RESOURCE_AUDIO_CLIP_Guid, "WPD_RESOURCE_AUDIO_CLIP_Guid"
               WPD_RESOURCE_BRANDING_ART_Guid, "WPD_RESOURCE_BRANDING_ART_Guid"
               WPD_RESOURCE_CONTACT_PHOTO_Guid, "WPD_RESOURCE_CONTACT_PHOTO_Guid"
               WPD_RESOURCE_DEFAULT_Guid, "WPD_RESOURCE_DEFAULT_Guid"
               WPD_RESOURCE_GENERIC_Guid, "WPD_RESOURCE_GENERIC_Guid"
               WPD_RESOURCE_ICON_Guid, "WPD_RESOURCE_ICON_Guid"
               WPD_RESOURCE_THUMBNAIL_Guid, "WPD_RESOURCE_THUMBNAIL_Guid"
               WPD_RESOURCE_VIDEO_CLIP_Guid, "WPD_RESOURCE_VIDEO_CLIP_Guid"
               WPD_SECTION_OBJECT_PROPERTIES_V1, "WPD_SECTION_OBJECT_PROPERTIES_V1"
               WPD_SERVICE_PROPERTIES_V1, "WPD_SERVICE_PROPERTIES_V1"
               WPD_SMS_OBJECT_PROPERTIES_V1, "WPD_SMS_OBJECT_PROPERTIES_V1"
               WPD_STILL_IMAGE_CAPTURE_OBJECT_PROPERTIES_V1, "WPD_STILL_IMAGE_CAPTURE_OBJECT_PROPERTIES_V1"
               WPD_STORAGE_OBJECT_PROPERTIES_V1, "WPD_STORAGE_OBJECT_PROPERTIES_V1"
               WPD_TASK_OBJECT_PROPERTIES_V1, "WPD_TASK_OBJECT_PROPERTIES_V1"
               WPD_VIDEO_OBJECT_PROPERTIES_V1, "WPD_VIDEO_OBJECT_PROPERTIES_V1" ]
    
    let PropertyNameIndex = 
        [| WPD_API_OPTION_IOCTL_ACCESS, "WPD_API_OPTION_IOCTL_ACCESS"
           WPD_API_OPTION_USE_CLEAR_DATA_STREAM, "WPD_API_OPTION_USE_CLEAR_DATA_STREAM"
           WPD_APPOINTMENT_ACCEPTED_ATTENDEES, "WPD_APPOINTMENT_ACCEPTED_ATTENDEES"
           WPD_APPOINTMENT_DECLINED_ATTENDEES, "WPD_APPOINTMENT_DECLINED_ATTENDEES"
           WPD_APPOINTMENT_LOCATION, "WPD_APPOINTMENT_LOCATION"
           WPD_APPOINTMENT_OPTIONAL_ATTENDEES, "WPD_APPOINTMENT_OPTIONAL_ATTENDEES"
           WPD_APPOINTMENT_REQUIRED_ATTENDEES, "WPD_APPOINTMENT_REQUIRED_ATTENDEES"
           WPD_APPOINTMENT_RESOURCES, "WPD_APPOINTMENT_RESOURCES"
           WPD_APPOINTMENT_TENTATIVE_ATTENDEES, "WPD_APPOINTMENT_TENTATIVE_ATTENDEES"
           WPD_APPOINTMENT_TYPE, "WPD_APPOINTMENT_TYPE"
           WPD_AUDIO_BIT_DEPTH, "WPD_AUDIO_BIT_DEPTH"
           WPD_AUDIO_BITRATE, "WPD_AUDIO_BITRATE"
           WPD_AUDIO_BLOCK_ALIGNMENT, "WPD_AUDIO_BLOCK_ALIGNMENT"
           WPD_AUDIO_CHANNEL_COUNT, "WPD_AUDIO_CHANNEL_COUNT"
           WPD_AUDIO_FORMAT_CODE, "WPD_AUDIO_FORMAT_CODE"
           
           WPD_CLASS_EXTENSION_OPTIONS_DEVICE_IDENTIFICATION_VALUES, 
           "WPD_CLASS_EXTENSION_OPTIONS_DEVICE_IDENTIFICATION_VALUES"
           
           WPD_CLASS_EXTENSION_OPTIONS_DONT_REGISTER_WPD_DEVICE_INTERFACE, 
           "WPD_CLASS_EXTENSION_OPTIONS_DONT_REGISTER_WPD_DEVICE_INTERFACE"
           WPD_CLASS_EXTENSION_OPTIONS_MULTITRANSPORT_MODE, "WPD_CLASS_EXTENSION_OPTIONS_MULTITRANSPORT_MODE"
           
           WPD_CLASS_EXTENSION_OPTIONS_REGISTER_WPD_PRIVATE_DEVICE_INTERFACE, 
           "WPD_CLASS_EXTENSION_OPTIONS_REGISTER_WPD_PRIVATE_DEVICE_INTERFACE"
           WPD_CLASS_EXTENSION_OPTIONS_SILENCE_AUTOPLAY, "WPD_CLASS_EXTENSION_OPTIONS_SILENCE_AUTOPLAY"
           WPD_CLASS_EXTENSION_OPTIONS_SUPPORTED_CONTENT_TYPES, "WPD_CLASS_EXTENSION_OPTIONS_SUPPORTED_CONTENT_TYPES"
           WPD_CLASS_EXTENSION_OPTIONS_TRANSPORT_BANDWIDTH, "WPD_CLASS_EXTENSION_OPTIONS_TRANSPORT_BANDWIDTH"
           WPD_CLIENT_DESIRED_ACCESS, "WPD_CLIENT_DESIRED_ACCESS"
           WPD_CLIENT_EVENT_COOKIE, "WPD_CLIENT_EVENT_COOKIE"
           WPD_CLIENT_MAJOR_VERSION, "WPD_CLIENT_MAJOR_VERSION"
           WPD_CLIENT_MANUAL_CLOSE_ON_DISCONNECT, "WPD_CLIENT_MANUAL_CLOSE_ON_DISCONNECT"
           WPD_CLIENT_MINIMUM_RESULTS_BUFFER_SIZE, "WPD_CLIENT_MINIMUM_RESULTS_BUFFER_SIZE"
           WPD_CLIENT_MINOR_VERSION, "WPD_CLIENT_MINOR_VERSION"
           WPD_CLIENT_NAME, "WPD_CLIENT_NAME"
           WPD_CLIENT_REVISION, "WPD_CLIENT_REVISION"
           WPD_CLIENT_SECURITY_QUALITY_OF_SERVICE, "WPD_CLIENT_SECURITY_QUALITY_OF_SERVICE"
           WPD_CLIENT_SHARE_MODE, "WPD_CLIENT_SHARE_MODE"
           WPD_CLIENT_WMDRM_APPLICATION_CERTIFICATE, "WPD_CLIENT_WMDRM_APPLICATION_CERTIFICATE"
           WPD_CLIENT_WMDRM_APPLICATION_PRIVATE_KEY, "WPD_CLIENT_WMDRM_APPLICATION_PRIVATE_KEY"
           WPD_COMMAND_CAPABILITIES_GET_COMMAND_OPTIONS, "WPD_COMMAND_CAPABILITIES_GET_COMMAND_OPTIONS"
           WPD_COMMAND_CAPABILITIES_GET_EVENT_OPTIONS, "WPD_COMMAND_CAPABILITIES_GET_EVENT_OPTIONS"
           
           WPD_COMMAND_CAPABILITIES_GET_FIXED_PROPERTY_ATTRIBUTES, 
           "WPD_COMMAND_CAPABILITIES_GET_FIXED_PROPERTY_ATTRIBUTES"
           WPD_COMMAND_CAPABILITIES_GET_FUNCTIONAL_OBJECTS, "WPD_COMMAND_CAPABILITIES_GET_FUNCTIONAL_OBJECTS"
           WPD_COMMAND_CAPABILITIES_GET_SUPPORTED_COMMANDS, "WPD_COMMAND_CAPABILITIES_GET_SUPPORTED_COMMANDS"
           WPD_COMMAND_CAPABILITIES_GET_SUPPORTED_CONTENT_TYPES, "WPD_COMMAND_CAPABILITIES_GET_SUPPORTED_CONTENT_TYPES"
           WPD_COMMAND_CAPABILITIES_GET_SUPPORTED_EVENTS, "WPD_COMMAND_CAPABILITIES_GET_SUPPORTED_EVENTS"
           
           WPD_COMMAND_CAPABILITIES_GET_SUPPORTED_FORMAT_PROPERTIES, 
           "WPD_COMMAND_CAPABILITIES_GET_SUPPORTED_FORMAT_PROPERTIES"
           WPD_COMMAND_CAPABILITIES_GET_SUPPORTED_FORMATS, "WPD_COMMAND_CAPABILITIES_GET_SUPPORTED_FORMATS"
           
           WPD_COMMAND_CAPABILITIES_GET_SUPPORTED_FUNCTIONAL_CATEGORIES, 
           "WPD_COMMAND_CAPABILITIES_GET_SUPPORTED_FUNCTIONAL_CATEGORIES"
           
           WPD_COMMAND_CLASS_EXTENSION_REGISTER_SERVICE_INTERFACES, 
           "WPD_COMMAND_CLASS_EXTENSION_REGISTER_SERVICE_INTERFACES"
           
           WPD_COMMAND_CLASS_EXTENSION_UNREGISTER_SERVICE_INTERFACES, 
           "WPD_COMMAND_CLASS_EXTENSION_UNREGISTER_SERVICE_INTERFACES"
           WPD_COMMAND_CLASS_EXTENSION_WRITE_DEVICE_INFORMATION, "WPD_COMMAND_CLASS_EXTENSION_WRITE_DEVICE_INFORMATION"
           WPD_COMMAND_COMMIT_KEYPAIR, "WPD_COMMAND_COMMIT_KEYPAIR"
           
           WPD_COMMAND_COMMON_GET_OBJECT_IDS_FROM_PERSISTENT_UNIQUE_IDS, 
           "WPD_COMMAND_COMMON_GET_OBJECT_IDS_FROM_PERSISTENT_UNIQUE_IDS"
           WPD_COMMAND_COMMON_RESET_DEVICE, "WPD_COMMAND_COMMON_RESET_DEVICE"
           WPD_COMMAND_COMMON_SAVE_CLIENT_INFORMATION, "WPD_COMMAND_COMMON_SAVE_CLIENT_INFORMATION"
           WPD_COMMAND_DEVICE_HINTS_GET_CONTENT_LOCATION, "WPD_COMMAND_DEVICE_HINTS_GET_CONTENT_LOCATION"
           WPD_COMMAND_GENERATE_KEYPAIR, "WPD_COMMAND_GENERATE_KEYPAIR"
           WPD_COMMAND_MEDIA_CAPTURE_PAUSE, "WPD_COMMAND_MEDIA_CAPTURE_PAUSE"
           WPD_COMMAND_MEDIA_CAPTURE_START, "WPD_COMMAND_MEDIA_CAPTURE_START"
           WPD_COMMAND_MEDIA_CAPTURE_STOP, "WPD_COMMAND_MEDIA_CAPTURE_STOP"
           WPD_COMMAND_OBJECT_ENUMERATION_END_FIND, "WPD_COMMAND_OBJECT_ENUMERATION_END_FIND"
           WPD_COMMAND_OBJECT_ENUMERATION_FIND_NEXT, "WPD_COMMAND_OBJECT_ENUMERATION_FIND_NEXT"
           WPD_COMMAND_OBJECT_ENUMERATION_START_FIND, "WPD_COMMAND_OBJECT_ENUMERATION_START_FIND"
           WPD_COMMAND_OBJECT_MANAGEMENT_COMMIT_OBJECT, "WPD_COMMAND_OBJECT_MANAGEMENT_COMMIT_OBJECT"
           WPD_COMMAND_OBJECT_MANAGEMENT_COPY_OBJECTS, "WPD_COMMAND_OBJECT_MANAGEMENT_COPY_OBJECTS"
           
           WPD_COMMAND_OBJECT_MANAGEMENT_CREATE_OBJECT_WITH_PROPERTIES_AND_DATA, 
           "WPD_COMMAND_OBJECT_MANAGEMENT_CREATE_OBJECT_WITH_PROPERTIES_AND_DATA"
           
           WPD_COMMAND_OBJECT_MANAGEMENT_CREATE_OBJECT_WITH_PROPERTIES_ONLY, 
           "WPD_COMMAND_OBJECT_MANAGEMENT_CREATE_OBJECT_WITH_PROPERTIES_ONLY"
           WPD_COMMAND_OBJECT_MANAGEMENT_DELETE_OBJECTS, "WPD_COMMAND_OBJECT_MANAGEMENT_DELETE_OBJECTS"
           WPD_COMMAND_OBJECT_MANAGEMENT_MOVE_OBJECTS, "WPD_COMMAND_OBJECT_MANAGEMENT_MOVE_OBJECTS"
           WPD_COMMAND_OBJECT_MANAGEMENT_REVERT_OBJECT, "WPD_COMMAND_OBJECT_MANAGEMENT_REVERT_OBJECT"
           
           WPD_COMMAND_OBJECT_MANAGEMENT_UPDATE_OBJECT_WITH_PROPERTIES_AND_DATA, 
           "WPD_COMMAND_OBJECT_MANAGEMENT_UPDATE_OBJECT_WITH_PROPERTIES_AND_DATA"
           WPD_COMMAND_OBJECT_MANAGEMENT_WRITE_OBJECT_DATA, "WPD_COMMAND_OBJECT_MANAGEMENT_WRITE_OBJECT_DATA"
           
           WPD_COMMAND_OBJECT_PROPERTIES_BULK_GET_VALUES_BY_OBJECT_FORMAT_END, 
           "WPD_COMMAND_OBJECT_PROPERTIES_BULK_GET_VALUES_BY_OBJECT_FORMAT_END"
           
           WPD_COMMAND_OBJECT_PROPERTIES_BULK_GET_VALUES_BY_OBJECT_FORMAT_NEXT, 
           "WPD_COMMAND_OBJECT_PROPERTIES_BULK_GET_VALUES_BY_OBJECT_FORMAT_NEXT"
           
           WPD_COMMAND_OBJECT_PROPERTIES_BULK_GET_VALUES_BY_OBJECT_FORMAT_START, 
           "WPD_COMMAND_OBJECT_PROPERTIES_BULK_GET_VALUES_BY_OBJECT_FORMAT_START"
           
           WPD_COMMAND_OBJECT_PROPERTIES_BULK_GET_VALUES_BY_OBJECT_LIST_END, 
           "WPD_COMMAND_OBJECT_PROPERTIES_BULK_GET_VALUES_BY_OBJECT_LIST_END"
           
           WPD_COMMAND_OBJECT_PROPERTIES_BULK_GET_VALUES_BY_OBJECT_LIST_NEXT, 
           "WPD_COMMAND_OBJECT_PROPERTIES_BULK_GET_VALUES_BY_OBJECT_LIST_NEXT"
           
           WPD_COMMAND_OBJECT_PROPERTIES_BULK_GET_VALUES_BY_OBJECT_LIST_START, 
           "WPD_COMMAND_OBJECT_PROPERTIES_BULK_GET_VALUES_BY_OBJECT_LIST_START"
           
           WPD_COMMAND_OBJECT_PROPERTIES_BULK_SET_VALUES_BY_OBJECT_LIST_END, 
           "WPD_COMMAND_OBJECT_PROPERTIES_BULK_SET_VALUES_BY_OBJECT_LIST_END"
           
           WPD_COMMAND_OBJECT_PROPERTIES_BULK_SET_VALUES_BY_OBJECT_LIST_NEXT, 
           "WPD_COMMAND_OBJECT_PROPERTIES_BULK_SET_VALUES_BY_OBJECT_LIST_NEXT"
           
           WPD_COMMAND_OBJECT_PROPERTIES_BULK_SET_VALUES_BY_OBJECT_LIST_START, 
           "WPD_COMMAND_OBJECT_PROPERTIES_BULK_SET_VALUES_BY_OBJECT_LIST_START"
           WPD_COMMAND_OBJECT_PROPERTIES_DELETE, "WPD_COMMAND_OBJECT_PROPERTIES_DELETE"
           WPD_COMMAND_OBJECT_PROPERTIES_GET, "WPD_COMMAND_OBJECT_PROPERTIES_GET"
           WPD_COMMAND_OBJECT_PROPERTIES_GET_ALL, "WPD_COMMAND_OBJECT_PROPERTIES_GET_ALL"
           WPD_COMMAND_OBJECT_PROPERTIES_GET_ATTRIBUTES, "WPD_COMMAND_OBJECT_PROPERTIES_GET_ATTRIBUTES"
           WPD_COMMAND_OBJECT_PROPERTIES_GET_SUPPORTED, "WPD_COMMAND_OBJECT_PROPERTIES_GET_SUPPORTED"
           WPD_COMMAND_OBJECT_PROPERTIES_SET, "WPD_COMMAND_OBJECT_PROPERTIES_SET"
           WPD_COMMAND_OBJECT_RESOURCES_CLOSE, "WPD_COMMAND_OBJECT_RESOURCES_CLOSE"
           WPD_COMMAND_OBJECT_RESOURCES_COMMIT, "WPD_COMMAND_OBJECT_RESOURCES_COMMIT"
           WPD_COMMAND_OBJECT_RESOURCES_CREATE_RESOURCE, "WPD_COMMAND_OBJECT_RESOURCES_CREATE_RESOURCE"
           WPD_COMMAND_OBJECT_RESOURCES_DELETE, "WPD_COMMAND_OBJECT_RESOURCES_DELETE"
           WPD_COMMAND_OBJECT_RESOURCES_GET_ATTRIBUTES, "WPD_COMMAND_OBJECT_RESOURCES_GET_ATTRIBUTES"
           WPD_COMMAND_OBJECT_RESOURCES_GET_SUPPORTED, "WPD_COMMAND_OBJECT_RESOURCES_GET_SUPPORTED"
           WPD_COMMAND_OBJECT_RESOURCES_OPEN, "WPD_COMMAND_OBJECT_RESOURCES_OPEN"
           WPD_COMMAND_OBJECT_RESOURCES_READ, "WPD_COMMAND_OBJECT_RESOURCES_READ"
           WPD_COMMAND_OBJECT_RESOURCES_REVERT, "WPD_COMMAND_OBJECT_RESOURCES_REVERT"
           WPD_COMMAND_OBJECT_RESOURCES_SEEK, "WPD_COMMAND_OBJECT_RESOURCES_SEEK"
           WPD_COMMAND_OBJECT_RESOURCES_SEEK_IN_UNITS, "WPD_COMMAND_OBJECT_RESOURCES_SEEK_IN_UNITS"
           WPD_COMMAND_OBJECT_RESOURCES_WRITE, "WPD_COMMAND_OBJECT_RESOURCES_WRITE"
           WPD_COMMAND_PROCESS_WIRELESS_PROFILE, "WPD_COMMAND_PROCESS_WIRELESS_PROFILE"
           WPD_COMMAND_SERVICE_CAPABILITIES_GET_COMMAND_OPTIONS, "WPD_COMMAND_SERVICE_CAPABILITIES_GET_COMMAND_OPTIONS"
           
           WPD_COMMAND_SERVICE_CAPABILITIES_GET_EVENT_ATTRIBUTES, 
           "WPD_COMMAND_SERVICE_CAPABILITIES_GET_EVENT_ATTRIBUTES"
           
           WPD_COMMAND_SERVICE_CAPABILITIES_GET_EVENT_PARAMETER_ATTRIBUTES, 
           "WPD_COMMAND_SERVICE_CAPABILITIES_GET_EVENT_PARAMETER_ATTRIBUTES"
           
           WPD_COMMAND_SERVICE_CAPABILITIES_GET_FORMAT_ATTRIBUTES, 
           "WPD_COMMAND_SERVICE_CAPABILITIES_GET_FORMAT_ATTRIBUTES"
           
           WPD_COMMAND_SERVICE_CAPABILITIES_GET_FORMAT_PROPERTY_ATTRIBUTES, 
           "WPD_COMMAND_SERVICE_CAPABILITIES_GET_FORMAT_PROPERTY_ATTRIBUTES"
           
           WPD_COMMAND_SERVICE_CAPABILITIES_GET_FORMAT_RENDERING_PROFILES, 
           "WPD_COMMAND_SERVICE_CAPABILITIES_GET_FORMAT_RENDERING_PROFILES"
           
           WPD_COMMAND_SERVICE_CAPABILITIES_GET_INHERITED_SERVICES, 
           "WPD_COMMAND_SERVICE_CAPABILITIES_GET_INHERITED_SERVICES"
           
           WPD_COMMAND_SERVICE_CAPABILITIES_GET_METHOD_ATTRIBUTES, 
           "WPD_COMMAND_SERVICE_CAPABILITIES_GET_METHOD_ATTRIBUTES"
           
           WPD_COMMAND_SERVICE_CAPABILITIES_GET_METHOD_PARAMETER_ATTRIBUTES, 
           "WPD_COMMAND_SERVICE_CAPABILITIES_GET_METHOD_PARAMETER_ATTRIBUTES"
           
           WPD_COMMAND_SERVICE_CAPABILITIES_GET_SUPPORTED_COMMANDS, 
           "WPD_COMMAND_SERVICE_CAPABILITIES_GET_SUPPORTED_COMMANDS"
           
           WPD_COMMAND_SERVICE_CAPABILITIES_GET_SUPPORTED_EVENTS, 
           "WPD_COMMAND_SERVICE_CAPABILITIES_GET_SUPPORTED_EVENTS"
           
           WPD_COMMAND_SERVICE_CAPABILITIES_GET_SUPPORTED_FORMAT_PROPERTIES, 
           "WPD_COMMAND_SERVICE_CAPABILITIES_GET_SUPPORTED_FORMAT_PROPERTIES"
           
           WPD_COMMAND_SERVICE_CAPABILITIES_GET_SUPPORTED_FORMATS, 
           "WPD_COMMAND_SERVICE_CAPABILITIES_GET_SUPPORTED_FORMATS"
           
           WPD_COMMAND_SERVICE_CAPABILITIES_GET_SUPPORTED_METHODS, 
           "WPD_COMMAND_SERVICE_CAPABILITIES_GET_SUPPORTED_METHODS"
           
           WPD_COMMAND_SERVICE_CAPABILITIES_GET_SUPPORTED_METHODS_BY_FORMAT, 
           "WPD_COMMAND_SERVICE_CAPABILITIES_GET_SUPPORTED_METHODS_BY_FORMAT"
           WPD_COMMAND_SERVICE_COMMON_GET_SERVICE_OBJECT_ID, "WPD_COMMAND_SERVICE_COMMON_GET_SERVICE_OBJECT_ID"
           WPD_COMMAND_SERVICE_METHODS_CANCEL_INVOKE, "WPD_COMMAND_SERVICE_METHODS_CANCEL_INVOKE"
           WPD_COMMAND_SERVICE_METHODS_END_INVOKE, "WPD_COMMAND_SERVICE_METHODS_END_INVOKE"
           WPD_COMMAND_SERVICE_METHODS_START_INVOKE, "WPD_COMMAND_SERVICE_METHODS_START_INVOKE"
           WPD_COMMAND_SMS_SEND, "WPD_COMMAND_SMS_SEND"
           WPD_COMMAND_STILL_IMAGE_CAPTURE_INITIATE, "WPD_COMMAND_STILL_IMAGE_CAPTURE_INITIATE"
           WPD_COMMAND_STORAGE_EJECT, "WPD_COMMAND_STORAGE_EJECT"
           WPD_COMMAND_STORAGE_FORMAT, "WPD_COMMAND_STORAGE_FORMAT"
           WPD_COMMON_INFORMATION_BODY_TEXT, "WPD_COMMON_INFORMATION_BODY_TEXT"
           WPD_COMMON_INFORMATION_END_DATETIME, "WPD_COMMON_INFORMATION_END_DATETIME"
           WPD_COMMON_INFORMATION_NOTES, "WPD_COMMON_INFORMATION_NOTES"
           WPD_COMMON_INFORMATION_PRIORITY, "WPD_COMMON_INFORMATION_PRIORITY"
           WPD_COMMON_INFORMATION_START_DATETIME, "WPD_COMMON_INFORMATION_START_DATETIME"
           WPD_COMMON_INFORMATION_SUBJECT, "WPD_COMMON_INFORMATION_SUBJECT"
           WPD_CONTACT_ANNIVERSARY_DATE, "WPD_CONTACT_ANNIVERSARY_DATE"
           WPD_CONTACT_ASSISTANT, "WPD_CONTACT_ASSISTANT"
           WPD_CONTACT_BIRTHDATE, "WPD_CONTACT_BIRTHDATE"
           WPD_CONTACT_BUSINESS_EMAIL, "WPD_CONTACT_BUSINESS_EMAIL"
           WPD_CONTACT_BUSINESS_EMAIL2, "WPD_CONTACT_BUSINESS_EMAIL2"
           WPD_CONTACT_BUSINESS_FAX, "WPD_CONTACT_BUSINESS_FAX"
           WPD_CONTACT_BUSINESS_FULL_POSTAL_ADDRESS, "WPD_CONTACT_BUSINESS_FULL_POSTAL_ADDRESS"
           WPD_CONTACT_BUSINESS_PHONE, "WPD_CONTACT_BUSINESS_PHONE"
           WPD_CONTACT_BUSINESS_PHONE2, "WPD_CONTACT_BUSINESS_PHONE2"
           WPD_CONTACT_BUSINESS_POSTAL_ADDRESS_CITY, "WPD_CONTACT_BUSINESS_POSTAL_ADDRESS_CITY"
           WPD_CONTACT_BUSINESS_POSTAL_ADDRESS_COUNTRY, "WPD_CONTACT_BUSINESS_POSTAL_ADDRESS_COUNTRY"
           WPD_CONTACT_BUSINESS_POSTAL_ADDRESS_LINE1, "WPD_CONTACT_BUSINESS_POSTAL_ADDRESS_LINE1"
           WPD_CONTACT_BUSINESS_POSTAL_ADDRESS_LINE2, "WPD_CONTACT_BUSINESS_POSTAL_ADDRESS_LINE2"
           WPD_CONTACT_BUSINESS_POSTAL_ADDRESS_POSTAL_CODE, "WPD_CONTACT_BUSINESS_POSTAL_ADDRESS_POSTAL_CODE"
           WPD_CONTACT_BUSINESS_POSTAL_ADDRESS_REGION, "WPD_CONTACT_BUSINESS_POSTAL_ADDRESS_REGION"
           WPD_CONTACT_BUSINESS_WEB_ADDRESS, "WPD_CONTACT_BUSINESS_WEB_ADDRESS"
           WPD_CONTACT_CHILDREN, "WPD_CONTACT_CHILDREN"
           WPD_CONTACT_COMPANY_NAME, "WPD_CONTACT_COMPANY_NAME"
           WPD_CONTACT_DISPLAY_NAME, "WPD_CONTACT_DISPLAY_NAME"
           WPD_CONTACT_FIRST_NAME, "WPD_CONTACT_FIRST_NAME"
           WPD_CONTACT_INSTANT_MESSENGER, "WPD_CONTACT_INSTANT_MESSENGER"
           WPD_CONTACT_INSTANT_MESSENGER2, "WPD_CONTACT_INSTANT_MESSENGER2"
           WPD_CONTACT_INSTANT_MESSENGER3, "WPD_CONTACT_INSTANT_MESSENGER3"
           WPD_CONTACT_LAST_NAME, "WPD_CONTACT_LAST_NAME"
           WPD_CONTACT_MIDDLE_NAMES, "WPD_CONTACT_MIDDLE_NAMES"
           WPD_CONTACT_MOBILE_PHONE, "WPD_CONTACT_MOBILE_PHONE"
           WPD_CONTACT_MOBILE_PHONE2, "WPD_CONTACT_MOBILE_PHONE2"
           WPD_CONTACT_OTHER_EMAILS, "WPD_CONTACT_OTHER_EMAILS"
           WPD_CONTACT_OTHER_FULL_POSTAL_ADDRESS, "WPD_CONTACT_OTHER_FULL_POSTAL_ADDRESS"
           WPD_CONTACT_OTHER_PHONES, "WPD_CONTACT_OTHER_PHONES"
           WPD_CONTACT_OTHER_POSTAL_ADDRESS_CITY, "WPD_CONTACT_OTHER_POSTAL_ADDRESS_CITY"
           WPD_CONTACT_OTHER_POSTAL_ADDRESS_LINE1, "WPD_CONTACT_OTHER_POSTAL_ADDRESS_LINE1"
           WPD_CONTACT_OTHER_POSTAL_ADDRESS_LINE2, "WPD_CONTACT_OTHER_POSTAL_ADDRESS_LINE2"
           WPD_CONTACT_OTHER_POSTAL_ADDRESS_POSTAL_CODE, "WPD_CONTACT_OTHER_POSTAL_ADDRESS_POSTAL_CODE"
           WPD_CONTACT_OTHER_POSTAL_ADDRESS_POSTAL_COUNTRY, "WPD_CONTACT_OTHER_POSTAL_ADDRESS_POSTAL_COUNTRY"
           WPD_CONTACT_OTHER_POSTAL_ADDRESS_REGION, "WPD_CONTACT_OTHER_POSTAL_ADDRESS_REGION"
           WPD_CONTACT_PAGER, "WPD_CONTACT_PAGER"
           WPD_CONTACT_PERSONAL_EMAIL, "WPD_CONTACT_PERSONAL_EMAIL"
           WPD_CONTACT_PERSONAL_EMAIL2, "WPD_CONTACT_PERSONAL_EMAIL2"
           WPD_CONTACT_PERSONAL_FAX, "WPD_CONTACT_PERSONAL_FAX"
           WPD_CONTACT_PERSONAL_FULL_POSTAL_ADDRESS, "WPD_CONTACT_PERSONAL_FULL_POSTAL_ADDRESS"
           WPD_CONTACT_PERSONAL_PHONE, "WPD_CONTACT_PERSONAL_PHONE"
           WPD_CONTACT_PERSONAL_PHONE2, "WPD_CONTACT_PERSONAL_PHONE2"
           WPD_CONTACT_PERSONAL_POSTAL_ADDRESS_CITY, "WPD_CONTACT_PERSONAL_POSTAL_ADDRESS_CITY"
           WPD_CONTACT_PERSONAL_POSTAL_ADDRESS_COUNTRY, "WPD_CONTACT_PERSONAL_POSTAL_ADDRESS_COUNTRY"
           WPD_CONTACT_PERSONAL_POSTAL_ADDRESS_LINE1, "WPD_CONTACT_PERSONAL_POSTAL_ADDRESS_LINE1"
           WPD_CONTACT_PERSONAL_POSTAL_ADDRESS_LINE2, "WPD_CONTACT_PERSONAL_POSTAL_ADDRESS_LINE2"
           WPD_CONTACT_PERSONAL_POSTAL_ADDRESS_POSTAL_CODE, "WPD_CONTACT_PERSONAL_POSTAL_ADDRESS_POSTAL_CODE"
           WPD_CONTACT_PERSONAL_POSTAL_ADDRESS_REGION, "WPD_CONTACT_PERSONAL_POSTAL_ADDRESS_REGION"
           WPD_CONTACT_PERSONAL_WEB_ADDRESS, "WPD_CONTACT_PERSONAL_WEB_ADDRESS"
           WPD_CONTACT_PHONETIC_COMPANY_NAME, "WPD_CONTACT_PHONETIC_COMPANY_NAME"
           WPD_CONTACT_PHONETIC_FIRST_NAME, "WPD_CONTACT_PHONETIC_FIRST_NAME"
           WPD_CONTACT_PHONETIC_LAST_NAME, "WPD_CONTACT_PHONETIC_LAST_NAME"
           WPD_CONTACT_PREFIX, "WPD_CONTACT_PREFIX"
           WPD_CONTACT_PRIMARY_EMAIL_ADDRESS, "WPD_CONTACT_PRIMARY_EMAIL_ADDRESS"
           WPD_CONTACT_PRIMARY_FAX, "WPD_CONTACT_PRIMARY_FAX"
           WPD_CONTACT_PRIMARY_PHONE, "WPD_CONTACT_PRIMARY_PHONE"
           WPD_CONTACT_PRIMARY_WEB_ADDRESS, "WPD_CONTACT_PRIMARY_WEB_ADDRESS"
           WPD_CONTACT_RINGTONE, "WPD_CONTACT_RINGTONE"
           WPD_CONTACT_ROLE, "WPD_CONTACT_ROLE"
           WPD_CONTACT_SPOUSE, "WPD_CONTACT_SPOUSE"
           WPD_CONTACT_SUFFIX, "WPD_CONTACT_SUFFIX"
           WPD_DEVICE_DATETIME, "WPD_DEVICE_DATETIME"
           WPD_DEVICE_FIRMWARE_VERSION, "WPD_DEVICE_FIRMWARE_VERSION"
           WPD_DEVICE_FRIENDLY_NAME, "WPD_DEVICE_FRIENDLY_NAME"
           WPD_DEVICE_FUNCTIONAL_UNIQUE_ID, "WPD_DEVICE_FUNCTIONAL_UNIQUE_ID"
           WPD_DEVICE_MANUFACTURER, "WPD_DEVICE_MANUFACTURER"
           WPD_DEVICE_MODEL, "WPD_DEVICE_MODEL"
           WPD_DEVICE_MODEL_UNIQUE_ID, "WPD_DEVICE_MODEL_UNIQUE_ID"
           WPD_DEVICE_NETWORK_IDENTIFIER, "WPD_DEVICE_NETWORK_IDENTIFIER"
           WPD_DEVICE_POWER_LEVEL, "WPD_DEVICE_POWER_LEVEL"
           WPD_DEVICE_POWER_SOURCE, "WPD_DEVICE_POWER_SOURCE"
           WPD_DEVICE_PROTOCOL, "WPD_DEVICE_PROTOCOL"
           WPD_DEVICE_SERIAL_NUMBER, "WPD_DEVICE_SERIAL_NUMBER"
           WPD_DEVICE_SUPPORTED_DRM_SCHEMES, "WPD_DEVICE_SUPPORTED_DRM_SCHEMES"
           WPD_DEVICE_SUPPORTED_FORMATS_ARE_ORDERED, "WPD_DEVICE_SUPPORTED_FORMATS_ARE_ORDERED"
           WPD_DEVICE_SUPPORTS_NON_CONSUMABLE, "WPD_DEVICE_SUPPORTS_NON_CONSUMABLE"
           WPD_DEVICE_SYNC_PARTNER, "WPD_DEVICE_SYNC_PARTNER"
           WPD_DEVICE_TRANSPORT, "WPD_DEVICE_TRANSPORT"
           WPD_DEVICE_TYPE, "WPD_DEVICE_TYPE"
           WPD_DEVICE_USE_DEVICE_STAGE, "WPD_DEVICE_USE_DEVICE_STAGE"
           WPD_EMAIL_BCC_LINE, "WPD_EMAIL_BCC_LINE"
           WPD_EMAIL_CC_LINE, "WPD_EMAIL_CC_LINE"
           WPD_EMAIL_HAS_ATTACHMENTS, "WPD_EMAIL_HAS_ATTACHMENTS"
           WPD_EMAIL_HAS_BEEN_READ, "WPD_EMAIL_HAS_BEEN_READ"
           WPD_EMAIL_RECEIVED_TIME, "WPD_EMAIL_RECEIVED_TIME"
           WPD_EMAIL_SENDER_ADDRESS, "WPD_EMAIL_SENDER_ADDRESS"
           WPD_EMAIL_TO_LINE, "WPD_EMAIL_TO_LINE"
           WPD_EVENT_ATTRIBUTE_NAME, "WPD_EVENT_ATTRIBUTE_NAME"
           WPD_EVENT_ATTRIBUTE_OPTIONS, "WPD_EVENT_ATTRIBUTE_OPTIONS"
           WPD_EVENT_ATTRIBUTE_PARAMETERS, "WPD_EVENT_ATTRIBUTE_PARAMETERS"
           WPD_EVENT_OPTION_IS_AUTOPLAY_EVENT, "WPD_EVENT_OPTION_IS_AUTOPLAY_EVENT"
           WPD_EVENT_OPTION_IS_BROADCAST_EVENT, "WPD_EVENT_OPTION_IS_BROADCAST_EVENT"
           WPD_EVENT_PARAMETER_CHILD_HIERARCHY_CHANGED, "WPD_EVENT_PARAMETER_CHILD_HIERARCHY_CHANGED"
           WPD_EVENT_PARAMETER_EVENT_ID, "WPD_EVENT_PARAMETER_EVENT_ID"
           WPD_EVENT_PARAMETER_OBJECT_CREATION_COOKIE, "WPD_EVENT_PARAMETER_OBJECT_CREATION_COOKIE"
           
           WPD_EVENT_PARAMETER_OBJECT_PARENT_PERSISTENT_UNIQUE_ID, 
           "WPD_EVENT_PARAMETER_OBJECT_PARENT_PERSISTENT_UNIQUE_ID"
           WPD_EVENT_PARAMETER_OPERATION_PROGRESS, "WPD_EVENT_PARAMETER_OPERATION_PROGRESS"
           WPD_EVENT_PARAMETER_OPERATION_STATE, "WPD_EVENT_PARAMETER_OPERATION_STATE"
           WPD_EVENT_PARAMETER_PNP_DEVICE_ID, "WPD_EVENT_PARAMETER_PNP_DEVICE_ID"
           WPD_EVENT_PARAMETER_SERVICE_METHOD_CONTEXT, "WPD_EVENT_PARAMETER_SERVICE_METHOD_CONTEXT"
           WPD_FOLDER_CONTENT_TYPES_ALLOWED, "WPD_FOLDER_CONTENT_TYPES_ALLOWED"
           WPD_FORMAT_ATTRIBUTE_MIMETYPE, "WPD_FORMAT_ATTRIBUTE_MIMETYPE"
           WPD_FORMAT_ATTRIBUTE_NAME, "WPD_FORMAT_ATTRIBUTE_NAME"
           WPD_FUNCTIONAL_OBJECT_CATEGORY, "WPD_FUNCTIONAL_OBJECT_CATEGORY"
           WPD_IMAGE_BITDEPTH, "WPD_IMAGE_BITDEPTH"
           WPD_IMAGE_COLOR_CORRECTED_STATUS, "WPD_IMAGE_COLOR_CORRECTED_STATUS"
           WPD_IMAGE_CROPPED_STATUS, "WPD_IMAGE_CROPPED_STATUS"
           WPD_IMAGE_EXPOSURE_INDEX, "WPD_IMAGE_EXPOSURE_INDEX"
           WPD_IMAGE_EXPOSURE_TIME, "WPD_IMAGE_EXPOSURE_TIME"
           WPD_IMAGE_FNUMBER, "WPD_IMAGE_FNUMBER"
           WPD_IMAGE_HORIZONTAL_RESOLUTION, "WPD_IMAGE_HORIZONTAL_RESOLUTION"
           WPD_IMAGE_VERTICAL_RESOLUTION, "WPD_IMAGE_VERTICAL_RESOLUTION"
           WPD_MEDIA_ALBUM_ARTIST, "WPD_MEDIA_ALBUM_ARTIST"
           WPD_MEDIA_ARTIST, "WPD_MEDIA_ARTIST"
           WPD_MEDIA_AUDIO_ENCODING_PROFILE, "WPD_MEDIA_AUDIO_ENCODING_PROFILE"
           WPD_MEDIA_BITRATE_TYPE, "WPD_MEDIA_BITRATE_TYPE"
           WPD_MEDIA_BUY_NOW, "WPD_MEDIA_BUY_NOW"
           WPD_MEDIA_BYTE_BOOKMARK, "WPD_MEDIA_BYTE_BOOKMARK"
           WPD_MEDIA_COMPOSER, "WPD_MEDIA_COMPOSER"
           WPD_MEDIA_COPYRIGHT, "WPD_MEDIA_COPYRIGHT"
           WPD_MEDIA_DESCRIPTION, "WPD_MEDIA_DESCRIPTION"
           WPD_MEDIA_DESTINATION_URL, "WPD_MEDIA_DESTINATION_URL"
           WPD_MEDIA_DURATION, "WPD_MEDIA_DURATION"
           WPD_MEDIA_EFFECTIVE_RATING, "WPD_MEDIA_EFFECTIVE_RATING"
           WPD_MEDIA_ENCODING_PROFILE, "WPD_MEDIA_ENCODING_PROFILE"
           WPD_MEDIA_GENRE, "WPD_MEDIA_GENRE"
           WPD_MEDIA_GUID, "WPD_MEDIA_GUID"
           WPD_MEDIA_HEIGHT, "WPD_MEDIA_HEIGHT"
           WPD_MEDIA_LAST_ACCESSED_TIME, "WPD_MEDIA_LAST_ACCESSED_TIME"
           WPD_MEDIA_LAST_BUILD_DATE, "WPD_MEDIA_LAST_BUILD_DATE"
           WPD_MEDIA_MANAGING_EDITOR, "WPD_MEDIA_MANAGING_EDITOR"
           WPD_MEDIA_META_GENRE, "WPD_MEDIA_META_GENRE"
           WPD_MEDIA_OBJECT_BOOKMARK, "WPD_MEDIA_OBJECT_BOOKMARK"
           WPD_MEDIA_OWNER, "WPD_MEDIA_OWNER"
           WPD_MEDIA_PARENTAL_RATING, "WPD_MEDIA_PARENTAL_RATING"
           WPD_MEDIA_RELEASE_DATE, "WPD_MEDIA_RELEASE_DATE"
           WPD_MEDIA_SAMPLE_RATE, "WPD_MEDIA_SAMPLE_RATE"
           WPD_MEDIA_SKIP_COUNT, "WPD_MEDIA_SKIP_COUNT"
           WPD_MEDIA_SOURCE_URL, "WPD_MEDIA_SOURCE_URL"
           WPD_MEDIA_STAR_RATING, "WPD_MEDIA_STAR_RATING"
           WPD_MEDIA_SUB_DESCRIPTION, "WPD_MEDIA_SUB_DESCRIPTION"
           WPD_MEDIA_SUB_TITLE, "WPD_MEDIA_SUB_TITLE"
           WPD_MEDIA_SUBSCRIPTION_CONTENT_ID, "WPD_MEDIA_SUBSCRIPTION_CONTENT_ID"
           WPD_MEDIA_TIME_BOOKMARK, "WPD_MEDIA_TIME_BOOKMARK"
           WPD_MEDIA_TIME_TO_LIVE, "WPD_MEDIA_TIME_TO_LIVE"
           WPD_MEDIA_TITLE, "WPD_MEDIA_TITLE"
           WPD_MEDIA_TOTAL_BITRATE, "WPD_MEDIA_TOTAL_BITRATE"
           WPD_MEDIA_USE_COUNT, "WPD_MEDIA_USE_COUNT"
           WPD_MEDIA_USER_EFFECTIVE_RATING, "WPD_MEDIA_USER_EFFECTIVE_RATING"
           WPD_MEDIA_WEBMASTER, "WPD_MEDIA_WEBMASTER"
           WPD_MEDIA_WIDTH, "WPD_MEDIA_WIDTH"
           WPD_METHOD_ATTRIBUTE_ACCESS, "WPD_METHOD_ATTRIBUTE_ACCESS"
           WPD_METHOD_ATTRIBUTE_ASSOCIATED_FORMAT, "WPD_METHOD_ATTRIBUTE_ASSOCIATED_FORMAT"
           WPD_METHOD_ATTRIBUTE_NAME, "WPD_METHOD_ATTRIBUTE_NAME"
           WPD_METHOD_ATTRIBUTE_PARAMETERS, "WPD_METHOD_ATTRIBUTE_PARAMETERS"
           WPD_MUSIC_ALBUM, "WPD_MUSIC_ALBUM"
           WPD_MUSIC_LYRICS, "WPD_MUSIC_LYRICS"
           WPD_MUSIC_MOOD, "WPD_MUSIC_MOOD"
           WPD_MUSIC_TRACK, "WPD_MUSIC_TRACK"
           WPD_NETWORK_ASSOCIATION_HOST_NETWORK_IDENTIFIERS, "WPD_NETWORK_ASSOCIATION_HOST_NETWORK_IDENTIFIERS"
           WPD_NETWORK_ASSOCIATION_X509V3SEQUENCE, "WPD_NETWORK_ASSOCIATION_X509V3SEQUENCE"
           WPD_OBJECT_BACK_REFERENCES, "WPD_OBJECT_BACK_REFERENCES"
           WPD_OBJECT_CAN_DELETE, "WPD_OBJECT_CAN_DELETE"
           WPD_OBJECT_CONTAINER_FUNCTIONAL_OBJECT_ID, "WPD_OBJECT_CONTAINER_FUNCTIONAL_OBJECT_ID"
           WPD_OBJECT_CONTENT_TYPE, "WPD_OBJECT_CONTENT_TYPE"
           WPD_OBJECT_DATE_AUTHORED, "WPD_OBJECT_DATE_AUTHORED"
           WPD_OBJECT_DATE_CREATED, "WPD_OBJECT_DATE_CREATED"
           WPD_OBJECT_DATE_MODIFIED, "WPD_OBJECT_DATE_MODIFIED"
           WPD_OBJECT_FORMAT, "WPD_OBJECT_FORMAT"
           WPD_OBJECT_GENERATE_THUMBNAIL_FROM_RESOURCE, "WPD_OBJECT_GENERATE_THUMBNAIL_FROM_RESOURCE"
           WPD_OBJECT_HINT_LOCATION_DISPLAY_NAME, "WPD_OBJECT_HINT_LOCATION_DISPLAY_NAME"
           WPD_OBJECT_ID, "WPD_OBJECT_ID"
           WPD_OBJECT_IS_DRM_PROTECTED, "WPD_OBJECT_IS_DRM_PROTECTED"
           WPD_OBJECT_ISHIDDEN, "WPD_OBJECT_ISHIDDEN"
           WPD_OBJECT_ISSYSTEM, "WPD_OBJECT_ISSYSTEM"
           WPD_OBJECT_KEYWORDS, "WPD_OBJECT_KEYWORDS"
           WPD_OBJECT_LANGUAGE_LOCALE, "WPD_OBJECT_LANGUAGE_LOCALE"
           WPD_OBJECT_NAME, "WPD_OBJECT_NAME"
           WPD_OBJECT_NON_CONSUMABLE, "WPD_OBJECT_NON_CONSUMABLE"
           WPD_OBJECT_ORIGINAL_FILE_NAME, "WPD_OBJECT_ORIGINAL_FILE_NAME"
           WPD_OBJECT_PARENT_ID, "WPD_OBJECT_PARENT_ID"
           WPD_OBJECT_PERSISTENT_UNIQUE_ID, "WPD_OBJECT_PERSISTENT_UNIQUE_ID"
           WPD_OBJECT_REFERENCES, "WPD_OBJECT_REFERENCES"
           WPD_OBJECT_SIZE, "WPD_OBJECT_SIZE"
           WPD_OBJECT_SUPPORTED_UNITS, "WPD_OBJECT_SUPPORTED_UNITS"
           WPD_OBJECT_SYNC_ID, "WPD_OBJECT_SYNC_ID"
           
           WPD_OPTION_OBJECT_MANAGEMENT_RECURSIVE_DELETE_SUPPORTED, 
           "WPD_OPTION_OBJECT_MANAGEMENT_RECURSIVE_DELETE_SUPPORTED"
           WPD_OPTION_OBJECT_RESOURCES_NO_INPUT_BUFFER_ON_READ, "WPD_OPTION_OBJECT_RESOURCES_NO_INPUT_BUFFER_ON_READ"
           WPD_OPTION_OBJECT_RESOURCES_SEEK_ON_READ_SUPPORTED, "WPD_OPTION_OBJECT_RESOURCES_SEEK_ON_READ_SUPPORTED"
           WPD_OPTION_OBJECT_RESOURCES_SEEK_ON_WRITE_SUPPORTED, "WPD_OPTION_OBJECT_RESOURCES_SEEK_ON_WRITE_SUPPORTED"
           WPD_OPTION_SMS_BINARY_MESSAGE_SUPPORTED, "WPD_OPTION_SMS_BINARY_MESSAGE_SUPPORTED"
           WPD_OPTION_VALID_OBJECT_IDS, "WPD_OPTION_VALID_OBJECT_IDS"
           WPD_PARAMETER_ATTRIBUTE_DEFAULT_VALUE, "WPD_PARAMETER_ATTRIBUTE_DEFAULT_VALUE"
           WPD_PARAMETER_ATTRIBUTE_ENUMERATION_ELEMENTS, "WPD_PARAMETER_ATTRIBUTE_ENUMERATION_ELEMENTS"
           WPD_PARAMETER_ATTRIBUTE_FORM, "WPD_PARAMETER_ATTRIBUTE_FORM"
           WPD_PARAMETER_ATTRIBUTE_MAX_SIZE, "WPD_PARAMETER_ATTRIBUTE_MAX_SIZE"
           WPD_PARAMETER_ATTRIBUTE_NAME, "WPD_PARAMETER_ATTRIBUTE_NAME"
           WPD_PARAMETER_ATTRIBUTE_ORDER, "WPD_PARAMETER_ATTRIBUTE_ORDER"
           WPD_PARAMETER_ATTRIBUTE_RANGE_MAX, "WPD_PARAMETER_ATTRIBUTE_RANGE_MAX"
           WPD_PARAMETER_ATTRIBUTE_RANGE_MIN, "WPD_PARAMETER_ATTRIBUTE_RANGE_MIN"
           WPD_PARAMETER_ATTRIBUTE_RANGE_STEP, "WPD_PARAMETER_ATTRIBUTE_RANGE_STEP"
           WPD_PARAMETER_ATTRIBUTE_REGULAR_EXPRESSION, "WPD_PARAMETER_ATTRIBUTE_REGULAR_EXPRESSION"
           WPD_PARAMETER_ATTRIBUTE_USAGE, "WPD_PARAMETER_ATTRIBUTE_USAGE"
           WPD_PARAMETER_ATTRIBUTE_VARTYPE, "WPD_PARAMETER_ATTRIBUTE_VARTYPE"
           WPD_PROPERTY_ATTRIBUTE_CAN_DELETE, "WPD_PROPERTY_ATTRIBUTE_CAN_DELETE"
           WPD_PROPERTY_ATTRIBUTE_CAN_READ, "WPD_PROPERTY_ATTRIBUTE_CAN_READ"
           WPD_PROPERTY_ATTRIBUTE_CAN_WRITE, "WPD_PROPERTY_ATTRIBUTE_CAN_WRITE"
           WPD_PROPERTY_ATTRIBUTE_DEFAULT_VALUE, "WPD_PROPERTY_ATTRIBUTE_DEFAULT_VALUE"
           WPD_PROPERTY_ATTRIBUTE_ENUMERATION_ELEMENTS, "WPD_PROPERTY_ATTRIBUTE_ENUMERATION_ELEMENTS"
           WPD_PROPERTY_ATTRIBUTE_FAST_PROPERTY, "WPD_PROPERTY_ATTRIBUTE_FAST_PROPERTY"
           WPD_PROPERTY_ATTRIBUTE_FORM, "WPD_PROPERTY_ATTRIBUTE_FORM"
           WPD_PROPERTY_ATTRIBUTE_MAX_SIZE, "WPD_PROPERTY_ATTRIBUTE_MAX_SIZE"
           WPD_PROPERTY_ATTRIBUTE_NAME, "WPD_PROPERTY_ATTRIBUTE_NAME"
           WPD_PROPERTY_ATTRIBUTE_RANGE_MAX, "WPD_PROPERTY_ATTRIBUTE_RANGE_MAX"
           WPD_PROPERTY_ATTRIBUTE_RANGE_MIN, "WPD_PROPERTY_ATTRIBUTE_RANGE_MIN"
           WPD_PROPERTY_ATTRIBUTE_RANGE_STEP, "WPD_PROPERTY_ATTRIBUTE_RANGE_STEP"
           WPD_PROPERTY_ATTRIBUTE_REGULAR_EXPRESSION, "WPD_PROPERTY_ATTRIBUTE_REGULAR_EXPRESSION"
           WPD_PROPERTY_ATTRIBUTE_VARTYPE, "WPD_PROPERTY_ATTRIBUTE_VARTYPE"
           WPD_PROPERTY_CAPABILITIES_COMMAND, "WPD_PROPERTY_CAPABILITIES_COMMAND"
           WPD_PROPERTY_CAPABILITIES_COMMAND_OPTIONS, "WPD_PROPERTY_CAPABILITIES_COMMAND_OPTIONS"
           WPD_PROPERTY_CAPABILITIES_CONTENT_TYPE, "WPD_PROPERTY_CAPABILITIES_CONTENT_TYPE"
           WPD_PROPERTY_CAPABILITIES_CONTENT_TYPES, "WPD_PROPERTY_CAPABILITIES_CONTENT_TYPES"
           WPD_PROPERTY_CAPABILITIES_EVENT, "WPD_PROPERTY_CAPABILITIES_EVENT"
           WPD_PROPERTY_CAPABILITIES_EVENT_OPTIONS, "WPD_PROPERTY_CAPABILITIES_EVENT_OPTIONS"
           WPD_PROPERTY_CAPABILITIES_FORMAT, "WPD_PROPERTY_CAPABILITIES_FORMAT"
           WPD_PROPERTY_CAPABILITIES_FORMATS, "WPD_PROPERTY_CAPABILITIES_FORMATS"
           WPD_PROPERTY_CAPABILITIES_FUNCTIONAL_CATEGORIES, "WPD_PROPERTY_CAPABILITIES_FUNCTIONAL_CATEGORIES"
           WPD_PROPERTY_CAPABILITIES_FUNCTIONAL_CATEGORY, "WPD_PROPERTY_CAPABILITIES_FUNCTIONAL_CATEGORY"
           WPD_PROPERTY_CAPABILITIES_FUNCTIONAL_OBJECTS, "WPD_PROPERTY_CAPABILITIES_FUNCTIONAL_OBJECTS"
           WPD_PROPERTY_CAPABILITIES_PROPERTY_ATTRIBUTES, "WPD_PROPERTY_CAPABILITIES_PROPERTY_ATTRIBUTES"
           WPD_PROPERTY_CAPABILITIES_PROPERTY_KEYS, "WPD_PROPERTY_CAPABILITIES_PROPERTY_KEYS"
           WPD_PROPERTY_CAPABILITIES_SUPPORTED_COMMANDS, "WPD_PROPERTY_CAPABILITIES_SUPPORTED_COMMANDS"
           WPD_PROPERTY_CAPABILITIES_SUPPORTED_EVENTS, "WPD_PROPERTY_CAPABILITIES_SUPPORTED_EVENTS"
           
           WPD_PROPERTY_CLASS_EXTENSION_DEVICE_INFORMATION_VALUES, 
           "WPD_PROPERTY_CLASS_EXTENSION_DEVICE_INFORMATION_VALUES"
           
           WPD_PROPERTY_CLASS_EXTENSION_DEVICE_INFORMATION_WRITE_RESULTS, 
           "WPD_PROPERTY_CLASS_EXTENSION_DEVICE_INFORMATION_WRITE_RESULTS"
           WPD_PROPERTY_CLASS_EXTENSION_SERVICE_INTERFACES, "WPD_PROPERTY_CLASS_EXTENSION_SERVICE_INTERFACES"
           WPD_PROPERTY_CLASS_EXTENSION_SERVICE_OBJECT_ID, "WPD_PROPERTY_CLASS_EXTENSION_SERVICE_OBJECT_ID"
           
           WPD_PROPERTY_CLASS_EXTENSION_SERVICE_REGISTRATION_RESULTS, 
           "WPD_PROPERTY_CLASS_EXTENSION_SERVICE_REGISTRATION_RESULTS"
           WPD_PROPERTY_COMMON_ACTIVITY_ID, "WPD_PROPERTY_COMMON_ACTIVITY_ID"
           WPD_PROPERTY_COMMON_CLIENT_INFORMATION, "WPD_PROPERTY_COMMON_CLIENT_INFORMATION"
           WPD_PROPERTY_COMMON_CLIENT_INFORMATION_CONTEXT, "WPD_PROPERTY_COMMON_CLIENT_INFORMATION_CONTEXT"
           WPD_PROPERTY_COMMON_COMMAND_CATEGORY, "WPD_PROPERTY_COMMON_COMMAND_CATEGORY"
           WPD_PROPERTY_COMMON_COMMAND_ID, "WPD_PROPERTY_COMMON_COMMAND_ID"
           WPD_PROPERTY_COMMON_COMMAND_TARGET, "WPD_PROPERTY_COMMON_COMMAND_TARGET"
           WPD_PROPERTY_COMMON_DRIVER_ERROR_CODE, "WPD_PROPERTY_COMMON_DRIVER_ERROR_CODE"
           WPD_PROPERTY_COMMON_HRESULT, "WPD_PROPERTY_COMMON_HRESULT"
           WPD_PROPERTY_COMMON_OBJECT_IDS, "WPD_PROPERTY_COMMON_OBJECT_IDS"
           WPD_PROPERTY_COMMON_PERSISTENT_UNIQUE_IDS, "WPD_PROPERTY_COMMON_PERSISTENT_UNIQUE_IDS"
           WPD_PROPERTY_DEVICE_HINTS_CONTENT_LOCATIONS, "WPD_PROPERTY_DEVICE_HINTS_CONTENT_LOCATIONS"
           WPD_PROPERTY_DEVICE_HINTS_CONTENT_TYPE, "WPD_PROPERTY_DEVICE_HINTS_CONTENT_TYPE"
           WPD_PROPERTY_NULL, "WPD_PROPERTY_NULL"
           WPD_PROPERTY_OBJECT_ENUMERATION_CONTEXT, "WPD_PROPERTY_OBJECT_ENUMERATION_CONTEXT"
           WPD_PROPERTY_OBJECT_ENUMERATION_FILTER, "WPD_PROPERTY_OBJECT_ENUMERATION_FILTER"
           
           WPD_PROPERTY_OBJECT_ENUMERATION_NUM_OBJECTS_REQUESTED, 
           "WPD_PROPERTY_OBJECT_ENUMERATION_NUM_OBJECTS_REQUESTED"
           WPD_PROPERTY_OBJECT_ENUMERATION_OBJECT_IDS, "WPD_PROPERTY_OBJECT_ENUMERATION_OBJECT_IDS"
           WPD_PROPERTY_OBJECT_ENUMERATION_PARENT_ID, "WPD_PROPERTY_OBJECT_ENUMERATION_PARENT_ID"
           WPD_PROPERTY_OBJECT_MANAGEMENT_CONTEXT, "WPD_PROPERTY_OBJECT_MANAGEMENT_CONTEXT"
           WPD_PROPERTY_OBJECT_MANAGEMENT_COPY_RESULTS, "WPD_PROPERTY_OBJECT_MANAGEMENT_COPY_RESULTS"
           WPD_PROPERTY_OBJECT_MANAGEMENT_CREATION_PROPERTIES, "WPD_PROPERTY_OBJECT_MANAGEMENT_CREATION_PROPERTIES"
           WPD_PROPERTY_OBJECT_MANAGEMENT_DATA, "WPD_PROPERTY_OBJECT_MANAGEMENT_DATA"
           WPD_PROPERTY_OBJECT_MANAGEMENT_DELETE_OPTIONS, "WPD_PROPERTY_OBJECT_MANAGEMENT_DELETE_OPTIONS"
           WPD_PROPERTY_OBJECT_MANAGEMENT_DELETE_RESULTS, "WPD_PROPERTY_OBJECT_MANAGEMENT_DELETE_RESULTS"
           
           WPD_PROPERTY_OBJECT_MANAGEMENT_DESTINATION_FOLDER_OBJECT_ID, 
           "WPD_PROPERTY_OBJECT_MANAGEMENT_DESTINATION_FOLDER_OBJECT_ID"
           WPD_PROPERTY_OBJECT_MANAGEMENT_MOVE_RESULTS, "WPD_PROPERTY_OBJECT_MANAGEMENT_MOVE_RESULTS"
           WPD_PROPERTY_OBJECT_MANAGEMENT_NUM_BYTES_TO_WRITE, "WPD_PROPERTY_OBJECT_MANAGEMENT_NUM_BYTES_TO_WRITE"
           WPD_PROPERTY_OBJECT_MANAGEMENT_NUM_BYTES_WRITTEN, "WPD_PROPERTY_OBJECT_MANAGEMENT_NUM_BYTES_WRITTEN"
           WPD_PROPERTY_OBJECT_MANAGEMENT_OBJECT_FORMAT, "WPD_PROPERTY_OBJECT_MANAGEMENT_OBJECT_FORMAT"
           WPD_PROPERTY_OBJECT_MANAGEMENT_OBJECT_ID, "WPD_PROPERTY_OBJECT_MANAGEMENT_OBJECT_ID"
           WPD_PROPERTY_OBJECT_MANAGEMENT_OBJECT_IDS, "WPD_PROPERTY_OBJECT_MANAGEMENT_OBJECT_IDS"
           
           WPD_PROPERTY_OBJECT_MANAGEMENT_OPTIMAL_TRANSFER_BUFFER_SIZE, 
           "WPD_PROPERTY_OBJECT_MANAGEMENT_OPTIMAL_TRANSFER_BUFFER_SIZE"
           WPD_PROPERTY_OBJECT_MANAGEMENT_PROPERTY_KEYS, "WPD_PROPERTY_OBJECT_MANAGEMENT_PROPERTY_KEYS"
           WPD_PROPERTY_OBJECT_MANAGEMENT_UPDATE_PROPERTIES, "WPD_PROPERTY_OBJECT_MANAGEMENT_UPDATE_PROPERTIES"
           WPD_PROPERTY_OBJECT_PROPERTIES_BULK_CONTEXT, "WPD_PROPERTY_OBJECT_PROPERTIES_BULK_CONTEXT"
           WPD_PROPERTY_OBJECT_PROPERTIES_BULK_DEPTH, "WPD_PROPERTY_OBJECT_PROPERTIES_BULK_DEPTH"
           WPD_PROPERTY_OBJECT_PROPERTIES_BULK_OBJECT_FORMAT, "WPD_PROPERTY_OBJECT_PROPERTIES_BULK_OBJECT_FORMAT"
           WPD_PROPERTY_OBJECT_PROPERTIES_BULK_OBJECT_IDS, "WPD_PROPERTY_OBJECT_PROPERTIES_BULK_OBJECT_IDS"
           WPD_PROPERTY_OBJECT_PROPERTIES_BULK_PARENT_OBJECT_ID, "WPD_PROPERTY_OBJECT_PROPERTIES_BULK_PARENT_OBJECT_ID"
           WPD_PROPERTY_OBJECT_PROPERTIES_BULK_PROPERTY_KEYS, "WPD_PROPERTY_OBJECT_PROPERTIES_BULK_PROPERTY_KEYS"
           WPD_PROPERTY_OBJECT_PROPERTIES_BULK_VALUES, "WPD_PROPERTY_OBJECT_PROPERTIES_BULK_VALUES"
           WPD_PROPERTY_OBJECT_PROPERTIES_BULK_WRITE_RESULTS, "WPD_PROPERTY_OBJECT_PROPERTIES_BULK_WRITE_RESULTS"
           WPD_PROPERTY_OBJECT_PROPERTIES_OBJECT_ID, "WPD_PROPERTY_OBJECT_PROPERTIES_OBJECT_ID"
           WPD_PROPERTY_OBJECT_PROPERTIES_PROPERTY_ATTRIBUTES, "WPD_PROPERTY_OBJECT_PROPERTIES_PROPERTY_ATTRIBUTES"
           
           WPD_PROPERTY_OBJECT_PROPERTIES_PROPERTY_DELETE_RESULTS, 
           "WPD_PROPERTY_OBJECT_PROPERTIES_PROPERTY_DELETE_RESULTS"
           WPD_PROPERTY_OBJECT_PROPERTIES_PROPERTY_KEYS, "WPD_PROPERTY_OBJECT_PROPERTIES_PROPERTY_KEYS"
           WPD_PROPERTY_OBJECT_PROPERTIES_PROPERTY_VALUES, "WPD_PROPERTY_OBJECT_PROPERTIES_PROPERTY_VALUES"
           
           WPD_PROPERTY_OBJECT_PROPERTIES_PROPERTY_WRITE_RESULTS, 
           "WPD_PROPERTY_OBJECT_PROPERTIES_PROPERTY_WRITE_RESULTS"
           WPD_PROPERTY_OBJECT_RESOURCES_ACCESS_MODE, "WPD_PROPERTY_OBJECT_RESOURCES_ACCESS_MODE"
           WPD_PROPERTY_OBJECT_RESOURCES_CONTEXT, "WPD_PROPERTY_OBJECT_RESOURCES_CONTEXT"
           WPD_PROPERTY_OBJECT_RESOURCES_DATA, "WPD_PROPERTY_OBJECT_RESOURCES_DATA"
           WPD_PROPERTY_OBJECT_RESOURCES_NUM_BYTES_READ, "WPD_PROPERTY_OBJECT_RESOURCES_NUM_BYTES_READ"
           WPD_PROPERTY_OBJECT_RESOURCES_NUM_BYTES_TO_READ, "WPD_PROPERTY_OBJECT_RESOURCES_NUM_BYTES_TO_READ"
           WPD_PROPERTY_OBJECT_RESOURCES_NUM_BYTES_TO_WRITE, "WPD_PROPERTY_OBJECT_RESOURCES_NUM_BYTES_TO_WRITE"
           WPD_PROPERTY_OBJECT_RESOURCES_NUM_BYTES_WRITTEN, "WPD_PROPERTY_OBJECT_RESOURCES_NUM_BYTES_WRITTEN"
           WPD_PROPERTY_OBJECT_RESOURCES_OBJECT_ID, "WPD_PROPERTY_OBJECT_RESOURCES_OBJECT_ID"
           
           WPD_PROPERTY_OBJECT_RESOURCES_OPTIMAL_TRANSFER_BUFFER_SIZE, 
           "WPD_PROPERTY_OBJECT_RESOURCES_OPTIMAL_TRANSFER_BUFFER_SIZE"
           WPD_PROPERTY_OBJECT_RESOURCES_POSITION_FROM_START, "WPD_PROPERTY_OBJECT_RESOURCES_POSITION_FROM_START"
           WPD_PROPERTY_OBJECT_RESOURCES_RESOURCE_ATTRIBUTES, "WPD_PROPERTY_OBJECT_RESOURCES_RESOURCE_ATTRIBUTES"
           WPD_PROPERTY_OBJECT_RESOURCES_RESOURCE_KEYS, "WPD_PROPERTY_OBJECT_RESOURCES_RESOURCE_KEYS"
           WPD_PROPERTY_OBJECT_RESOURCES_SEEK_OFFSET, "WPD_PROPERTY_OBJECT_RESOURCES_SEEK_OFFSET"
           WPD_PROPERTY_OBJECT_RESOURCES_SEEK_ORIGIN_FLAG, "WPD_PROPERTY_OBJECT_RESOURCES_SEEK_ORIGIN_FLAG"
           WPD_PROPERTY_OBJECT_RESOURCES_STREAM_UNITS, "WPD_PROPERTY_OBJECT_RESOURCES_STREAM_UNITS"
           WPD_PROPERTY_OBJECT_RESOURCES_SUPPORTS_UNITS, "WPD_PROPERTY_OBJECT_RESOURCES_SUPPORTS_UNITS"
           WPD_PROPERTY_PUBLIC_KEY, "WPD_PROPERTY_PUBLIC_KEY"
           WPD_PROPERTY_SERVICE_CAPABILITIES_COMMAND, "WPD_PROPERTY_SERVICE_CAPABILITIES_COMMAND"
           WPD_PROPERTY_SERVICE_CAPABILITIES_COMMAND_OPTIONS, "WPD_PROPERTY_SERVICE_CAPABILITIES_COMMAND_OPTIONS"
           WPD_PROPERTY_SERVICE_CAPABILITIES_EVENT, "WPD_PROPERTY_SERVICE_CAPABILITIES_EVENT"
           WPD_PROPERTY_SERVICE_CAPABILITIES_EVENT_ATTRIBUTES, "WPD_PROPERTY_SERVICE_CAPABILITIES_EVENT_ATTRIBUTES"
           WPD_PROPERTY_SERVICE_CAPABILITIES_FORMAT, "WPD_PROPERTY_SERVICE_CAPABILITIES_FORMAT"
           WPD_PROPERTY_SERVICE_CAPABILITIES_FORMAT_ATTRIBUTES, "WPD_PROPERTY_SERVICE_CAPABILITIES_FORMAT_ATTRIBUTES"
           WPD_PROPERTY_SERVICE_CAPABILITIES_FORMATS, "WPD_PROPERTY_SERVICE_CAPABILITIES_FORMATS"
           WPD_PROPERTY_SERVICE_CAPABILITIES_INHERITANCE_TYPE, "WPD_PROPERTY_SERVICE_CAPABILITIES_INHERITANCE_TYPE"
           WPD_PROPERTY_SERVICE_CAPABILITIES_INHERITED_SERVICES, "WPD_PROPERTY_SERVICE_CAPABILITIES_INHERITED_SERVICES"
           WPD_PROPERTY_SERVICE_CAPABILITIES_METHOD, "WPD_PROPERTY_SERVICE_CAPABILITIES_METHOD"
           WPD_PROPERTY_SERVICE_CAPABILITIES_METHOD_ATTRIBUTES, "WPD_PROPERTY_SERVICE_CAPABILITIES_METHOD_ATTRIBUTES"
           WPD_PROPERTY_SERVICE_CAPABILITIES_PARAMETER, "WPD_PROPERTY_SERVICE_CAPABILITIES_PARAMETER"
           
           WPD_PROPERTY_SERVICE_CAPABILITIES_PARAMETER_ATTRIBUTES, 
           "WPD_PROPERTY_SERVICE_CAPABILITIES_PARAMETER_ATTRIBUTES"
           
           WPD_PROPERTY_SERVICE_CAPABILITIES_PROPERTY_ATTRIBUTES, 
           "WPD_PROPERTY_SERVICE_CAPABILITIES_PROPERTY_ATTRIBUTES"
           WPD_PROPERTY_SERVICE_CAPABILITIES_PROPERTY_KEYS, "WPD_PROPERTY_SERVICE_CAPABILITIES_PROPERTY_KEYS"
           WPD_PROPERTY_SERVICE_CAPABILITIES_RENDERING_PROFILES, "WPD_PROPERTY_SERVICE_CAPABILITIES_RENDERING_PROFILES"
           WPD_PROPERTY_SERVICE_CAPABILITIES_SUPPORTED_COMMANDS, "WPD_PROPERTY_SERVICE_CAPABILITIES_SUPPORTED_COMMANDS"
           WPD_PROPERTY_SERVICE_CAPABILITIES_SUPPORTED_EVENTS, "WPD_PROPERTY_SERVICE_CAPABILITIES_SUPPORTED_EVENTS"
           WPD_PROPERTY_SERVICE_CAPABILITIES_SUPPORTED_METHODS, "WPD_PROPERTY_SERVICE_CAPABILITIES_SUPPORTED_METHODS"
           WPD_PROPERTY_SERVICE_METHOD, "WPD_PROPERTY_SERVICE_METHOD"
           WPD_PROPERTY_SERVICE_METHOD_CONTEXT, "WPD_PROPERTY_SERVICE_METHOD_CONTEXT"
           WPD_PROPERTY_SERVICE_METHOD_HRESULT, "WPD_PROPERTY_SERVICE_METHOD_HRESULT"
           WPD_PROPERTY_SERVICE_METHOD_PARAMETER_VALUES, "WPD_PROPERTY_SERVICE_METHOD_PARAMETER_VALUES"
           WPD_PROPERTY_SERVICE_METHOD_RESULT_VALUES, "WPD_PROPERTY_SERVICE_METHOD_RESULT_VALUES"
           WPD_PROPERTY_SERVICE_OBJECT_ID, "WPD_PROPERTY_SERVICE_OBJECT_ID"
           WPD_PROPERTY_SMS_BINARY_MESSAGE, "WPD_PROPERTY_SMS_BINARY_MESSAGE"
           WPD_PROPERTY_SMS_MESSAGE_TYPE, "WPD_PROPERTY_SMS_MESSAGE_TYPE"
           WPD_PROPERTY_SMS_RECIPIENT, "WPD_PROPERTY_SMS_RECIPIENT"
           WPD_PROPERTY_SMS_TEXT_MESSAGE, "WPD_PROPERTY_SMS_TEXT_MESSAGE"
           WPD_PROPERTY_STORAGE_DESTINATION_OBJECT_ID, "WPD_PROPERTY_STORAGE_DESTINATION_OBJECT_ID"
           WPD_PROPERTY_STORAGE_OBJECT_ID, "WPD_PROPERTY_STORAGE_OBJECT_ID"
           
           WPD_RENDERING_INFORMATION_PROFILE_ENTRY_CREATABLE_RESOURCES, 
           "WPD_RENDERING_INFORMATION_PROFILE_ENTRY_CREATABLE_RESOURCES"
           WPD_RENDERING_INFORMATION_PROFILE_ENTRY_TYPE, "WPD_RENDERING_INFORMATION_PROFILE_ENTRY_TYPE"
           WPD_RENDERING_INFORMATION_PROFILES, "WPD_RENDERING_INFORMATION_PROFILES"
           WPD_RESOURCE_ALBUM_ART, "WPD_RESOURCE_ALBUM_ART"
           WPD_RESOURCE_ATTRIBUTE_CAN_DELETE, "WPD_RESOURCE_ATTRIBUTE_CAN_DELETE"
           WPD_RESOURCE_ATTRIBUTE_CAN_READ, "WPD_RESOURCE_ATTRIBUTE_CAN_READ"
           WPD_RESOURCE_ATTRIBUTE_CAN_WRITE, "WPD_RESOURCE_ATTRIBUTE_CAN_WRITE"
           WPD_RESOURCE_ATTRIBUTE_FORMAT, "WPD_RESOURCE_ATTRIBUTE_FORMAT"
           WPD_RESOURCE_ATTRIBUTE_OPTIMAL_READ_BUFFER_SIZE, "WPD_RESOURCE_ATTRIBUTE_OPTIMAL_READ_BUFFER_SIZE"
           WPD_RESOURCE_ATTRIBUTE_OPTIMAL_WRITE_BUFFER_SIZE, "WPD_RESOURCE_ATTRIBUTE_OPTIMAL_WRITE_BUFFER_SIZE"
           WPD_RESOURCE_ATTRIBUTE_RESOURCE_KEY, "WPD_RESOURCE_ATTRIBUTE_RESOURCE_KEY"
           WPD_RESOURCE_ATTRIBUTE_TOTAL_SIZE, "WPD_RESOURCE_ATTRIBUTE_TOTAL_SIZE"
           WPD_RESOURCE_AUDIO_CLIP, "WPD_RESOURCE_AUDIO_CLIP"
           WPD_RESOURCE_BRANDING_ART, "WPD_RESOURCE_BRANDING_ART"
           WPD_RESOURCE_CONTACT_PHOTO, "WPD_RESOURCE_CONTACT_PHOTO"
           WPD_RESOURCE_DEFAULT, "WPD_RESOURCE_DEFAULT"
           WPD_RESOURCE_GENERIC, "WPD_RESOURCE_GENERIC"
           WPD_RESOURCE_ICON, "WPD_RESOURCE_ICON"
           WPD_RESOURCE_THUMBNAIL, "WPD_RESOURCE_THUMBNAIL"
           WPD_RESOURCE_VIDEO_CLIP, "WPD_RESOURCE_VIDEO_CLIP"
           WPD_SECTION_DATA_LENGTH, "WPD_SECTION_DATA_LENGTH"
           WPD_SECTION_DATA_OFFSET, "WPD_SECTION_DATA_OFFSET"
           WPD_SECTION_DATA_REFERENCED_OBJECT_RESOURCE, "WPD_SECTION_DATA_REFERENCED_OBJECT_RESOURCE"
           WPD_SECTION_DATA_UNITS, "WPD_SECTION_DATA_UNITS"
           WPD_SERVICE_VERSION, "WPD_SERVICE_VERSION"
           WPD_SMS_ENCODING, "WPD_SMS_ENCODING"
           WPD_SMS_MAX_PAYLOAD, "WPD_SMS_MAX_PAYLOAD"
           WPD_SMS_PROVIDER, "WPD_SMS_PROVIDER"
           WPD_SMS_TIMEOUT, "WPD_SMS_TIMEOUT"
           WPD_STILL_IMAGE_ARTIST, "WPD_STILL_IMAGE_ARTIST"
           WPD_STILL_IMAGE_BURST_INTERVAL, "WPD_STILL_IMAGE_BURST_INTERVAL"
           WPD_STILL_IMAGE_BURST_NUMBER, "WPD_STILL_IMAGE_BURST_NUMBER"
           WPD_STILL_IMAGE_CAMERA_MANUFACTURER, "WPD_STILL_IMAGE_CAMERA_MANUFACTURER"
           WPD_STILL_IMAGE_CAMERA_MODEL, "WPD_STILL_IMAGE_CAMERA_MODEL"
           WPD_STILL_IMAGE_CAPTURE_DELAY, "WPD_STILL_IMAGE_CAPTURE_DELAY"
           WPD_STILL_IMAGE_CAPTURE_FORMAT, "WPD_STILL_IMAGE_CAPTURE_FORMAT"
           WPD_STILL_IMAGE_CAPTURE_MODE, "WPD_STILL_IMAGE_CAPTURE_MODE"
           WPD_STILL_IMAGE_CAPTURE_RESOLUTION, "WPD_STILL_IMAGE_CAPTURE_RESOLUTION"
           WPD_STILL_IMAGE_COMPRESSION_SETTING, "WPD_STILL_IMAGE_COMPRESSION_SETTING"
           WPD_STILL_IMAGE_CONTRAST, "WPD_STILL_IMAGE_CONTRAST"
           WPD_STILL_IMAGE_DIGITAL_ZOOM, "WPD_STILL_IMAGE_DIGITAL_ZOOM"
           WPD_STILL_IMAGE_EFFECT_MODE, "WPD_STILL_IMAGE_EFFECT_MODE"
           WPD_STILL_IMAGE_EXPOSURE_BIAS_COMPENSATION, "WPD_STILL_IMAGE_EXPOSURE_BIAS_COMPENSATION"
           WPD_STILL_IMAGE_EXPOSURE_INDEX, "WPD_STILL_IMAGE_EXPOSURE_INDEX"
           WPD_STILL_IMAGE_EXPOSURE_METERING_MODE, "WPD_STILL_IMAGE_EXPOSURE_METERING_MODE"
           WPD_STILL_IMAGE_EXPOSURE_PROGRAM_MODE, "WPD_STILL_IMAGE_EXPOSURE_PROGRAM_MODE"
           WPD_STILL_IMAGE_EXPOSURE_TIME, "WPD_STILL_IMAGE_EXPOSURE_TIME"
           WPD_STILL_IMAGE_FLASH_MODE, "WPD_STILL_IMAGE_FLASH_MODE"
           WPD_STILL_IMAGE_FNUMBER, "WPD_STILL_IMAGE_FNUMBER"
           WPD_STILL_IMAGE_FOCAL_LENGTH, "WPD_STILL_IMAGE_FOCAL_LENGTH"
           WPD_STILL_IMAGE_FOCUS_DISTANCE, "WPD_STILL_IMAGE_FOCUS_DISTANCE"
           WPD_STILL_IMAGE_FOCUS_METERING_MODE, "WPD_STILL_IMAGE_FOCUS_METERING_MODE"
           WPD_STILL_IMAGE_FOCUS_MODE, "WPD_STILL_IMAGE_FOCUS_MODE"
           WPD_STILL_IMAGE_RGB_GAIN, "WPD_STILL_IMAGE_RGB_GAIN"
           WPD_STILL_IMAGE_SHARPNESS, "WPD_STILL_IMAGE_SHARPNESS"
           WPD_STILL_IMAGE_TIMELAPSE_INTERVAL, "WPD_STILL_IMAGE_TIMELAPSE_INTERVAL"
           WPD_STILL_IMAGE_TIMELAPSE_NUMBER, "WPD_STILL_IMAGE_TIMELAPSE_NUMBER"
           WPD_STILL_IMAGE_UPLOAD_URL, "WPD_STILL_IMAGE_UPLOAD_URL"
           WPD_STILL_IMAGE_WHITE_BALANCE, "WPD_STILL_IMAGE_WHITE_BALANCE"
           WPD_STORAGE_ACCESS_CAPABILITY, "WPD_STORAGE_ACCESS_CAPABILITY"
           WPD_STORAGE_CAPACITY, "WPD_STORAGE_CAPACITY"
           WPD_STORAGE_CAPACITY_IN_OBJECTS, "WPD_STORAGE_CAPACITY_IN_OBJECTS"
           WPD_STORAGE_DESCRIPTION, "WPD_STORAGE_DESCRIPTION"
           WPD_STORAGE_FILE_SYSTEM_TYPE, "WPD_STORAGE_FILE_SYSTEM_TYPE"
           WPD_STORAGE_FREE_SPACE_IN_BYTES, "WPD_STORAGE_FREE_SPACE_IN_BYTES"
           WPD_STORAGE_FREE_SPACE_IN_OBJECTS, "WPD_STORAGE_FREE_SPACE_IN_OBJECTS"
           WPD_STORAGE_MAX_OBJECT_SIZE, "WPD_STORAGE_MAX_OBJECT_SIZE"
           WPD_STORAGE_SERIAL_NUMBER, "WPD_STORAGE_SERIAL_NUMBER"
           WPD_STORAGE_TYPE, "WPD_STORAGE_TYPE"
           WPD_TASK_OWNER, "WPD_TASK_OWNER"
           WPD_TASK_PERCENT_COMPLETE, "WPD_TASK_PERCENT_COMPLETE"
           WPD_TASK_REMINDER_DATE, "WPD_TASK_REMINDER_DATE"
           WPD_TASK_STATUS, "WPD_TASK_STATUS"
           WPD_VIDEO_AUTHOR, "WPD_VIDEO_AUTHOR"
           WPD_VIDEO_BITRATE, "WPD_VIDEO_BITRATE"
           WPD_VIDEO_BUFFER_SIZE, "WPD_VIDEO_BUFFER_SIZE"
           WPD_VIDEO_CREDITS, "WPD_VIDEO_CREDITS"
           WPD_VIDEO_FOURCC_CODE, "WPD_VIDEO_FOURCC_CODE"
           WPD_VIDEO_FRAMERATE, "WPD_VIDEO_FRAMERATE"
           WPD_VIDEO_KEY_FRAME_DISTANCE, "WPD_VIDEO_KEY_FRAME_DISTANCE"
           WPD_VIDEO_QUALITY_SETTING, "WPD_VIDEO_QUALITY_SETTING"
           WPD_VIDEO_RECORDEDTV_CHANNEL_NUMBER, "WPD_VIDEO_RECORDEDTV_CHANNEL_NUMBER"
           WPD_VIDEO_RECORDEDTV_REPEAT, "WPD_VIDEO_RECORDEDTV_REPEAT"
           WPD_VIDEO_RECORDEDTV_STATION_NAME, "WPD_VIDEO_RECORDEDTV_STATION_NAME"
           WPD_VIDEO_SCAN_TYPE, "WPD_VIDEO_SCAN_TYPE" |]
        |> dict
    
    let CategoryPropertiesIndex = 
        dict [ WPD_API_OPTIONS_V1, [| 2u; 3u |]
               WPD_APPOINTMENT_OBJECT_PROPERTIES_V1, [| 3u; 7u; 8u; 9u; 10u; 11u; 12u; 13u |]
               
               WPD_CATEGORY_CAPABILITIES, 
               [| 2u; 3u; 4u; 5u; 6u; 7u; 8u; 9u; 10u; 11u; 1001u; 1002u; 1003u; 1004u; 1005u; 1006u; 1007u; 1008u; 
                  1009u; 1010u; 1011u; 1012u; 1013u; 1014u; 1015u |]
               
               WPD_CATEGORY_COMMON, 
               [| 2u; 3u; 4u; 1001u; 1002u; 1003u; 1004u; 1006u; 1007u; 1008u; 1009u; 1010u; 1011u; 5001u |]
               WPD_CATEGORY_DEVICE_HINTS, [| 2u; 1001u; 1002u |]
               WPD_CATEGORY_MEDIA_CAPTURE, [| 2u; 3u; 4u |]
               WPD_CATEGORY_NETWORK_CONFIGURATION, [| 2u; 3u; 4u; 1001u |]
               WPD_CATEGORY_NULL, [| 0u |]
               WPD_CATEGORY_OBJECT_ENUMERATION, [| 2u; 3u; 4u; 1001u; 1002u; 1003u; 1004u; 1005u |]
               
               WPD_CATEGORY_OBJECT_MANAGEMENT, 
               [| 2u; 3u; 4u; 5u; 6u; 7u; 8u; 9u; 10u; 1001u; 1002u; 1003u; 1004u; 1005u; 1006u; 1007u; 1008u; 1009u; 
                  1010u; 1011u; 1012u; 1013u; 1014u; 1015u; 1016u; 5001u |]
               WPD_CATEGORY_OBJECT_PROPERTIES, [| 2u; 3u; 4u; 5u; 6u; 7u; 1001u; 1002u; 1003u; 1004u; 1005u; 1006u |]
               
               WPD_CATEGORY_OBJECT_PROPERTIES_BULK, 
               [| 2u; 3u; 4u; 5u; 6u; 7u; 8u; 9u; 10u; 1001u; 1002u; 1003u; 1004u; 1005u; 1006u; 1007u; 1008u |]
               
               WPD_CATEGORY_OBJECT_RESOURCES, 
               [| 2u; 3u; 4u; 5u; 6u; 7u; 8u; 9u; 10u; 11u; 12u; 13u; 1001u; 1002u; 1003u; 1004u; 1005u; 1006u; 1007u; 
                  1008u; 1009u; 1010u; 1011u; 1012u; 1013u; 1014u; 1015u; 1016u; 5001u; 5002u; 5003u |]
               
               WPD_CATEGORY_SERVICE_CAPABILITIES, 
               [| 2u; 3u; 4u; 5u; 6u; 7u; 8u; 9u; 10u; 11u; 12u; 13u; 14u; 15u; 16u; 1001u; 1002u; 1003u; 1004u; 1005u; 
                  1006u; 1007u; 1008u; 1009u; 1010u; 1011u; 1012u; 1013u; 1014u; 1015u; 1016u; 1017u; 1018u; 1019u |]
               WPD_CATEGORY_SERVICE_COMMON, [| 2u; 1001u |]
               WPD_CATEGORY_SERVICE_METHODS, [| 2u; 3u; 4u; 1001u; 1002u; 1003u; 1004u; 1005u |]
               WPD_CATEGORY_SMS, [| 2u; 1001u; 1002u; 1003u; 1004u; 5001u |]
               WPD_CATEGORY_STILL_IMAGE_CAPTURE, [| 2u |]
               WPD_CATEGORY_STORAGE, [| 2u; 4u; 1001u; 1002u |]
               WPD_CLASS_EXTENSION_OPTIONS_V1, [| 2u; 3u; 4u |]
               WPD_CLASS_EXTENSION_OPTIONS_V2, [| 2u; 3u; 4u |]
               WPD_CLASS_EXTENSION_OPTIONS_V3, [| 2u |]
               WPD_CLASS_EXTENSION_V1, [| 2u; 1001u; 1002u |]
               WPD_CLASS_EXTENSION_V2, [| 2u; 3u; 1001u; 1002u; 1003u |]
               WPD_CLIENT_INFORMATION_PROPERTIES_V1, [| 2u; 3u; 4u; 5u; 6u; 7u; 8u; 9u; 10u; 11u; 12u; 13u |]
               WPD_COMMON_INFORMATION_OBJECT_PROPERTIES_V1, [| 2u; 3u; 4u; 5u; 6u; 7u |]
               
               WPD_CONTACT_OBJECT_PROPERTIES_V1, 
               [| 2u; 3u; 4u; 5u; 6u; 7u; 8u; 9u; 10u; 11u; 12u; 13u; 14u; 15u; 16u; 17u; 18u; 19u; 20u; 21u; 22u; 23u; 
                  24u; 25u; 26u; 27u; 28u; 29u; 30u; 31u; 32u; 33u; 34u; 35u; 36u; 37u; 38u; 39u; 40u; 41u; 42u; 43u; 
                  44u; 45u; 46u; 47u; 48u; 49u; 50u; 51u; 52u; 53u; 54u; 55u; 56u; 57u; 58u; 59u; 60u; 61u; 62u; 63u |]
               WPD_DEVICE_PROPERTIES_V1, [| 2u; 3u; 4u; 5u; 6u; 7u; 8u; 9u; 10u; 11u; 12u; 13u; 14u; 15u; 16u |]
               WPD_DEVICE_PROPERTIES_V2, [| 2u; 3u; 4u; 5u |]
               WPD_EMAIL_OBJECT_PROPERTIES_V1, [| 2u; 3u; 4u; 7u; 8u; 9u; 10u |]
               WPD_EVENT_ATTRIBUTES_V1, [| 2u; 3u; 4u |]
               WPD_EVENT_OPTIONS_V1, [| 2u; 3u |]
               WPD_EVENT_PROPERTIES_V1, [| 2u; 3u; 4u; 5u; 6u; 7u; 8u |]
               WPD_EVENT_PROPERTIES_V2, [| 2u |]
               WPD_FOLDER_OBJECT_PROPERTIES_V1, [| 2u |]
               WPD_FORMAT_ATTRIBUTES_V1, [| 2u; 3u |]
               WPD_FUNCTIONAL_OBJECT_PROPERTIES_V1, [| 2u |]
               WPD_IMAGE_OBJECT_PROPERTIES_V1, [| 3u; 4u; 5u; 6u; 7u; 8u; 9u; 10u |]
               
               WPD_MEDIA_PROPERTIES_V1, 
               [| 2u; 3u; 4u; 5u; 6u; 7u; 8u; 9u; 10u; 11u; 12u; 13u; 14u; 15u; 16u; 17u; 18u; 19u; 20u; 21u; 22u; 23u; 
                  24u; 25u; 26u; 27u; 28u; 29u; 30u; 31u; 32u; 33u; 34u; 35u; 36u; 37u; 38u; 39u; 49u |]
               WPD_METHOD_ATTRIBUTES_V1, [| 2u; 3u; 4u; 5u |]
               WPD_MUSIC_OBJECT_PROPERTIES_V1, [| 3u; 4u; 6u; 8u; 9u; 10u; 11u; 12u; 13u |]
               WPD_NETWORK_ASSOCIATION_PROPERTIES_V1, [| 2u; 3u |]
               
               WPD_OBJECT_PROPERTIES_V1, 
               [| 7u; 14u; 23u; 24u; 25u; 2u; 3u; 4u; 5u; 6u; 9u; 10u; 11u; 12u; 13u; 15u; 16u; 17u; 18u; 19u; 20u; 21u; 
                  26u; 27u |]
               WPD_OBJECT_PROPERTIES_V2, [| 2u |]
               WPD_PARAMETER_ATTRIBUTES_V1, [| 2u; 3u; 4u; 5u; 6u; 7u; 8u; 9u; 10u; 11u; 12u; 13u |]
               WPD_PROPERTY_ATTRIBUTES_V1, [| 2u; 3u; 4u; 5u; 6u; 7u; 8u; 9u; 10u; 11u; 12u; 13u |]
               WPD_PROPERTY_ATTRIBUTES_V2, [| 2u; 3u |]
               WPD_RENDERING_INFORMATION_OBJECT_PROPERTIES_V1, [| 2u; 3u; 4u |]
               WPD_RESOURCE_ALBUM_ART_Guid, [| 0u |]
               WPD_RESOURCE_ATTRIBUTES_V1, [| 2u; 3u; 4u; 5u; 6u; 7u; 8u; 9u |]
               WPD_RESOURCE_AUDIO_CLIP_Guid, [| 0u |]
               WPD_RESOURCE_BRANDING_ART_Guid, [| 0u |]
               WPD_RESOURCE_CONTACT_PHOTO_Guid, [| 0u |]
               WPD_RESOURCE_DEFAULT_Guid, [| 0u |]
               WPD_RESOURCE_GENERIC_Guid, [| 0u |]
               WPD_RESOURCE_ICON_Guid, [| 0u |]
               WPD_RESOURCE_THUMBNAIL_Guid, [| 0u |]
               WPD_RESOURCE_VIDEO_CLIP_Guid, [| 0u |]
               WPD_SECTION_OBJECT_PROPERTIES_V1, [| 2u; 3u; 4u; 5u |]
               WPD_SERVICE_PROPERTIES_V1, [| 2u |]
               WPD_SMS_OBJECT_PROPERTIES_V1, [| 2u; 3u; 4u; 5u |]
               
               WPD_STILL_IMAGE_CAPTURE_OBJECT_PROPERTIES_V1, 
               [| 2u; 3u; 4u; 5u; 6u; 7u; 8u; 9u; 10u; 11u; 12u; 13u; 14u; 15u; 16u; 17u; 18u; 19u; 20u; 21u; 22u; 23u; 
                  24u; 25u; 26u; 27u; 28u; 29u; 30u; 31u |]
               WPD_STORAGE_OBJECT_PROPERTIES_V1, [| 2u; 3u; 4u; 5u; 6u; 7u; 8u; 9u; 10u; 11u |]
               WPD_TASK_OBJECT_PROPERTIES_V1, [| 6u; 8u; 10u; 11u |]
               WPD_VIDEO_OBJECT_PROPERTIES_V1, [| 2u; 4u; 5u; 7u; 8u; 9u; 10u; 11u; 12u; 13u; 14u; 15u |] ]
