namespace PortableDevices

module PDHeaderDecoder =     
    open PortableDeviceApiLib

    let ParseProperty (tag : _tagpropertykey) = 
        match (sprintf "%A" tag.fmtid ) with
        | "3e3595da-4d71-49fe-a0b4-d4406c3ae93f" -> 
            match (tag.pid) with 
            | 2u -> "[ VT_BOOL ] WPD_CLASS_EXTENSION_OPTIONS_V2.WPD_CLASS_EXTENSION_OPTIONS_MULTITRANSPORT_MODE"
            | 3u -> "[ VT_UNKNOWN ] WPD_CLASS_EXTENSION_OPTIONS_V2.WPD_CLASS_EXTENSION_OPTIONS_DEVICE_IDENTIFICATION_VALUES"
            | 4u -> "[ VT_UI4 ] WPD_CLASS_EXTENSION_OPTIONS_V2.WPD_CLASS_EXTENSION_OPTIONS_TRANSPORT_BANDWIDTH"
            | _ -> sprintf "Variant type %u not found" tag.pid
        | "a0a02000-bcaf-4be8-b3f5-233f231cf58f" -> 
            match (tag.pid) with 
            | 2u -> "[ VT_LPWSTR ] WPD_FORMAT_ATTRIBUTES_V1.WPD_FORMAT_ATTRIBUTE_NAME"
            | 3u -> "[ VT_LPWSTR ] WPD_FORMAT_ATTRIBUTES_V1.WPD_FORMAT_ATTRIBUTE_MIMETYPE"
            | _ -> sprintf "Variant type %u not found" tag.pid
        | "346f2163-f998-4146-8b01-d19b4c00de9a" -> 
            match (tag.pid) with 
            | 2u -> "[ VT_LPWSTR ] WPD_VIDEO_OBJECT_PROPERTIES_V1.WPD_VIDEO_AUTHOR"
            | 4u -> "[ VT_LPWSTR ] WPD_VIDEO_OBJECT_PROPERTIES_V1.WPD_VIDEO_RECORDEDTV_STATION_NAME"
            | 5u -> "[ VT_UI4 ] WPD_VIDEO_OBJECT_PROPERTIES_V1.WPD_VIDEO_RECORDEDTV_CHANNEL_NUMBER"
            | 7u -> "[ VT_BOOL ] WPD_VIDEO_OBJECT_PROPERTIES_V1.WPD_VIDEO_RECORDEDTV_REPEAT"
            | 8u -> "[ VT_UI4 ] WPD_VIDEO_OBJECT_PROPERTIES_V1.WPD_VIDEO_BUFFER_SIZE"
            | 9u -> "[ VT_LPWSTR ] WPD_VIDEO_OBJECT_PROPERTIES_V1.WPD_VIDEO_CREDITS"
            | 10u -> "[ VT_UI4 ] WPD_VIDEO_OBJECT_PROPERTIES_V1.WPD_VIDEO_KEY_FRAME_DISTANCE"
            | 11u -> "[ VT_UI4 ] WPD_VIDEO_OBJECT_PROPERTIES_V1.WPD_VIDEO_QUALITY_SETTING"
            | 12u -> "[ VT_UI4 ] WPD_VIDEO_OBJECT_PROPERTIES_V1.WPD_VIDEO_SCAN_TYPE"
            | 13u -> "[ VT_UI4 ] WPD_VIDEO_OBJECT_PROPERTIES_V1.WPD_VIDEO_BITRATE"
            | 14u -> "[ VT_UI4 ] WPD_VIDEO_OBJECT_PROPERTIES_V1.WPD_VIDEO_FOURCC_CODE"
            | 15u -> "[ VT_UI4 ] WPD_VIDEO_OBJECT_PROPERTIES_V1.WPD_VIDEO_FRAMERATE"
            | _ -> sprintf "Variant type %u not found" tag.pid
        | "b28ae94b-05a4-4e8e-be01-72cc7e099d8f" -> 
            match (tag.pid) with 
            | 2u -> "[ VT_LPWSTR ] WPD_COMMON_INFORMATION_OBJECT_PROPERTIES_V1.WPD_COMMON_INFORMATION_SUBJECT"
            | 3u -> "[ VT_LPWSTR ] WPD_COMMON_INFORMATION_OBJECT_PROPERTIES_V1.WPD_COMMON_INFORMATION_BODY_TEXT"
            | 4u -> "[ VT_UI4 ] WPD_COMMON_INFORMATION_OBJECT_PROPERTIES_V1.WPD_COMMON_INFORMATION_PRIORITY"
            | 5u -> "[ VT_DATE ] WPD_COMMON_INFORMATION_OBJECT_PROPERTIES_V1.WPD_COMMON_INFORMATION_START_DATETIME"
            | 6u -> "[ VT_DATE ] WPD_COMMON_INFORMATION_OBJECT_PROPERTIES_V1.WPD_COMMON_INFORMATION_END_DATETIME"
            | 7u -> "[ VT_LPWSTR ] WPD_COMMON_INFORMATION_OBJECT_PROPERTIES_V1.WPD_COMMON_INFORMATION_NOTES"
            | _ -> sprintf "Variant type %u not found" tag.pid
        | "ab7943d8-6332-445f-a00d-8d5ef1e96f37" -> 
            match (tag.pid) with 
            | 2u -> "[ VT_UI4 ] WPD_PROPERTY_ATTRIBUTES_V1.WPD_PROPERTY_ATTRIBUTE_FORM"
            | 3u -> "[ VT_BOOL ] WPD_PROPERTY_ATTRIBUTES_V1.WPD_PROPERTY_ATTRIBUTE_CAN_READ"
            | 4u -> "[ VT_BOOL ] WPD_PROPERTY_ATTRIBUTES_V1.WPD_PROPERTY_ATTRIBUTE_CAN_WRITE"
            | 5u -> "[ VT_BOOL ] WPD_PROPERTY_ATTRIBUTES_V1.WPD_PROPERTY_ATTRIBUTE_CAN_DELETE"
            | 6u -> "[ VT_XXXX ] WPD_PROPERTY_ATTRIBUTES_V1.WPD_PROPERTY_ATTRIBUTE_DEFAULT_VALUE"
            | 7u -> "[ VT_BOOL ] WPD_PROPERTY_ATTRIBUTES_V1.WPD_PROPERTY_ATTRIBUTE_FAST_PROPERTY"
            | 8u -> "[ VT_XXXX ] WPD_PROPERTY_ATTRIBUTES_V1.WPD_PROPERTY_ATTRIBUTE_RANGE_MIN"
            | 9u -> "[ VT_XXXX ] WPD_PROPERTY_ATTRIBUTES_V1.WPD_PROPERTY_ATTRIBUTE_RANGE_MAX"
            | 10u -> "[ VT_XXXX ] WPD_PROPERTY_ATTRIBUTES_V1.WPD_PROPERTY_ATTRIBUTE_RANGE_STEP"
            | 11u -> "[ VT_UNKNOWN ] WPD_PROPERTY_ATTRIBUTES_V1.WPD_PROPERTY_ATTRIBUTE_ENUMERATION_ELEMENTS"
            | 12u -> "[ VT_LPWSTR ] WPD_PROPERTY_ATTRIBUTES_V1.WPD_PROPERTY_ATTRIBUTE_REGULAR_EXPRESSION"
            | 13u -> "[ VT_UI8 ] WPD_PROPERTY_ATTRIBUTES_V1.WPD_PROPERTY_ATTRIBUTE_MAX_SIZE"
            | _ -> sprintf "Variant type %u not found" tag.pid
        | "11c824dd-04cd-4e4e-8c7b-f6efb794d84e" -> 
            match (tag.pid) with 
            | 2u -> "[ Required ] WPD_CATEGORY_OBJECT_PROPERTIES_BULK.WPD_COMMAND_OBJECT_PROPERTIES_BULK_GET_VALUES_BY_OBJECT_LIST_START"
            | 3u -> "[ Required ] WPD_CATEGORY_OBJECT_PROPERTIES_BULK.WPD_COMMAND_OBJECT_PROPERTIES_BULK_GET_VALUES_BY_OBJECT_LIST_NEXT"
            | 4u -> "[ Required ] WPD_CATEGORY_OBJECT_PROPERTIES_BULK.WPD_COMMAND_OBJECT_PROPERTIES_BULK_GET_VALUES_BY_OBJECT_LIST_END"
            | 5u -> "[ Required ] WPD_CATEGORY_OBJECT_PROPERTIES_BULK.WPD_COMMAND_OBJECT_PROPERTIES_BULK_GET_VALUES_BY_OBJECT_FORMAT_START"
            | 6u -> "[ Required ] WPD_CATEGORY_OBJECT_PROPERTIES_BULK.WPD_COMMAND_OBJECT_PROPERTIES_BULK_GET_VALUES_BY_OBJECT_FORMAT_NEXT"
            | 7u -> "[ Required ] WPD_CATEGORY_OBJECT_PROPERTIES_BULK.WPD_COMMAND_OBJECT_PROPERTIES_BULK_GET_VALUES_BY_OBJECT_FORMAT_END"
            | 8u -> "[ Required ] WPD_CATEGORY_OBJECT_PROPERTIES_BULK.WPD_COMMAND_OBJECT_PROPERTIES_BULK_SET_VALUES_BY_OBJECT_LIST_START"
            | 9u -> "[ Required ] WPD_CATEGORY_OBJECT_PROPERTIES_BULK.WPD_COMMAND_OBJECT_PROPERTIES_BULK_SET_VALUES_BY_OBJECT_LIST_NEXT"
            | 10u -> "[ Required ] WPD_CATEGORY_OBJECT_PROPERTIES_BULK.WPD_COMMAND_OBJECT_PROPERTIES_BULK_SET_VALUES_BY_OBJECT_LIST_END"
            | 1001u -> "[ VT_UNKNOWN ] WPD_CATEGORY_OBJECT_PROPERTIES_BULK.WPD_PROPERTY_OBJECT_PROPERTIES_BULK_OBJECT_IDS"
            | 1002u -> "[ VT_LPWSTR ] WPD_CATEGORY_OBJECT_PROPERTIES_BULK.WPD_PROPERTY_OBJECT_PROPERTIES_BULK_CONTEXT"
            | 1003u -> "[ VT_UNKNOWN ] WPD_CATEGORY_OBJECT_PROPERTIES_BULK.WPD_PROPERTY_OBJECT_PROPERTIES_BULK_VALUES"
            | 1004u -> "[ VT_UNKNOWN ] WPD_CATEGORY_OBJECT_PROPERTIES_BULK.WPD_PROPERTY_OBJECT_PROPERTIES_BULK_PROPERTY_KEYS"
            | 1005u -> "[ VT_UI4 ] WPD_CATEGORY_OBJECT_PROPERTIES_BULK.WPD_PROPERTY_OBJECT_PROPERTIES_BULK_DEPTH"
            | 1006u -> "[ VT_LPWSTR ] WPD_CATEGORY_OBJECT_PROPERTIES_BULK.WPD_PROPERTY_OBJECT_PROPERTIES_BULK_PARENT_OBJECT_ID"
            | 1007u -> "[ VT_CLSID ] WPD_CATEGORY_OBJECT_PROPERTIES_BULK.WPD_PROPERTY_OBJECT_PROPERTIES_BULK_OBJECT_FORMAT"
            | 1008u -> "[ VT_UNKNOWN ] WPD_CATEGORY_OBJECT_PROPERTIES_BULK.WPD_PROPERTY_OBJECT_PROPERTIES_BULK_WRITE_RESULTS"
            | _ -> sprintf "Variant type %u not found" tag.pid
        | "26d4979a-e643-4626-9e2b-736dc0c92fdc" -> 
            match (tag.pid) with 
            | 2u -> "[ VT_LPWSTR ] WPD_DEVICE_PROPERTIES_V1.WPD_DEVICE_SYNC_PARTNER"
            | 3u -> "[ VT_LPWSTR ] WPD_DEVICE_PROPERTIES_V1.WPD_DEVICE_FIRMWARE_VERSION"
            | 4u -> "[ VT_UI4 ] WPD_DEVICE_PROPERTIES_V1.WPD_DEVICE_POWER_LEVEL"
            | 5u -> "[ VT_UI4 ] WPD_DEVICE_PROPERTIES_V1.WPD_DEVICE_POWER_SOURCE"
            | 6u -> "[ VT_LPWSTR ] WPD_DEVICE_PROPERTIES_V1.WPD_DEVICE_PROTOCOL"
            | 7u -> "[ VT_LPWSTR ] WPD_DEVICE_PROPERTIES_V1.WPD_DEVICE_MANUFACTURER"
            | 8u -> "[ VT_LPWSTR ] WPD_DEVICE_PROPERTIES_V1.WPD_DEVICE_MODEL"
            | 9u -> "[ VT_LPWSTR ] WPD_DEVICE_PROPERTIES_V1.WPD_DEVICE_SERIAL_NUMBER"
            | 10u -> "[ VT_BOOL ] WPD_DEVICE_PROPERTIES_V1.WPD_DEVICE_SUPPORTS_NON_CONSUMABLE"
            | 11u -> "[ VT_DATE ] WPD_DEVICE_PROPERTIES_V1.WPD_DEVICE_DATETIME"
            | 12u -> "[ VT_LPWSTR ] WPD_DEVICE_PROPERTIES_V1.WPD_DEVICE_FRIENDLY_NAME"
            | 13u -> "[ VT_UNKNOWN ] WPD_DEVICE_PROPERTIES_V1.WPD_DEVICE_SUPPORTED_DRM_SCHEMES"
            | 14u -> "[ VT_BOOL ] WPD_DEVICE_PROPERTIES_V1.WPD_DEVICE_SUPPORTED_FORMATS_ARE_ORDERED"
            | 15u -> "[ VT_UI4 ] WPD_DEVICE_PROPERTIES_V1.WPD_DEVICE_TYPE"
            | 16u -> "[ VT_UI8 ] WPD_DEVICE_PROPERTIES_V1.WPD_DEVICE_NETWORK_IDENTIFIER"
            | _ -> sprintf "Variant type %u not found" tag.pid
        | "9e5582e4-0814-44e6-981a-b2998d583804" -> 
            match (tag.pid) with 
            | 2u -> "[ Required ] WPD_CATEGORY_OBJECT_PROPERTIES.WPD_COMMAND_OBJECT_PROPERTIES_GET_SUPPORTED"
            | 3u -> "[ Required ] WPD_CATEGORY_OBJECT_PROPERTIES.WPD_COMMAND_OBJECT_PROPERTIES_GET_ATTRIBUTES"
            | 4u -> "[ Required ] WPD_CATEGORY_OBJECT_PROPERTIES.WPD_COMMAND_OBJECT_PROPERTIES_GET"
            | 5u -> "[ Required ] WPD_CATEGORY_OBJECT_PROPERTIES.WPD_COMMAND_OBJECT_PROPERTIES_SET"
            | 6u -> "[ Required ] WPD_CATEGORY_OBJECT_PROPERTIES.WPD_COMMAND_OBJECT_PROPERTIES_GET_ALL"
            | 7u -> "[ Optional ] WPD_CATEGORY_OBJECT_PROPERTIES.WPD_COMMAND_OBJECT_PROPERTIES_DELETE"
            | 1001u -> "[ VT_LPWSTR ] WPD_CATEGORY_OBJECT_PROPERTIES.WPD_PROPERTY_OBJECT_PROPERTIES_OBJECT_ID"
            | 1002u -> "[ VT_UNKNOWN ] WPD_CATEGORY_OBJECT_PROPERTIES.WPD_PROPERTY_OBJECT_PROPERTIES_PROPERTY_KEYS"
            | 1003u -> "[ VT_UNKNOWN ] WPD_CATEGORY_OBJECT_PROPERTIES.WPD_PROPERTY_OBJECT_PROPERTIES_PROPERTY_ATTRIBUTES"
            | 1004u -> "[ VT_UNKNOWN ] WPD_CATEGORY_OBJECT_PROPERTIES.WPD_PROPERTY_OBJECT_PROPERTIES_PROPERTY_VALUES"
            | 1005u -> "[ VT_UNKNOWN ] WPD_CATEGORY_OBJECT_PROPERTIES.WPD_PROPERTY_OBJECT_PROPERTIES_PROPERTY_WRITE_RESULTS"
            | 1006u -> "[ VT_UNKNOWN ] WPD_CATEGORY_OBJECT_PROPERTIES.WPD_PROPERTY_OBJECT_PROPERTIES_PROPERTY_DELETE_RESULTS"
            | _ -> sprintf "Variant type %u not found" tag.pid
        | "63d64908-9fa1-479f-85ba-9952216447db" -> 
            match (tag.pid) with 
            | 3u -> "[ VT_UI4 ] WPD_IMAGE_OBJECT_PROPERTIES_V1.WPD_IMAGE_BITDEPTH"
            | 4u -> "[ VT_UI4 ] WPD_IMAGE_OBJECT_PROPERTIES_V1.WPD_IMAGE_CROPPED_STATUS"
            | 5u -> "[ VT_UI4 ] WPD_IMAGE_OBJECT_PROPERTIES_V1.WPD_IMAGE_COLOR_CORRECTED_STATUS"
            | 6u -> "[ VT_UI4 ] WPD_IMAGE_OBJECT_PROPERTIES_V1.WPD_IMAGE_FNUMBER"
            | 7u -> "[ VT_UI4 ] WPD_IMAGE_OBJECT_PROPERTIES_V1.WPD_IMAGE_EXPOSURE_TIME"
            | 8u -> "[ VT_UI4 ] WPD_IMAGE_OBJECT_PROPERTIES_V1.WPD_IMAGE_EXPOSURE_INDEX"
            | 9u -> "[ VT_R8 ] WPD_IMAGE_OBJECT_PROPERTIES_V1.WPD_IMAGE_HORIZONTAL_RESOLUTION"
            | 10u -> "[ VT_R8 ] WPD_IMAGE_OBJECT_PROPERTIES_V1.WPD_IMAGE_VERTICAL_RESOLUTION"
            | _ -> sprintf "Variant type %u not found" tag.pid
        | "2d521ca8-c1b0-4268-a342-cf19321569bc" -> 
            match (tag.pid) with 
            | 2u -> "[ Required ] WPD_CATEGORY_SERVICE_METHODS.WPD_COMMAND_SERVICE_METHODS_START_INVOKE"
            | 3u -> "[ Required ] WPD_CATEGORY_SERVICE_METHODS.WPD_COMMAND_SERVICE_METHODS_CANCEL_INVOKE"
            | 4u -> "[ Required ] WPD_CATEGORY_SERVICE_METHODS.WPD_COMMAND_SERVICE_METHODS_END_INVOKE"
            | 1001u -> "[ VT_CLSID ] WPD_CATEGORY_SERVICE_METHODS.WPD_PROPERTY_SERVICE_METHOD"
            | 1002u -> "[ VT_UNKNOWN ] WPD_CATEGORY_SERVICE_METHODS.WPD_PROPERTY_SERVICE_METHOD_PARAMETER_VALUES"
            | 1003u -> "[ VT_UNKNOWN ] WPD_CATEGORY_SERVICE_METHODS.WPD_PROPERTY_SERVICE_METHOD_RESULT_VALUES"
            | 1004u -> "[ VT_LPWSTR ] WPD_CATEGORY_SERVICE_METHODS.WPD_PROPERTY_SERVICE_METHOD_CONTEXT"
            | 1005u -> "[ VT_ERROR ] WPD_CATEGORY_SERVICE_METHODS.WPD_PROPERTY_SERVICE_METHOD_HRESULT"
            | _ -> sprintf "Variant type %u not found" tag.pid
        | "78f9c6fc-79b8-473c-9060-6bd23dd072c4" -> 
            match (tag.pid) with 
            | 2u -> "[ Required ] WPD_CATEGORY_NETWORK_CONFIGURATION.WPD_COMMAND_GENERATE_KEYPAIR"
            | 3u -> "[ Required ] WPD_CATEGORY_NETWORK_CONFIGURATION.WPD_COMMAND_COMMIT_KEYPAIR"
            | 4u -> "[ Required ] WPD_CATEGORY_NETWORK_CONFIGURATION.WPD_COMMAND_PROCESS_WIRELESS_PROFILE"
            | 1001u -> " WPD_CATEGORY_NETWORK_CONFIGURATION.WPD_PROPERTY_PUBLIC_KEY"
            | _ -> sprintf "Variant type %u not found" tag.pid
        | "15ab1953-f817-4fef-a921-5676e838f6e0" -> 
            match (tag.pid) with 
            | 2u -> "[ VT_LPWSTR ] WPD_EVENT_PROPERTIES_V1.WPD_EVENT_PARAMETER_PNP_DEVICE_ID"
            | 3u -> "[ VT_CLSID ] WPD_EVENT_PROPERTIES_V1.WPD_EVENT_PARAMETER_EVENT_ID"
            | 4u -> "[ VT_UI4 ] WPD_EVENT_PROPERTIES_V1.WPD_EVENT_PARAMETER_OPERATION_STATE"
            | 5u -> "[ VT_UI4 ] WPD_EVENT_PROPERTIES_V1.WPD_EVENT_PARAMETER_OPERATION_PROGRESS"
            | 6u -> "[ VT_LPWSTR ] WPD_EVENT_PROPERTIES_V1.WPD_EVENT_PARAMETER_OBJECT_PARENT_PERSISTENT_UNIQUE_ID"
            | 7u -> "[ VT_LPWSTR ] WPD_EVENT_PROPERTIES_V1.WPD_EVENT_PARAMETER_OBJECT_CREATION_COOKIE"
            | 8u -> "[ VT_BOOL ] WPD_EVENT_PROPERTIES_V1.WPD_EVENT_PARAMETER_CHILD_HIERARCHY_CHANGED"
            | _ -> sprintf "Variant type %u not found" tag.pid
        | "59b433ba-fe44-4d8d-808c-6bcb9b0f15e8" -> 
            match (tag.pid) with 
            | 2u -> "[ Required ] WPD_CATEGORY_MEDIA_CAPTURE.WPD_COMMAND_MEDIA_CAPTURE_START"
            | 3u -> "[ Required ] WPD_CATEGORY_MEDIA_CAPTURE.WPD_COMMAND_MEDIA_CAPTURE_STOP"
            | 4u -> "[ Required ] WPD_CATEGORY_MEDIA_CAPTURE.WPD_COMMAND_MEDIA_CAPTURE_PAUSE"
            | _ -> sprintf "Variant type %u not found" tag.pid
        | "58c571ec-1bcb-42a7-8ac5-bb291573a260" -> 
            match (tag.pid) with 
            | 2u -> "[ VT_LPWSTR ] WPD_STILL_IMAGE_CAPTURE_OBJECT_PROPERTIES_V1.WPD_STILL_IMAGE_CAPTURE_RESOLUTION"
            | 3u -> "[ VT_CLSID ] WPD_STILL_IMAGE_CAPTURE_OBJECT_PROPERTIES_V1.WPD_STILL_IMAGE_CAPTURE_FORMAT"
            | 4u -> "[ VT_UI8 ] WPD_STILL_IMAGE_CAPTURE_OBJECT_PROPERTIES_V1.WPD_STILL_IMAGE_COMPRESSION_SETTING"
            | 5u -> "[ VT_UI4 ] WPD_STILL_IMAGE_CAPTURE_OBJECT_PROPERTIES_V1.WPD_STILL_IMAGE_WHITE_BALANCE"
            | 6u -> "[ VT_LPWSTR ] WPD_STILL_IMAGE_CAPTURE_OBJECT_PROPERTIES_V1.WPD_STILL_IMAGE_RGB_GAIN"
            | 7u -> "[ VT_UI4 ] WPD_STILL_IMAGE_CAPTURE_OBJECT_PROPERTIES_V1.WPD_STILL_IMAGE_FNUMBER"
            | 8u -> "[ VT_UI4 ] WPD_STILL_IMAGE_CAPTURE_OBJECT_PROPERTIES_V1.WPD_STILL_IMAGE_FOCAL_LENGTH"
            | 9u -> "[ VT_UI4 ] WPD_STILL_IMAGE_CAPTURE_OBJECT_PROPERTIES_V1.WPD_STILL_IMAGE_FOCUS_DISTANCE"
            | 10u -> "[ VT_UI4 ] WPD_STILL_IMAGE_CAPTURE_OBJECT_PROPERTIES_V1.WPD_STILL_IMAGE_FOCUS_MODE"
            | 11u -> "[ VT_UI4 ] WPD_STILL_IMAGE_CAPTURE_OBJECT_PROPERTIES_V1.WPD_STILL_IMAGE_EXPOSURE_METERING_MODE"
            | 12u -> "[ VT_UI4 ] WPD_STILL_IMAGE_CAPTURE_OBJECT_PROPERTIES_V1.WPD_STILL_IMAGE_FLASH_MODE"
            | 13u -> "[ VT_UI4 ] WPD_STILL_IMAGE_CAPTURE_OBJECT_PROPERTIES_V1.WPD_STILL_IMAGE_EXPOSURE_TIME"
            | 14u -> "[ VT_UI4 ] WPD_STILL_IMAGE_CAPTURE_OBJECT_PROPERTIES_V1.WPD_STILL_IMAGE_EXPOSURE_PROGRAM_MODE"
            | 15u -> "[ VT_UI4 ] WPD_STILL_IMAGE_CAPTURE_OBJECT_PROPERTIES_V1.WPD_STILL_IMAGE_EXPOSURE_INDEX"
            | 16u -> "[ VT_I4 ] WPD_STILL_IMAGE_CAPTURE_OBJECT_PROPERTIES_V1.WPD_STILL_IMAGE_EXPOSURE_BIAS_COMPENSATION"
            | 17u -> "[ VT_UI4 ] WPD_STILL_IMAGE_CAPTURE_OBJECT_PROPERTIES_V1.WPD_STILL_IMAGE_CAPTURE_DELAY"
            | 18u -> "[ VT_UI4 ] WPD_STILL_IMAGE_CAPTURE_OBJECT_PROPERTIES_V1.WPD_STILL_IMAGE_CAPTURE_MODE"
            | 19u -> "[ VT_UI4 ] WPD_STILL_IMAGE_CAPTURE_OBJECT_PROPERTIES_V1.WPD_STILL_IMAGE_CONTRAST"
            | 20u -> "[ VT_UI4 ] WPD_STILL_IMAGE_CAPTURE_OBJECT_PROPERTIES_V1.WPD_STILL_IMAGE_SHARPNESS"
            | 21u -> "[ VT_UI4 ] WPD_STILL_IMAGE_CAPTURE_OBJECT_PROPERTIES_V1.WPD_STILL_IMAGE_DIGITAL_ZOOM"
            | 22u -> "[ VT_UI4 ] WPD_STILL_IMAGE_CAPTURE_OBJECT_PROPERTIES_V1.WPD_STILL_IMAGE_EFFECT_MODE"
            | 23u -> "[ VT_UI4 ] WPD_STILL_IMAGE_CAPTURE_OBJECT_PROPERTIES_V1.WPD_STILL_IMAGE_BURST_NUMBER"
            | 24u -> "[ VT_UI4 ] WPD_STILL_IMAGE_CAPTURE_OBJECT_PROPERTIES_V1.WPD_STILL_IMAGE_BURST_INTERVAL"
            | 25u -> "[ VT_UI4 ] WPD_STILL_IMAGE_CAPTURE_OBJECT_PROPERTIES_V1.WPD_STILL_IMAGE_TIMELAPSE_NUMBER"
            | 26u -> "[ VT_UI4 ] WPD_STILL_IMAGE_CAPTURE_OBJECT_PROPERTIES_V1.WPD_STILL_IMAGE_TIMELAPSE_INTERVAL"
            | 27u -> "[ VT_UI4 ] WPD_STILL_IMAGE_CAPTURE_OBJECT_PROPERTIES_V1.WPD_STILL_IMAGE_FOCUS_METERING_MODE"
            | 28u -> "[ VT_LPWSTR ] WPD_STILL_IMAGE_CAPTURE_OBJECT_PROPERTIES_V1.WPD_STILL_IMAGE_UPLOAD_URL"
            | 29u -> "[ VT_LPWSTR ] WPD_STILL_IMAGE_CAPTURE_OBJECT_PROPERTIES_V1.WPD_STILL_IMAGE_ARTIST"
            | 30u -> "[ VT_LPWSTR ] WPD_STILL_IMAGE_CAPTURE_OBJECT_PROPERTIES_V1.WPD_STILL_IMAGE_CAMERA_MODEL"
            | 31u -> "[ VT_LPWSTR ] WPD_STILL_IMAGE_CAPTURE_OBJECT_PROPERTIES_V1.WPD_STILL_IMAGE_CAMERA_MANUFACTURER"
            | _ -> sprintf "Variant type %u not found" tag.pid
        | "7510698a-cb54-481c-b8db-0d75c93f1c06" -> 
            match (tag.pid) with 
            | 2u -> "[ VT_LPWSTR ] WPD_SERVICE_PROPERTIES_V1.WPD_SERVICE_VERSION"
            | _ -> sprintf "Variant type %u not found" tag.pid
        | "10c96578-2e81-4111-adde-e08ca6138f6d" -> 
            match (tag.pid) with 
            | 2u -> "[ VT_LPWSTR ] WPD_EVENT_ATTRIBUTES_V1.WPD_EVENT_ATTRIBUTE_NAME"
            | 3u -> "[ VT_UNKNOWN ] WPD_EVENT_ATTRIBUTES_V1.WPD_EVENT_ATTRIBUTE_PARAMETERS"
            | 4u -> "[ VT_UNKNOWN ] WPD_EVENT_ATTRIBUTES_V1.WPD_EVENT_ATTRIBUTE_OPTIONS"
            | _ -> sprintf "Variant type %u not found" tag.pid
        | "7f0779b5-fa2b-4766-9cb2-f73ba30b6758" -> 
            match (tag.pid) with 
            | 2u -> "[ Required ] WPD_CLASS_EXTENSION_V2.WPD_COMMAND_CLASS_EXTENSION_REGISTER_SERVICE_INTERFACES"
            | 3u -> "[ Required ] WPD_CLASS_EXTENSION_V2.WPD_COMMAND_CLASS_EXTENSION_UNREGISTER_SERVICE_INTERFACES"
            | 1001u -> "[ VT_LPWSTR ] WPD_CLASS_EXTENSION_V2.WPD_PROPERTY_CLASS_EXTENSION_SERVICE_OBJECT_ID"
            | 1002u -> "[ VT_UNKNOWN ] WPD_CLASS_EXTENSION_V2.WPD_PROPERTY_CLASS_EXTENSION_SERVICE_INTERFACES"
            | 1003u -> "[ VT_UNKNOWN ] WPD_CLASS_EXTENSION_V2.WPD_PROPERTY_CLASS_EXTENSION_SERVICE_REGISTRATION_RESULTS"
            | _ -> sprintf "Variant type %u not found" tag.pid
        | "afc25d66-fe0d-4114-9097-970c93e920d1" -> 
            match (tag.pid) with 
            | 2u -> "[ Optional ] WPD_CATEGORY_SMS.WPD_COMMAND_SMS_SEND"
            | 1001u -> "[ VT_LPWSTR ] WPD_CATEGORY_SMS.WPD_PROPERTY_SMS_RECIPIENT"
            | 1002u -> "[ VT_UI4 ] WPD_CATEGORY_SMS.WPD_PROPERTY_SMS_MESSAGE_TYPE"
            | 1003u -> "[ VT_LPWSTR ] WPD_CATEGORY_SMS.WPD_PROPERTY_SMS_TEXT_MESSAGE"
            | 1004u -> " WPD_CATEGORY_SMS.WPD_PROPERTY_SMS_BINARY_MESSAGE"
            | 5001u -> "[ VT_BOOL ] WPD_CATEGORY_SMS.WPD_OPTION_SMS_BINARY_MESSAGE_SUPPORTED"
            | _ -> sprintf "Variant type %u not found" tag.pid
        | "fbd4fdab-987d-4777-b3f9-726185a9312b" -> 
            match (tag.pid) with 
            | 2u -> "[ VT_LPWSTR ] WPD_CONTACT_OBJECT_PROPERTIES_V1.WPD_CONTACT_DISPLAY_NAME"
            | 3u -> "[ VT_LPWSTR ] WPD_CONTACT_OBJECT_PROPERTIES_V1.WPD_CONTACT_FIRST_NAME"
            | 4u -> "[ VT_LPWSTR ] WPD_CONTACT_OBJECT_PROPERTIES_V1.WPD_CONTACT_MIDDLE_NAMES"
            | 5u -> "[ VT_LPWSTR ] WPD_CONTACT_OBJECT_PROPERTIES_V1.WPD_CONTACT_LAST_NAME"
            | 6u -> "[ VT_LPWSTR ] WPD_CONTACT_OBJECT_PROPERTIES_V1.WPD_CONTACT_PREFIX"
            | 7u -> "[ VT_LPWSTR ] WPD_CONTACT_OBJECT_PROPERTIES_V1.WPD_CONTACT_SUFFIX"
            | 8u -> "[ VT_LPWSTR ] WPD_CONTACT_OBJECT_PROPERTIES_V1.WPD_CONTACT_PHONETIC_FIRST_NAME"
            | 9u -> "[ VT_LPWSTR ] WPD_CONTACT_OBJECT_PROPERTIES_V1.WPD_CONTACT_PHONETIC_LAST_NAME"
            | 10u -> "[ VT_LPWSTR ] WPD_CONTACT_OBJECT_PROPERTIES_V1.WPD_CONTACT_PERSONAL_FULL_POSTAL_ADDRESS"
            | 11u -> "[ VT_LPWSTR ] WPD_CONTACT_OBJECT_PROPERTIES_V1.WPD_CONTACT_PERSONAL_POSTAL_ADDRESS_LINE1"
            | 12u -> "[ VT_LPWSTR ] WPD_CONTACT_OBJECT_PROPERTIES_V1.WPD_CONTACT_PERSONAL_POSTAL_ADDRESS_LINE2"
            | 13u -> "[ VT_LPWSTR ] WPD_CONTACT_OBJECT_PROPERTIES_V1.WPD_CONTACT_PERSONAL_POSTAL_ADDRESS_CITY"
            | 14u -> "[ VT_LPWSTR ] WPD_CONTACT_OBJECT_PROPERTIES_V1.WPD_CONTACT_PERSONAL_POSTAL_ADDRESS_REGION"
            | 15u -> "[ VT_LPWSTR ] WPD_CONTACT_OBJECT_PROPERTIES_V1.WPD_CONTACT_PERSONAL_POSTAL_ADDRESS_POSTAL_CODE"
            | 16u -> "[ VT_LPWSTR ] WPD_CONTACT_OBJECT_PROPERTIES_V1.WPD_CONTACT_PERSONAL_POSTAL_ADDRESS_COUNTRY"
            | 17u -> "[ VT_LPWSTR ] WPD_CONTACT_OBJECT_PROPERTIES_V1.WPD_CONTACT_BUSINESS_FULL_POSTAL_ADDRESS"
            | 18u -> "[ VT_LPWSTR ] WPD_CONTACT_OBJECT_PROPERTIES_V1.WPD_CONTACT_BUSINESS_POSTAL_ADDRESS_LINE1"
            | 19u -> "[ VT_LPWSTR ] WPD_CONTACT_OBJECT_PROPERTIES_V1.WPD_CONTACT_BUSINESS_POSTAL_ADDRESS_LINE2"
            | 20u -> "[ VT_LPWSTR ] WPD_CONTACT_OBJECT_PROPERTIES_V1.WPD_CONTACT_BUSINESS_POSTAL_ADDRESS_CITY"
            | 21u -> "[ VT_LPWSTR ] WPD_CONTACT_OBJECT_PROPERTIES_V1.WPD_CONTACT_BUSINESS_POSTAL_ADDRESS_REGION"
            | 22u -> "[ VT_LPWSTR ] WPD_CONTACT_OBJECT_PROPERTIES_V1.WPD_CONTACT_BUSINESS_POSTAL_ADDRESS_POSTAL_CODE"
            | 23u -> "[ VT_LPWSTR ] WPD_CONTACT_OBJECT_PROPERTIES_V1.WPD_CONTACT_BUSINESS_POSTAL_ADDRESS_COUNTRY"
            | 24u -> "[ VT_LPWSTR ] WPD_CONTACT_OBJECT_PROPERTIES_V1.WPD_CONTACT_OTHER_FULL_POSTAL_ADDRESS"
            | 25u -> "[ VT_LPWSTR ] WPD_CONTACT_OBJECT_PROPERTIES_V1.WPD_CONTACT_OTHER_POSTAL_ADDRESS_LINE1"
            | 26u -> "[ VT_LPWSTR ] WPD_CONTACT_OBJECT_PROPERTIES_V1.WPD_CONTACT_OTHER_POSTAL_ADDRESS_LINE2"
            | 27u -> "[ VT_LPWSTR ] WPD_CONTACT_OBJECT_PROPERTIES_V1.WPD_CONTACT_OTHER_POSTAL_ADDRESS_CITY"
            | 28u -> "[ VT_LPWSTR ] WPD_CONTACT_OBJECT_PROPERTIES_V1.WPD_CONTACT_OTHER_POSTAL_ADDRESS_REGION"
            | 29u -> "[ VT_LPWSTR ] WPD_CONTACT_OBJECT_PROPERTIES_V1.WPD_CONTACT_OTHER_POSTAL_ADDRESS_POSTAL_CODE"
            | 30u -> "[ VT_LPWSTR ] WPD_CONTACT_OBJECT_PROPERTIES_V1.WPD_CONTACT_OTHER_POSTAL_ADDRESS_POSTAL_COUNTRY"
            | 31u -> "[ VT_LPWSTR ] WPD_CONTACT_OBJECT_PROPERTIES_V1.WPD_CONTACT_PRIMARY_EMAIL_ADDRESS"
            | 32u -> "[ VT_LPWSTR ] WPD_CONTACT_OBJECT_PROPERTIES_V1.WPD_CONTACT_PERSONAL_EMAIL"
            | 33u -> "[ VT_LPWSTR ] WPD_CONTACT_OBJECT_PROPERTIES_V1.WPD_CONTACT_PERSONAL_EMAIL2"
            | 34u -> "[ VT_LPWSTR ] WPD_CONTACT_OBJECT_PROPERTIES_V1.WPD_CONTACT_BUSINESS_EMAIL"
            | 35u -> "[ VT_LPWSTR ] WPD_CONTACT_OBJECT_PROPERTIES_V1.WPD_CONTACT_BUSINESS_EMAIL2"
            | 36u -> "[ VT_UNKNOWN ] WPD_CONTACT_OBJECT_PROPERTIES_V1.WPD_CONTACT_OTHER_EMAILS"
            | 37u -> "[ VT_LPWSTR ] WPD_CONTACT_OBJECT_PROPERTIES_V1.WPD_CONTACT_PRIMARY_PHONE"
            | 38u -> "[ VT_LPWSTR ] WPD_CONTACT_OBJECT_PROPERTIES_V1.WPD_CONTACT_PERSONAL_PHONE"
            | 39u -> "[ VT_LPWSTR ] WPD_CONTACT_OBJECT_PROPERTIES_V1.WPD_CONTACT_PERSONAL_PHONE2"
            | 40u -> "[ VT_LPWSTR ] WPD_CONTACT_OBJECT_PROPERTIES_V1.WPD_CONTACT_BUSINESS_PHONE"
            | 41u -> "[ VT_LPWSTR ] WPD_CONTACT_OBJECT_PROPERTIES_V1.WPD_CONTACT_BUSINESS_PHONE2"
            | 42u -> "[ VT_LPWSTR ] WPD_CONTACT_OBJECT_PROPERTIES_V1.WPD_CONTACT_MOBILE_PHONE"
            | 43u -> "[ VT_LPWSTR ] WPD_CONTACT_OBJECT_PROPERTIES_V1.WPD_CONTACT_MOBILE_PHONE2"
            | 44u -> "[ VT_LPWSTR ] WPD_CONTACT_OBJECT_PROPERTIES_V1.WPD_CONTACT_PERSONAL_FAX"
            | 45u -> "[ VT_LPWSTR ] WPD_CONTACT_OBJECT_PROPERTIES_V1.WPD_CONTACT_BUSINESS_FAX"
            | 46u -> "[ VT_LPWSTR ] WPD_CONTACT_OBJECT_PROPERTIES_V1.WPD_CONTACT_PAGER"
            | 47u -> "[ VT_UNKNOWN ] WPD_CONTACT_OBJECT_PROPERTIES_V1.WPD_CONTACT_OTHER_PHONES"
            | 48u -> "[ VT_LPWSTR ] WPD_CONTACT_OBJECT_PROPERTIES_V1.WPD_CONTACT_PRIMARY_WEB_ADDRESS"
            | 49u -> "[ VT_LPWSTR ] WPD_CONTACT_OBJECT_PROPERTIES_V1.WPD_CONTACT_PERSONAL_WEB_ADDRESS"
            | 50u -> "[ VT_LPWSTR ] WPD_CONTACT_OBJECT_PROPERTIES_V1.WPD_CONTACT_BUSINESS_WEB_ADDRESS"
            | 51u -> "[ VT_LPWSTR ] WPD_CONTACT_OBJECT_PROPERTIES_V1.WPD_CONTACT_INSTANT_MESSENGER"
            | 52u -> "[ VT_LPWSTR ] WPD_CONTACT_OBJECT_PROPERTIES_V1.WPD_CONTACT_INSTANT_MESSENGER2"
            | 53u -> "[ VT_LPWSTR ] WPD_CONTACT_OBJECT_PROPERTIES_V1.WPD_CONTACT_INSTANT_MESSENGER3"
            | 54u -> "[ VT_LPWSTR ] WPD_CONTACT_OBJECT_PROPERTIES_V1.WPD_CONTACT_COMPANY_NAME"
            | 55u -> "[ VT_LPWSTR ] WPD_CONTACT_OBJECT_PROPERTIES_V1.WPD_CONTACT_PHONETIC_COMPANY_NAME"
            | 56u -> "[ VT_LPWSTR ] WPD_CONTACT_OBJECT_PROPERTIES_V1.WPD_CONTACT_ROLE"
            | 57u -> "[ VT_DATE ] WPD_CONTACT_OBJECT_PROPERTIES_V1.WPD_CONTACT_BIRTHDATE"
            | 58u -> "[ VT_LPWSTR ] WPD_CONTACT_OBJECT_PROPERTIES_V1.WPD_CONTACT_PRIMARY_FAX"
            | 59u -> "[ VT_LPWSTR ] WPD_CONTACT_OBJECT_PROPERTIES_V1.WPD_CONTACT_SPOUSE"
            | 60u -> "[ VT_UNKNOWN ] WPD_CONTACT_OBJECT_PROPERTIES_V1.WPD_CONTACT_CHILDREN"
            | 61u -> "[ VT_LPWSTR ] WPD_CONTACT_OBJECT_PROPERTIES_V1.WPD_CONTACT_ASSISTANT"
            | 62u -> "[ VT_DATE ] WPD_CONTACT_OBJECT_PROPERTIES_V1.WPD_CONTACT_ANNIVERSARY_DATE"
            | 63u -> "[ VT_LPWSTR ] WPD_CONTACT_OBJECT_PROPERTIES_V1.WPD_CONTACT_RINGTONE"
            | _ -> sprintf "Variant type %u not found" tag.pid
        | "204d9f0c-2292-4080-9f42-40664e70f859" -> 
            match (tag.pid) with 
            | 2u -> "[ VT_LPWSTR ] WPD_CLIENT_INFORMATION_PROPERTIES_V1.WPD_CLIENT_NAME"
            | 3u -> "[ VT_UI4 ] WPD_CLIENT_INFORMATION_PROPERTIES_V1.WPD_CLIENT_MAJOR_VERSION"
            | 4u -> "[ VT_UI4 ] WPD_CLIENT_INFORMATION_PROPERTIES_V1.WPD_CLIENT_MINOR_VERSION"
            | 5u -> "[ VT_UI4 ] WPD_CLIENT_INFORMATION_PROPERTIES_V1.WPD_CLIENT_REVISION"
            | 6u -> " WPD_CLIENT_INFORMATION_PROPERTIES_V1.WPD_CLIENT_WMDRM_APPLICATION_PRIVATE_KEY"
            | 7u -> " WPD_CLIENT_INFORMATION_PROPERTIES_V1.WPD_CLIENT_WMDRM_APPLICATION_CERTIFICATE"
            | 8u -> "[ VT_UI4 ] WPD_CLIENT_INFORMATION_PROPERTIES_V1.WPD_CLIENT_SECURITY_QUALITY_OF_SERVICE"
            | 9u -> "[ VT_UI4 ] WPD_CLIENT_INFORMATION_PROPERTIES_V1.WPD_CLIENT_DESIRED_ACCESS"
            | 10u -> "[ VT_UI4 ] WPD_CLIENT_INFORMATION_PROPERTIES_V1.WPD_CLIENT_SHARE_MODE"
            | 11u -> "[ VT_LPWSTR ] WPD_CLIENT_INFORMATION_PROPERTIES_V1.WPD_CLIENT_EVENT_COOKIE"
            | 12u -> "[ VT_UI4 ] WPD_CLIENT_INFORMATION_PROPERTIES_V1.WPD_CLIENT_MINIMUM_RESULTS_BUFFER_SIZE"
            | 13u -> "[ VT_BOOL ] WPD_CLIENT_INFORMATION_PROPERTIES_V1.WPD_CLIENT_MANUAL_CLOSE_ON_DISCONNECT"
            | _ -> sprintf "Variant type %u not found" tag.pid
        | "1eb6f604-9278-429f-93cc-5bb8c06656b6" -> 
            match (tag.pid) with 
            | 2u -> "[ VT_UI8 ] WPD_RESOURCE_ATTRIBUTES_V1.WPD_RESOURCE_ATTRIBUTE_TOTAL_SIZE"
            | 3u -> "[ VT_BOOL ] WPD_RESOURCE_ATTRIBUTES_V1.WPD_RESOURCE_ATTRIBUTE_CAN_READ"
            | 4u -> "[ VT_BOOL ] WPD_RESOURCE_ATTRIBUTES_V1.WPD_RESOURCE_ATTRIBUTE_CAN_WRITE"
            | 5u -> "[ VT_BOOL ] WPD_RESOURCE_ATTRIBUTES_V1.WPD_RESOURCE_ATTRIBUTE_CAN_DELETE"
            | 6u -> "[ VT_UI4 ] WPD_RESOURCE_ATTRIBUTES_V1.WPD_RESOURCE_ATTRIBUTE_OPTIMAL_READ_BUFFER_SIZE"
            | 7u -> "[ VT_UI4 ] WPD_RESOURCE_ATTRIBUTES_V1.WPD_RESOURCE_ATTRIBUTE_OPTIMAL_WRITE_BUFFER_SIZE"
            | 8u -> "[ VT_CLSID ] WPD_RESOURCE_ATTRIBUTES_V1.WPD_RESOURCE_ATTRIBUTE_FORMAT"
            | 9u -> "[ VT_UNKNOWN ] WPD_RESOURCE_ATTRIBUTES_V1.WPD_RESOURCE_ATTRIBUTE_RESOURCE_KEY"
            | _ -> sprintf "Variant type %u not found" tag.pid
        | "ef6b490d-5cd8-437a-affc-da8b60ee4a3c" -> 
            match (tag.pid) with 
            | 7u -> "[ VT_CLSID ] WPD_OBJECT_PROPERTIES_V1.WPD_OBJECT_CONTENT_TYPE"
            | 14u -> "[ VT_UNKNOWN ] WPD_OBJECT_PROPERTIES_V1.WPD_OBJECT_REFERENCES"
            | 23u -> "[ VT_LPWSTR ] WPD_OBJECT_PROPERTIES_V1.WPD_OBJECT_CONTAINER_FUNCTIONAL_OBJECT_ID"
            | 24u -> "[ VT_BOOL ] WPD_OBJECT_PROPERTIES_V1.WPD_OBJECT_GENERATE_THUMBNAIL_FROM_RESOURCE"
            | 25u -> "[ VT_LPWSTR ] WPD_OBJECT_PROPERTIES_V1.WPD_OBJECT_HINT_LOCATION_DISPLAY_NAME"
            | 2u -> "[ VT_LPWSTR ] legacy_WPD_Properties.WPD_OBJECT_ID"
            | 3u -> "[ VT_LPWSTR ] legacy_WPD_Properties.WPD_OBJECT_PARENT_ID"
            | 4u -> "[ VT_LPWSTR ] legacy_WPD_Properties.WPD_OBJECT_NAME"
            | 5u -> "[ VT_LPWSTR ] legacy_WPD_Properties.WPD_OBJECT_PERSISTENT_UNIQUE_ID"
            | 6u -> "[ VT_CLSID ] legacy_WPD_Properties.WPD_OBJECT_FORMAT"
            | 9u -> "[ VT_BOOL ] legacy_WPD_Properties.WPD_OBJECT_ISHIDDEN"
            | 10u -> "[ VT_BOOL ] legacy_WPD_Properties.WPD_OBJECT_ISSYSTEM"
            | 11u -> "[ VT_UI8 ] legacy_WPD_Properties.WPD_OBJECT_SIZE"
            | 12u -> "[ VT_LPWSTR ] legacy_WPD_Properties.WPD_OBJECT_ORIGINAL_FILE_NAME"
            | 13u -> "[ VT_BOOL ] legacy_WPD_Properties.WPD_OBJECT_NON_CONSUMABLE"
            | 15u -> "[ VT_LPWSTR ] legacy_WPD_Properties.WPD_OBJECT_KEYWORDS"
            | 16u -> "[ VT_LPWSTR ] legacy_WPD_Properties.WPD_OBJECT_SYNC_ID"
            | 17u -> "[ VT_BOOL ] legacy_WPD_Properties.WPD_OBJECT_IS_DRM_PROTECTED"
            | 18u -> "[ VT_DATE ] legacy_WPD_Properties.WPD_OBJECT_DATE_CREATED"
            | 19u -> "[ VT_DATE ] legacy_WPD_Properties.WPD_OBJECT_DATE_MODIFIED"
            | 20u -> "[ VT_DATE ] legacy_WPD_Properties.WPD_OBJECT_DATE_AUTHORED"
            | 21u -> "[ VT_UNKNOWN ] legacy_WPD_Properties.WPD_OBJECT_BACK_REFERENCES"
            | 26u -> "[ VT_BOOL ] legacy_WPD_Properties.WPD_OBJECT_CAN_DELETE"
            | 27u -> "[ VT_LPWSTR ] legacy_WPD_Properties.WPD_OBJECT_LANGUAGE_LOCALE"
            | _ -> sprintf "Variant type %u not found" tag.pid
        | "65c160f8-1367-4ce2-939d-8310839f0d30" -> 
            match (tag.pid) with 
            | 2u -> "[ VT_BOOL ] WPD_CLASS_EXTENSION_OPTIONS_V3.WPD_CLASS_EXTENSION_OPTIONS_SILENCE_AUTOPLAY"
            | _ -> sprintf "Variant type %u not found" tag.pid
        | "b3a2b22d-a595-4108-be0a-fc3c965f3d4a" -> 
            match (tag.pid) with 
            | 2u -> "[ Required ] WPD_CATEGORY_OBJECT_RESOURCES.WPD_COMMAND_OBJECT_RESOURCES_GET_SUPPORTED"
            | 3u -> "[ Required ] WPD_CATEGORY_OBJECT_RESOURCES.WPD_COMMAND_OBJECT_RESOURCES_GET_ATTRIBUTES"
            | 4u -> "[ Optional ] WPD_CATEGORY_OBJECT_RESOURCES.WPD_COMMAND_OBJECT_RESOURCES_OPEN"
            | 5u -> "[ Required ] WPD_CATEGORY_OBJECT_RESOURCES.WPD_COMMAND_OBJECT_RESOURCES_READ"
            | 6u -> "[ Required ] WPD_CATEGORY_OBJECT_RESOURCES.WPD_COMMAND_OBJECT_RESOURCES_WRITE"
            | 7u -> "[ Required ] WPD_CATEGORY_OBJECT_RESOURCES.WPD_COMMAND_OBJECT_RESOURCES_CLOSE"
            | 8u -> "[ Required ] WPD_CATEGORY_OBJECT_RESOURCES.WPD_COMMAND_OBJECT_RESOURCES_DELETE"
            | 9u -> "[ Required ] WPD_CATEGORY_OBJECT_RESOURCES.WPD_COMMAND_OBJECT_RESOURCES_CREATE_RESOURCE"
            | 10u -> "[ Required ] WPD_CATEGORY_OBJECT_RESOURCES.WPD_COMMAND_OBJECT_RESOURCES_REVERT"
            | 11u -> "[ Required ] WPD_CATEGORY_OBJECT_RESOURCES.WPD_COMMAND_OBJECT_RESOURCES_SEEK"
            | 12u -> "[ Required ] WPD_CATEGORY_OBJECT_RESOURCES.WPD_COMMAND_OBJECT_RESOURCES_COMMIT"
            | 13u -> "[ Required ] WPD_CATEGORY_OBJECT_RESOURCES.WPD_COMMAND_OBJECT_RESOURCES_SEEK_IN_UNITS"
            | 1001u -> "[ VT_LPWSTR ] WPD_CATEGORY_OBJECT_RESOURCES.WPD_PROPERTY_OBJECT_RESOURCES_OBJECT_ID"
            | 1002u -> "[ VT_UI4 ] WPD_CATEGORY_OBJECT_RESOURCES.WPD_PROPERTY_OBJECT_RESOURCES_ACCESS_MODE"
            | 1003u -> "[ VT_UNKNOWN ] WPD_CATEGORY_OBJECT_RESOURCES.WPD_PROPERTY_OBJECT_RESOURCES_RESOURCE_KEYS"
            | 1004u -> "[ VT_UNKNOWN ] WPD_CATEGORY_OBJECT_RESOURCES.WPD_PROPERTY_OBJECT_RESOURCES_RESOURCE_ATTRIBUTES"
            | 1005u -> "[ VT_LPWSTR ] WPD_CATEGORY_OBJECT_RESOURCES.WPD_PROPERTY_OBJECT_RESOURCES_CONTEXT"
            | 1006u -> "[ VT_UI4 ] WPD_CATEGORY_OBJECT_RESOURCES.WPD_PROPERTY_OBJECT_RESOURCES_NUM_BYTES_TO_READ"
            | 1007u -> "[ VT_UI4 ] WPD_CATEGORY_OBJECT_RESOURCES.WPD_PROPERTY_OBJECT_RESOURCES_NUM_BYTES_READ"
            | 1008u -> "[ VT_UI4 ] WPD_CATEGORY_OBJECT_RESOURCES.WPD_PROPERTY_OBJECT_RESOURCES_NUM_BYTES_TO_WRITE"
            | 1009u -> "[ VT_UI4 ] WPD_CATEGORY_OBJECT_RESOURCES.WPD_PROPERTY_OBJECT_RESOURCES_NUM_BYTES_WRITTEN"
            | 1010u -> " WPD_CATEGORY_OBJECT_RESOURCES.WPD_PROPERTY_OBJECT_RESOURCES_DATA"
            | 1011u -> "[ VT_UI4 ] WPD_CATEGORY_OBJECT_RESOURCES.WPD_PROPERTY_OBJECT_RESOURCES_OPTIMAL_TRANSFER_BUFFER_SIZE"
            | 1012u -> "[ VT_I8 ] WPD_CATEGORY_OBJECT_RESOURCES.WPD_PROPERTY_OBJECT_RESOURCES_SEEK_OFFSET"
            | 1013u -> "[ VT_UI4 ] WPD_CATEGORY_OBJECT_RESOURCES.WPD_PROPERTY_OBJECT_RESOURCES_SEEK_ORIGIN_FLAG"
            | 1014u -> "[ VT_UI8 ] WPD_CATEGORY_OBJECT_RESOURCES.WPD_PROPERTY_OBJECT_RESOURCES_POSITION_FROM_START"
            | 1015u -> "[ VT_BOOL ] WPD_CATEGORY_OBJECT_RESOURCES.WPD_PROPERTY_OBJECT_RESOURCES_SUPPORTS_UNITS"
            | 1016u -> "[ VT_UI4 ] WPD_CATEGORY_OBJECT_RESOURCES.WPD_PROPERTY_OBJECT_RESOURCES_STREAM_UNITS"
            | 5001u -> "[ VT_BOOL ] WPD_CATEGORY_OBJECT_RESOURCES.WPD_OPTION_OBJECT_RESOURCES_SEEK_ON_READ_SUPPORTED"
            | 5002u -> "[ VT_BOOL ] WPD_CATEGORY_OBJECT_RESOURCES.WPD_OPTION_OBJECT_RESOURCES_SEEK_ON_WRITE_SUPPORTED"
            | 5003u -> "[ VT_BOOL ] WPD_CATEGORY_OBJECT_RESOURCES.WPD_OPTION_OBJECT_RESOURCES_NO_INPUT_BUFFER_ON_READ"
            | _ -> sprintf "Variant type %u not found" tag.pid
        | "463dd662-7fc4-4291-911c-7f4c9cca9799" -> 
            match (tag.pid) with 
            | 2u -> " WPD_DEVICE_PROPERTIES_V2.WPD_DEVICE_FUNCTIONAL_UNIQUE_ID"
            | 3u -> " WPD_DEVICE_PROPERTIES_V2.WPD_DEVICE_MODEL_UNIQUE_ID"
            | 4u -> "[ VT_UI4 ] WPD_DEVICE_PROPERTIES_V2.WPD_DEVICE_TRANSPORT"
            | 5u -> "[ VT_BOOL ] WPD_DEVICE_PROPERTIES_V2.WPD_DEVICE_USE_DEVICE_STAGE"
            | _ -> sprintf "Variant type %u not found" tag.pid
        | "41f8f65a-5484-4782-b13d-4740dd7c37c5" -> 
            match (tag.pid) with 
            | 2u -> "[ VT_LPWSTR ] WPD_EMAIL_OBJECT_PROPERTIES_V1.WPD_EMAIL_TO_LINE"
            | 3u -> "[ VT_LPWSTR ] WPD_EMAIL_OBJECT_PROPERTIES_V1.WPD_EMAIL_CC_LINE"
            | 4u -> "[ VT_LPWSTR ] WPD_EMAIL_OBJECT_PROPERTIES_V1.WPD_EMAIL_BCC_LINE"
            | 7u -> "[ VT_BOOL ] WPD_EMAIL_OBJECT_PROPERTIES_V1.WPD_EMAIL_HAS_BEEN_READ"
            | 8u -> "[ VT_DATE ] WPD_EMAIL_OBJECT_PROPERTIES_V1.WPD_EMAIL_RECEIVED_TIME"
            | 9u -> "[ VT_BOOL ] WPD_EMAIL_OBJECT_PROPERTIES_V1.WPD_EMAIL_HAS_ATTACHMENTS"
            | 10u -> "[ VT_LPWSTR ] WPD_EMAIL_OBJECT_PROPERTIES_V1.WPD_EMAIL_SENDER_ADDRESS"
            | _ -> sprintf "Variant type %u not found" tag.pid
        | "4fcd6982-22a2-4b05-a48b-62d38bf27b32" -> 
            match (tag.pid) with 
            | 2u -> "[ Required ] WPD_CATEGORY_STILL_IMAGE_CAPTURE.WPD_COMMAND_STILL_IMAGE_CAPTURE_INITIATE"
            | _ -> sprintf "Variant type %u not found" tag.pid
        | "e6864dd7-f325-45ea-a1d5-97cf73b6ca58" -> 
            match (tag.pid) with 
            | 2u -> "[ VT_UI4 ] WPD_PARAMETER_ATTRIBUTES_V1.WPD_PARAMETER_ATTRIBUTE_ORDER"
            | 3u -> "[ VT_UI4 ] WPD_PARAMETER_ATTRIBUTES_V1.WPD_PARAMETER_ATTRIBUTE_USAGE"
            | 4u -> "[ VT_UI4 ] WPD_PARAMETER_ATTRIBUTES_V1.WPD_PARAMETER_ATTRIBUTE_FORM"
            | 5u -> "[ VT_XXXX ] WPD_PARAMETER_ATTRIBUTES_V1.WPD_PARAMETER_ATTRIBUTE_DEFAULT_VALUE"
            | 6u -> "[ VT_XXXX ] WPD_PARAMETER_ATTRIBUTES_V1.WPD_PARAMETER_ATTRIBUTE_RANGE_MIN"
            | 7u -> "[ VT_XXXX ] WPD_PARAMETER_ATTRIBUTES_V1.WPD_PARAMETER_ATTRIBUTE_RANGE_MAX"
            | 8u -> "[ VT_XXXX ] WPD_PARAMETER_ATTRIBUTES_V1.WPD_PARAMETER_ATTRIBUTE_RANGE_STEP"
            | 9u -> "[ VT_UNKNOWN ] WPD_PARAMETER_ATTRIBUTES_V1.WPD_PARAMETER_ATTRIBUTE_ENUMERATION_ELEMENTS"
            | 10u -> "[ VT_LPWSTR ] WPD_PARAMETER_ATTRIBUTES_V1.WPD_PARAMETER_ATTRIBUTE_REGULAR_EXPRESSION"
            | 11u -> "[ VT_UI8 ] WPD_PARAMETER_ATTRIBUTES_V1.WPD_PARAMETER_ATTRIBUTE_MAX_SIZE"
            | 12u -> "[ VT_UI4 ] WPD_PARAMETER_ATTRIBUTES_V1.WPD_PARAMETER_ATTRIBUTE_VARTYPE"
            | 13u -> "[ VT_LPWSTR ] WPD_PARAMETER_ATTRIBUTES_V1.WPD_PARAMETER_ATTRIBUTE_NAME"
            | _ -> sprintf "Variant type %u not found" tag.pid
        | "0373cd3d-4a46-40d7-b4d8-73e8da74e775" -> 
            match (tag.pid) with 
            | 2u -> "[ VT_UI4 ] WPD_OBJECT_PROPERTIES_V2.WPD_OBJECT_SUPPORTED_UNITS"
            | _ -> sprintf "Variant type %u not found" tag.pid
        | "e81e79be-34f0-41bf-b53f-f1a06ae87842" -> "RESOURCE_KEYS.WPD_RESOURCE_DEFAULT"
        | "2c4d6803-80ea-4580-af9a-5be1a23eddcb" -> "RESOURCE_KEYS.WPD_RESOURCE_CONTACT_PHOTO"
        | "c7c407ba-98fa-46b5-9960-23fec124cfde" -> "RESOURCE_KEYS.WPD_RESOURCE_THUMBNAIL"
        | "f195fed8-aa28-4ee3-b153-e182dd5edc39" -> "RESOURCE_KEYS.WPD_RESOURCE_ICON"
        | "3bc13982-85b1-48e0-95a6-8d3ad06be117" -> "RESOURCE_KEYS.WPD_RESOURCE_AUDIO_CLIP"
        | "f02aa354-2300-4e2d-a1b9-3b6730f7fa21" -> "RESOURCE_KEYS.WPD_RESOURCE_ALBUM_ART"
        | "b9b9f515-ba70-4647-94dc-fa4925e95a07" -> "RESOURCE_KEYS.WPD_RESOURCE_GENERIC"
        | "b566ee42-6368-4290-8662-70182fb79f20" -> "RESOURCE_KEYS.WPD_RESOURCE_VIDEO_CLIP"
        | "b633b1ae-6caf-4a87-9589-22ded6dd5899" -> "RESOURCE_KEYS.WPD_RESOURCE_BRANDING_ART"          
//        | "ef6b490d-5cd8-437a-affc-da8b60ee4a3c" -> 
//            match (tag.pid) with 
//            | 2u -> "[ VT_LPWSTR ] legacy_WPD_Properties.WPD_OBJECT_ID"
//            | 3u -> "[ VT_LPWSTR ] legacy_WPD_Properties.WPD_OBJECT_PARENT_ID"
//            | 4u -> "[ VT_LPWSTR ] legacy_WPD_Properties.WPD_OBJECT_NAME"
//            | 5u -> "[ VT_LPWSTR ] legacy_WPD_Properties.WPD_OBJECT_PERSISTENT_UNIQUE_ID"
//            | 6u -> "[ VT_CLSID ] legacy_WPD_Properties.WPD_OBJECT_FORMAT"
//            | 9u -> "[ VT_BOOL ] legacy_WPD_Properties.WPD_OBJECT_ISHIDDEN"
//            | 10u -> "[ VT_BOOL ] legacy_WPD_Properties.WPD_OBJECT_ISSYSTEM"
//            | 11u -> "[ VT_UI8 ] legacy_WPD_Properties.WPD_OBJECT_SIZE"
//            | 12u -> "[ VT_LPWSTR ] legacy_WPD_Properties.WPD_OBJECT_ORIGINAL_FILE_NAME"
//            | 13u -> "[ VT_BOOL ] legacy_WPD_Properties.WPD_OBJECT_NON_CONSUMABLE"
//            | 15u -> "[ VT_LPWSTR ] legacy_WPD_Properties.WPD_OBJECT_KEYWORDS"
//            | 16u -> "[ VT_LPWSTR ] legacy_WPD_Properties.WPD_OBJECT_SYNC_ID"
//            | 17u -> "[ VT_BOOL ] legacy_WPD_Properties.WPD_OBJECT_IS_DRM_PROTECTED"
//            | 18u -> "[ VT_DATE ] legacy_WPD_Properties.WPD_OBJECT_DATE_CREATED"
//            | 19u -> "[ VT_DATE ] legacy_WPD_Properties.WPD_OBJECT_DATE_MODIFIED"
//            | 20u -> "[ VT_DATE ] legacy_WPD_Properties.WPD_OBJECT_DATE_AUTHORED"
//            | 21u -> "[ VT_UNKNOWN ] legacy_WPD_Properties.WPD_OBJECT_BACK_REFERENCES"
//            | 26u -> "[ VT_BOOL ] legacy_WPD_Properties.WPD_OBJECT_CAN_DELETE"
//            | 27u -> "[ VT_LPWSTR ] legacy_WPD_Properties.WPD_OBJECT_LANGUAGE_LOCALE"
//            | _ -> sprintf "Variant type %u not found" tag.pid
        | "f17a5071-f039-44af-8efe-432cf32e432a" -> 
            match (tag.pid) with 
            | 2u -> "[ VT_LPWSTR ] WPD_METHOD_ATTRIBUTES_V1.WPD_METHOD_ATTRIBUTE_NAME"
            | 3u -> "[ VT_CLSID ] WPD_METHOD_ATTRIBUTES_V1.WPD_METHOD_ATTRIBUTE_ASSOCIATED_FORMAT"
            | 4u -> "[ VT_UI4 ] WPD_METHOD_ATTRIBUTES_V1.WPD_METHOD_ATTRIBUTE_ACCESS"
            | 5u -> "[ VT_UNKNOWN ] WPD_METHOD_ATTRIBUTES_V1.WPD_METHOD_ATTRIBUTE_PARAMETERS"
            | _ -> sprintf "Variant type %u not found" tag.pid
        | "322f071d-36ef-477f-b4b5-6f52d734baee" -> 
            match (tag.pid) with 
            | 2u -> "[ Required ] WPD_CATEGORY_SERVICE_COMMON.WPD_COMMAND_SERVICE_COMMON_GET_SERVICE_OBJECT_ID"
            | 1001u -> "[ VT_LPWSTR ] WPD_CATEGORY_SERVICE_COMMON.WPD_PROPERTY_SERVICE_OBJECT_ID"
            | _ -> sprintf "Variant type %u not found" tag.pid
        | "52807b8a-4914-4323-9b9a-74f654b2b846" -> 
            match (tag.pid) with 
            | 2u -> "[ VT_LPWSTR ] WPD_EVENT_PROPERTIES_V2.WPD_EVENT_PARAMETER_SERVICE_METHOD_CONTEXT"
            | _ -> sprintf "Variant type %u not found" tag.pid
        | "10e54a3e-052d-4777-a13c-de7614be2bc4" -> 
            match (tag.pid) with 
            | 2u -> "[ VT_BOOL ] WPD_API_OPTIONS_V1.WPD_API_OPTION_USE_CLEAR_DATA_STREAM"
            | 3u -> "[ VT_UI4 ] WPD_API_OPTIONS_V1.WPD_API_OPTION_IOCTL_ACCESS"
            | _ -> sprintf "Variant type %u not found" tag.pid
        | "6309ffef-a87c-4ca7-8434-797576e40a96" -> 
            match (tag.pid) with 
            | 2u -> "[ VT_UNKNOWN ] WPD_CLASS_EXTENSION_OPTIONS_V1.WPD_CLASS_EXTENSION_OPTIONS_SUPPORTED_CONTENT_TYPES"
            | 3u -> "[ VT_BOOL ] WPD_CLASS_EXTENSION_OPTIONS_V1.WPD_CLASS_EXTENSION_OPTIONS_DONT_REGISTER_WPD_DEVICE_INTERFACE"
            | 4u -> "[ VT_BOOL ] WPD_CLASS_EXTENSION_OPTIONS_V1.WPD_CLASS_EXTENSION_OPTIONS_REGISTER_WPD_PRIVATE_DEVICE_INTERFACE"
            | _ -> sprintf "Variant type %u not found" tag.pid
        | "e4c93c1f-b203-43f1-a100-5a07d11b0274" -> 
            match (tag.pid) with 
            | 2u -> " WPD_NETWORK_ASSOCIATION_PROPERTIES_V1.WPD_NETWORK_ASSOCIATION_HOST_NETWORK_IDENTIFIERS"
            | 3u -> " WPD_NETWORK_ASSOCIATION_PROPERTIES_V1.WPD_NETWORK_ASSOCIATION_X509V3SEQUENCE"
            | _ -> sprintf "Variant type %u not found" tag.pid
        | "f0422a9c-5dc8-4440-b5bd-5df28835658a" -> 
            match (tag.pid) with 
            | 2u -> " WPD_CATEGORY_COMMON.WPD_COMMAND_COMMON_RESET_DEVICE"
            | 3u -> "[ Required ] WPD_CATEGORY_COMMON.WPD_COMMAND_COMMON_GET_OBJECT_IDS_FROM_PERSISTENT_UNIQUE_IDS"
            | 4u -> "[ Optional ] WPD_CATEGORY_COMMON.WPD_COMMAND_COMMON_SAVE_CLIENT_INFORMATION"
            | 1001u -> "[ VT_CLSID ] WPD_CATEGORY_COMMON.WPD_PROPERTY_COMMON_COMMAND_CATEGORY"
            | 1002u -> "[ VT_UI4 ] WPD_CATEGORY_COMMON.WPD_PROPERTY_COMMON_COMMAND_ID"
            | 1003u -> "[ VT_ERROR ] WPD_CATEGORY_COMMON.WPD_PROPERTY_COMMON_HRESULT"
            | 1004u -> "[ VT_UI4 ] WPD_CATEGORY_COMMON.WPD_PROPERTY_COMMON_DRIVER_ERROR_CODE"
            | 1006u -> "[ VT_LPWSTR ] WPD_CATEGORY_COMMON.WPD_PROPERTY_COMMON_COMMAND_TARGET"
            | 1007u -> "[ VT_UNKNOWN ] WPD_CATEGORY_COMMON.WPD_PROPERTY_COMMON_PERSISTENT_UNIQUE_IDS"
            | 1008u -> "[ VT_UNKNOWN ] WPD_CATEGORY_COMMON.WPD_PROPERTY_COMMON_OBJECT_IDS"
            | 1009u -> "[ VT_UNKNOWN ] WPD_CATEGORY_COMMON.WPD_PROPERTY_COMMON_CLIENT_INFORMATION"
            | 1010u -> "[ VT_LPWSTR ] WPD_CATEGORY_COMMON.WPD_PROPERTY_COMMON_CLIENT_INFORMATION_CONTEXT"
            | 1011u -> "[ VT_CLSID ] WPD_CATEGORY_COMMON.WPD_PROPERTY_COMMON_ACTIVITY_ID"
            | 5001u -> "[ VT_UNKNOWN ] WPD_CATEGORY_COMMON.WPD_OPTION_VALID_OBJECT_IDS"
            | _ -> sprintf "Variant type %u not found" tag.pid
        | "b3d8dad7-a361-4b83-8a48-5b02ce10713b" -> 
            match (tag.pid) with 
            | 2u -> "[ VT_BOOL ] WPD_EVENT_OPTIONS_V1.WPD_EVENT_OPTION_IS_BROADCAST_EVENT"
            | 3u -> "[ VT_BOOL ] WPD_EVENT_OPTIONS_V1.WPD_EVENT_OPTION_IS_AUTOPLAY_EVENT"
            | _ -> sprintf "Variant type %u not found" tag.pid
        | "5d9da160-74ae-43cc-85a9-fe555a80798e" -> 
            match (tag.pid) with 
            | 2u -> "[ VT_LPWSTR ] WPD_PROPERTY_ATTRIBUTES_V2.WPD_PROPERTY_ATTRIBUTE_NAME"
            | 3u -> "[ VT_UI4 ] WPD_PROPERTY_ATTRIBUTES_V2.WPD_PROPERTY_ATTRIBUTE_VARTYPE"
            | _ -> sprintf "Variant type %u not found" tag.pid
        | "24457e74-2e9f-44f9-8c57-1d1bcb170b89" -> 
            match (tag.pid) with 
            | 2u -> "[ Required ] WPD_CATEGORY_SERVICE_CAPABILITIES.WPD_COMMAND_SERVICE_CAPABILITIES_GET_SUPPORTED_METHODS"
            | 3u -> "[ Required ] WPD_CATEGORY_SERVICE_CAPABILITIES.WPD_COMMAND_SERVICE_CAPABILITIES_GET_SUPPORTED_METHODS_BY_FORMAT"
            | 4u -> "[ Required ] WPD_CATEGORY_SERVICE_CAPABILITIES.WPD_COMMAND_SERVICE_CAPABILITIES_GET_METHOD_ATTRIBUTES"
            | 5u -> "[ Required ] WPD_CATEGORY_SERVICE_CAPABILITIES.WPD_COMMAND_SERVICE_CAPABILITIES_GET_METHOD_PARAMETER_ATTRIBUTES"
            | 6u -> "[ Required ] WPD_CATEGORY_SERVICE_CAPABILITIES.WPD_COMMAND_SERVICE_CAPABILITIES_GET_SUPPORTED_FORMATS"
            | 7u -> "[ Required ] WPD_CATEGORY_SERVICE_CAPABILITIES.WPD_COMMAND_SERVICE_CAPABILITIES_GET_FORMAT_ATTRIBUTES"
            | 8u -> "[ Required ] WPD_CATEGORY_SERVICE_CAPABILITIES.WPD_COMMAND_SERVICE_CAPABILITIES_GET_SUPPORTED_FORMAT_PROPERTIES"
            | 9u -> "[ Required ] WPD_CATEGORY_SERVICE_CAPABILITIES.WPD_COMMAND_SERVICE_CAPABILITIES_GET_FORMAT_PROPERTY_ATTRIBUTES"
            | 10u -> "[ Required ] WPD_CATEGORY_SERVICE_CAPABILITIES.WPD_COMMAND_SERVICE_CAPABILITIES_GET_SUPPORTED_EVENTS"
            | 11u -> "[ Required ] WPD_CATEGORY_SERVICE_CAPABILITIES.WPD_COMMAND_SERVICE_CAPABILITIES_GET_EVENT_ATTRIBUTES"
            | 12u -> "[ Required ] WPD_CATEGORY_SERVICE_CAPABILITIES.WPD_COMMAND_SERVICE_CAPABILITIES_GET_EVENT_PARAMETER_ATTRIBUTES"
            | 13u -> "[ Required ] WPD_CATEGORY_SERVICE_CAPABILITIES.WPD_COMMAND_SERVICE_CAPABILITIES_GET_INHERITED_SERVICES"
            | 14u -> "[ Required ] WPD_CATEGORY_SERVICE_CAPABILITIES.WPD_COMMAND_SERVICE_CAPABILITIES_GET_FORMAT_RENDERING_PROFILES"
            | 15u -> "[ Required ] WPD_CATEGORY_SERVICE_CAPABILITIES.WPD_COMMAND_SERVICE_CAPABILITIES_GET_SUPPORTED_COMMANDS"
            | 16u -> "[ Required ] WPD_CATEGORY_SERVICE_CAPABILITIES.WPD_COMMAND_SERVICE_CAPABILITIES_GET_COMMAND_OPTIONS"
            | 1001u -> "[ VT_UNKNOWN ] WPD_CATEGORY_SERVICE_CAPABILITIES.WPD_PROPERTY_SERVICE_CAPABILITIES_SUPPORTED_METHODS"
            | 1002u -> "[ VT_CLSID ] WPD_CATEGORY_SERVICE_CAPABILITIES.WPD_PROPERTY_SERVICE_CAPABILITIES_FORMAT"
            | 1003u -> "[ VT_CLSID ] WPD_CATEGORY_SERVICE_CAPABILITIES.WPD_PROPERTY_SERVICE_CAPABILITIES_METHOD"
            | 1004u -> "[ VT_UNKNOWN ] WPD_CATEGORY_SERVICE_CAPABILITIES.WPD_PROPERTY_SERVICE_CAPABILITIES_METHOD_ATTRIBUTES"
            | 1005u -> "[ VT_UNKNOWN ] WPD_CATEGORY_SERVICE_CAPABILITIES.WPD_PROPERTY_SERVICE_CAPABILITIES_PARAMETER"
            | 1006u -> "[ VT_UNKNOWN ] WPD_CATEGORY_SERVICE_CAPABILITIES.WPD_PROPERTY_SERVICE_CAPABILITIES_PARAMETER_ATTRIBUTES"
            | 1007u -> "[ VT_UNKNOWN ] WPD_CATEGORY_SERVICE_CAPABILITIES.WPD_PROPERTY_SERVICE_CAPABILITIES_FORMATS"
            | 1008u -> "[ VT_UNKNOWN ] WPD_CATEGORY_SERVICE_CAPABILITIES.WPD_PROPERTY_SERVICE_CAPABILITIES_FORMAT_ATTRIBUTES"
            | 1009u -> "[ VT_UNKNOWN ] WPD_CATEGORY_SERVICE_CAPABILITIES.WPD_PROPERTY_SERVICE_CAPABILITIES_PROPERTY_KEYS"
            | 1010u -> "[ VT_UNKNOWN ] WPD_CATEGORY_SERVICE_CAPABILITIES.WPD_PROPERTY_SERVICE_CAPABILITIES_PROPERTY_ATTRIBUTES"
            | 1011u -> "[ VT_UNKNOWN ] WPD_CATEGORY_SERVICE_CAPABILITIES.WPD_PROPERTY_SERVICE_CAPABILITIES_SUPPORTED_EVENTS"
            | 1012u -> "[ VT_CLSID ] WPD_CATEGORY_SERVICE_CAPABILITIES.WPD_PROPERTY_SERVICE_CAPABILITIES_EVENT"
            | 1013u -> "[ VT_UNKNOWN ] WPD_CATEGORY_SERVICE_CAPABILITIES.WPD_PROPERTY_SERVICE_CAPABILITIES_EVENT_ATTRIBUTES"
            | 1014u -> "[ VT_UI4 ] WPD_CATEGORY_SERVICE_CAPABILITIES.WPD_PROPERTY_SERVICE_CAPABILITIES_INHERITANCE_TYPE"
            | 1015u -> "[ VT_UNKNOWN ] WPD_CATEGORY_SERVICE_CAPABILITIES.WPD_PROPERTY_SERVICE_CAPABILITIES_INHERITED_SERVICES"
            | 1016u -> "[ VT_UNKNOWN ] WPD_CATEGORY_SERVICE_CAPABILITIES.WPD_PROPERTY_SERVICE_CAPABILITIES_RENDERING_PROFILES"
            | 1017u -> "[ VT_UNKNOWN ] WPD_CATEGORY_SERVICE_CAPABILITIES.WPD_PROPERTY_SERVICE_CAPABILITIES_SUPPORTED_COMMANDS"
            | 1018u -> "[ VT_UNKNOWN ] WPD_CATEGORY_SERVICE_CAPABILITIES.WPD_PROPERTY_SERVICE_CAPABILITIES_COMMAND"
            | 1019u -> "[ VT_UNKNOWN ] WPD_CATEGORY_SERVICE_CAPABILITIES.WPD_PROPERTY_SERVICE_CAPABILITIES_COMMAND_OPTIONS"
            | _ -> sprintf "Variant type %u not found" tag.pid
        | "2ed8ba05-0ad3-42dc-b0d0-bc95ac396ac8" -> 
            match (tag.pid) with 
            | 2u -> "[ VT_UI4 ] WPD_MEDIA_PROPERTIES_V1.WPD_MEDIA_TOTAL_BITRATE"
            | 3u -> "[ VT_UI4 ] WPD_MEDIA_PROPERTIES_V1.WPD_MEDIA_BITRATE_TYPE"
            | 4u -> "[ VT_LPWSTR ] WPD_MEDIA_PROPERTIES_V1.WPD_MEDIA_COPYRIGHT"
            | 5u -> "[ VT_LPWSTR ] WPD_MEDIA_PROPERTIES_V1.WPD_MEDIA_SUBSCRIPTION_CONTENT_ID"
            | 6u -> "[ VT_UI4 ] WPD_MEDIA_PROPERTIES_V1.WPD_MEDIA_USE_COUNT"
            | 7u -> "[ VT_UI4 ] WPD_MEDIA_PROPERTIES_V1.WPD_MEDIA_SKIP_COUNT"
            | 8u -> "[ VT_DATE ] WPD_MEDIA_PROPERTIES_V1.WPD_MEDIA_LAST_ACCESSED_TIME"
            | 9u -> "[ VT_LPWSTR ] WPD_MEDIA_PROPERTIES_V1.WPD_MEDIA_PARENTAL_RATING"
            | 10u -> "[ VT_UI4 ] WPD_MEDIA_PROPERTIES_V1.WPD_MEDIA_META_GENRE"
            | 11u -> "[ VT_LPWSTR ] WPD_MEDIA_PROPERTIES_V1.WPD_MEDIA_COMPOSER"
            | 12u -> "[ VT_UI4 ] WPD_MEDIA_PROPERTIES_V1.WPD_MEDIA_EFFECTIVE_RATING"
            | 13u -> "[ VT_LPWSTR ] WPD_MEDIA_PROPERTIES_V1.WPD_MEDIA_SUB_TITLE"
            | 14u -> "[ VT_DATE ] WPD_MEDIA_PROPERTIES_V1.WPD_MEDIA_RELEASE_DATE"
            | 15u -> "[ VT_UI4 ] WPD_MEDIA_PROPERTIES_V1.WPD_MEDIA_SAMPLE_RATE"
            | 16u -> "[ VT_UI4 ] WPD_MEDIA_PROPERTIES_V1.WPD_MEDIA_STAR_RATING"
            | 17u -> "[ VT_UI4 ] WPD_MEDIA_PROPERTIES_V1.WPD_MEDIA_USER_EFFECTIVE_RATING"
            | 18u -> "[ VT_LPWSTR ] WPD_MEDIA_PROPERTIES_V1.WPD_MEDIA_TITLE"
            | 19u -> "[ VT_UI8 ] WPD_MEDIA_PROPERTIES_V1.WPD_MEDIA_DURATION"
            | 20u -> "[ VT_BOOL ] WPD_MEDIA_PROPERTIES_V1.WPD_MEDIA_BUY_NOW"
            | 21u -> "[ VT_LPWSTR ] WPD_MEDIA_PROPERTIES_V1.WPD_MEDIA_ENCODING_PROFILE"
            | 22u -> "[ VT_UI4 ] WPD_MEDIA_PROPERTIES_V1.WPD_MEDIA_WIDTH"
            | 23u -> "[ VT_UI4 ] WPD_MEDIA_PROPERTIES_V1.WPD_MEDIA_HEIGHT"
            | 24u -> "[ VT_LPWSTR ] WPD_MEDIA_PROPERTIES_V1.WPD_MEDIA_ARTIST"
            | 25u -> "[ VT_LPWSTR ] WPD_MEDIA_PROPERTIES_V1.WPD_MEDIA_ALBUM_ARTIST"
            | 26u -> "[ VT_LPWSTR ] WPD_MEDIA_PROPERTIES_V1.WPD_MEDIA_OWNER"
            | 27u -> "[ VT_LPWSTR ] WPD_MEDIA_PROPERTIES_V1.WPD_MEDIA_MANAGING_EDITOR"
            | 28u -> "[ VT_LPWSTR ] WPD_MEDIA_PROPERTIES_V1.WPD_MEDIA_WEBMASTER"
            | 29u -> "[ VT_LPWSTR ] WPD_MEDIA_PROPERTIES_V1.WPD_MEDIA_SOURCE_URL"
            | 30u -> "[ VT_LPWSTR ] WPD_MEDIA_PROPERTIES_V1.WPD_MEDIA_DESTINATION_URL"
            | 31u -> "[ VT_LPWSTR ] WPD_MEDIA_PROPERTIES_V1.WPD_MEDIA_DESCRIPTION"
            | 32u -> "[ VT_LPWSTR ] WPD_MEDIA_PROPERTIES_V1.WPD_MEDIA_GENRE"
            | 33u -> "[ VT_UI8 ] WPD_MEDIA_PROPERTIES_V1.WPD_MEDIA_TIME_BOOKMARK"
            | 34u -> "[ VT_LPWSTR ] WPD_MEDIA_PROPERTIES_V1.WPD_MEDIA_OBJECT_BOOKMARK"
            | 35u -> "[ VT_DATE ] WPD_MEDIA_PROPERTIES_V1.WPD_MEDIA_LAST_BUILD_DATE"
            | 36u -> "[ VT_UI8 ] WPD_MEDIA_PROPERTIES_V1.WPD_MEDIA_BYTE_BOOKMARK"
            | 37u -> "[ VT_UI8 ] WPD_MEDIA_PROPERTIES_V1.WPD_MEDIA_TIME_TO_LIVE"
            | 38u -> "[ VT_LPWSTR ] WPD_MEDIA_PROPERTIES_V1.WPD_MEDIA_GUID"
            | 39u -> "[ VT_LPWSTR ] WPD_MEDIA_PROPERTIES_V1.WPD_MEDIA_SUB_DESCRIPTION"
            | 49u -> "[ VT_LPWSTR ] WPD_MEDIA_PROPERTIES_V1.WPD_MEDIA_AUDIO_ENCODING_PROFILE"
            | _ -> sprintf "Variant type %u not found" tag.pid
        | "f99efd03-431d-40d8-a1c9-4e220d9c88d3" -> 
            match (tag.pid) with 
            | 3u -> "[ VT_LPWSTR ] WPD_APPOINTMENT_OBJECT_PROPERTIES_V1.WPD_APPOINTMENT_LOCATION"
            | 7u -> "[ VT_LPWSTR ] WPD_APPOINTMENT_OBJECT_PROPERTIES_V1.WPD_APPOINTMENT_TYPE"
            | 8u -> "[ VT_LPWSTR ] WPD_APPOINTMENT_OBJECT_PROPERTIES_V1.WPD_APPOINTMENT_REQUIRED_ATTENDEES"
            | 9u -> "[ VT_LPWSTR ] WPD_APPOINTMENT_OBJECT_PROPERTIES_V1.WPD_APPOINTMENT_OPTIONAL_ATTENDEES"
            | 10u -> "[ VT_LPWSTR ] WPD_APPOINTMENT_OBJECT_PROPERTIES_V1.WPD_APPOINTMENT_ACCEPTED_ATTENDEES"
            | 11u -> "[ VT_LPWSTR ] WPD_APPOINTMENT_OBJECT_PROPERTIES_V1.WPD_APPOINTMENT_RESOURCES"
            | 12u -> "[ VT_LPWSTR ] WPD_APPOINTMENT_OBJECT_PROPERTIES_V1.WPD_APPOINTMENT_TENTATIVE_ATTENDEES"
            | 13u -> "[ VT_LPWSTR ] WPD_APPOINTMENT_OBJECT_PROPERTIES_V1.WPD_APPOINTMENT_DECLINED_ATTENDEES"
            | _ -> sprintf "Variant type %u not found" tag.pid
        | "b324f56a-dc5d-46e5-b6df-d2ea414888c6" -> 
            match (tag.pid) with 
            | 3u -> "[ VT_LPWSTR ] WPD_MUSIC_OBJECT_PROPERTIES_V1.WPD_MUSIC_ALBUM"
            | 4u -> "[ VT_UI4 ] WPD_MUSIC_OBJECT_PROPERTIES_V1.WPD_MUSIC_TRACK"
            | 6u -> "[ VT_LPWSTR ] WPD_MUSIC_OBJECT_PROPERTIES_V1.WPD_MUSIC_LYRICS"
            | 8u -> "[ VT_LPWSTR ] WPD_MUSIC_OBJECT_PROPERTIES_V1.WPD_MUSIC_MOOD"
            | 9u -> "[ VT_UI4 ] WPD_MUSIC_OBJECT_PROPERTIES_V1.WPD_AUDIO_BITRATE"
            | 10u -> "[ VT_R4 ] WPD_MUSIC_OBJECT_PROPERTIES_V1.WPD_AUDIO_CHANNEL_COUNT"
            | 11u -> "[ VT_UI4 ] WPD_MUSIC_OBJECT_PROPERTIES_V1.WPD_AUDIO_FORMAT_CODE"
            | 12u -> "[ VT_UI4 ] WPD_MUSIC_OBJECT_PROPERTIES_V1.WPD_AUDIO_BIT_DEPTH"
            | 13u -> "[ VT_UI4 ] WPD_MUSIC_OBJECT_PROPERTIES_V1.WPD_AUDIO_BLOCK_ALIGNMENT"
            | _ -> sprintf "Variant type %u not found" tag.pid
        | "e354e95e-d8a0-4637-a03a-0cb26838dbc7" -> 
            match (tag.pid) with 
            | 6u -> "[ VT_LPWSTR ] WPD_TASK_OBJECT_PROPERTIES_V1.WPD_TASK_STATUS"
            | 8u -> "[ VT_UI4 ] WPD_TASK_OBJECT_PROPERTIES_V1.WPD_TASK_PERCENT_COMPLETE"
            | 10u -> "[ VT_DATE ] WPD_TASK_OBJECT_PROPERTIES_V1.WPD_TASK_REMINDER_DATE"
            | 11u -> "[ VT_LPWSTR ] WPD_TASK_OBJECT_PROPERTIES_V1.WPD_TASK_OWNER"
            | _ -> sprintf "Variant type %u not found" tag.pid
        | "00000000-0000-0000-0000-000000000000" -> 
            match (tag.pid) with 
            | 0u -> "[ VT_EMPTY ] WPD_CATEGORY_NULL.WPD_PROPERTY_NULL"
            | _ -> sprintf "Variant type %u not found" tag.pid
        | "33fb0d11-64a3-4fac-b4c7-3dfeaa99b051" -> 
            match (tag.pid) with 
            | 2u -> "[ Required ] WPD_CLASS_EXTENSION_V1.WPD_COMMAND_CLASS_EXTENSION_WRITE_DEVICE_INFORMATION"
            | 1001u -> "[ VT_UNKNOWN ] WPD_CLASS_EXTENSION_V1.WPD_PROPERTY_CLASS_EXTENSION_DEVICE_INFORMATION_VALUES"
            | 1002u -> "[ VT_UNKNOWN ] WPD_CLASS_EXTENSION_V1.WPD_PROPERTY_CLASS_EXTENSION_DEVICE_INFORMATION_WRITE_RESULTS"
            | _ -> sprintf "Variant type %u not found" tag.pid
        | "7e9a7abf-e568-4b34-aa2f-13bb12ab177d" -> 
            match (tag.pid) with 
            | 2u -> "[ VT_UNKNOWN ] WPD_FOLDER_OBJECT_PROPERTIES_V1.WPD_FOLDER_CONTENT_TYPES_ALLOWED"
            | _ -> sprintf "Variant type %u not found" tag.pid
        | "b7474e91-e7f8-4ad9-b400-ad1a4b58eeec" -> 
            match (tag.pid) with 
            | 2u -> "[ Required ] WPD_CATEGORY_OBJECT_ENUMERATION.WPD_COMMAND_OBJECT_ENUMERATION_START_FIND"
            | 3u -> "[ Required ] WPD_CATEGORY_OBJECT_ENUMERATION.WPD_COMMAND_OBJECT_ENUMERATION_FIND_NEXT"
            | 4u -> "[ Required ] WPD_CATEGORY_OBJECT_ENUMERATION.WPD_COMMAND_OBJECT_ENUMERATION_END_FIND"
            | 1001u -> "[ VT_LPWSTR ] WPD_CATEGORY_OBJECT_ENUMERATION.WPD_PROPERTY_OBJECT_ENUMERATION_PARENT_ID"
            | 1002u -> "[ VT_UNKNOWN ] WPD_CATEGORY_OBJECT_ENUMERATION.WPD_PROPERTY_OBJECT_ENUMERATION_FILTER"
            | 1003u -> "[ VT_UNKNOWN ] WPD_CATEGORY_OBJECT_ENUMERATION.WPD_PROPERTY_OBJECT_ENUMERATION_OBJECT_IDS"
            | 1004u -> "[ VT_LPWSTR ] WPD_CATEGORY_OBJECT_ENUMERATION.WPD_PROPERTY_OBJECT_ENUMERATION_CONTEXT"
            | 1005u -> "[ VT_UI4 ] WPD_CATEGORY_OBJECT_ENUMERATION.WPD_PROPERTY_OBJECT_ENUMERATION_NUM_OBJECTS_REQUESTED"
            | _ -> sprintf "Variant type %u not found" tag.pid
        | "0cabec78-6b74-41c6-9216-2639d1fce356" -> 
            match (tag.pid) with 
            | 2u -> "[ Required ] WPD_CATEGORY_CAPABILITIES.WPD_COMMAND_CAPABILITIES_GET_SUPPORTED_COMMANDS"
            | 3u -> "[ Required ] WPD_CATEGORY_CAPABILITIES.WPD_COMMAND_CAPABILITIES_GET_COMMAND_OPTIONS"
            | 4u -> "[ Required ] WPD_CATEGORY_CAPABILITIES.WPD_COMMAND_CAPABILITIES_GET_SUPPORTED_FUNCTIONAL_CATEGORIES"
            | 5u -> "[ Required ] WPD_CATEGORY_CAPABILITIES.WPD_COMMAND_CAPABILITIES_GET_FUNCTIONAL_OBJECTS"
            | 6u -> "[ Required ] WPD_CATEGORY_CAPABILITIES.WPD_COMMAND_CAPABILITIES_GET_SUPPORTED_CONTENT_TYPES"
            | 7u -> "[ Required ] WPD_CATEGORY_CAPABILITIES.WPD_COMMAND_CAPABILITIES_GET_SUPPORTED_FORMATS"
            | 8u -> "[ Required ] WPD_CATEGORY_CAPABILITIES.WPD_COMMAND_CAPABILITIES_GET_SUPPORTED_FORMAT_PROPERTIES"
            | 9u -> "[ Required ] WPD_CATEGORY_CAPABILITIES.WPD_COMMAND_CAPABILITIES_GET_FIXED_PROPERTY_ATTRIBUTES"
            | 10u -> "[ Required ] WPD_CATEGORY_CAPABILITIES.WPD_COMMAND_CAPABILITIES_GET_SUPPORTED_EVENTS"
            | 11u -> "[ Required ] WPD_CATEGORY_CAPABILITIES.WPD_COMMAND_CAPABILITIES_GET_EVENT_OPTIONS"
            | 1001u -> "[ VT_UNKNOWN ] WPD_CATEGORY_CAPABILITIES.WPD_PROPERTY_CAPABILITIES_SUPPORTED_COMMANDS"
            | 1002u -> "[ VT_UNKNOWN ] WPD_CATEGORY_CAPABILITIES.WPD_PROPERTY_CAPABILITIES_COMMAND"
            | 1003u -> "[ VT_UNKNOWN ] WPD_CATEGORY_CAPABILITIES.WPD_PROPERTY_CAPABILITIES_COMMAND_OPTIONS"
            | 1004u -> "[ VT_UNKNOWN ] WPD_CATEGORY_CAPABILITIES.WPD_PROPERTY_CAPABILITIES_FUNCTIONAL_CATEGORIES"
            | 1005u -> "[ VT_CLSID ] WPD_CATEGORY_CAPABILITIES.WPD_PROPERTY_CAPABILITIES_FUNCTIONAL_CATEGORY"
            | 1006u -> "[ VT_UNKNOWN ] WPD_CATEGORY_CAPABILITIES.WPD_PROPERTY_CAPABILITIES_FUNCTIONAL_OBJECTS"
            | 1007u -> "[ VT_UNKNOWN ] WPD_CATEGORY_CAPABILITIES.WPD_PROPERTY_CAPABILITIES_CONTENT_TYPES"
            | 1008u -> "[ VT_CLSID ] WPD_CATEGORY_CAPABILITIES.WPD_PROPERTY_CAPABILITIES_CONTENT_TYPE"
            | 1009u -> "[ VT_UNKNOWN ] WPD_CATEGORY_CAPABILITIES.WPD_PROPERTY_CAPABILITIES_FORMATS"
            | 1010u -> "[ VT_CLSID ] WPD_CATEGORY_CAPABILITIES.WPD_PROPERTY_CAPABILITIES_FORMAT"
            | 1011u -> "[ VT_UNKNOWN ] WPD_CATEGORY_CAPABILITIES.WPD_PROPERTY_CAPABILITIES_PROPERTY_KEYS"
            | 1012u -> "[ VT_UNKNOWN ] WPD_CATEGORY_CAPABILITIES.WPD_PROPERTY_CAPABILITIES_PROPERTY_ATTRIBUTES"
            | 1013u -> "[ VT_UNKNOWN ] WPD_CATEGORY_CAPABILITIES.WPD_PROPERTY_CAPABILITIES_SUPPORTED_EVENTS"
            | 1014u -> "[ VT_CLSID ] WPD_CATEGORY_CAPABILITIES.WPD_PROPERTY_CAPABILITIES_EVENT"
            | 1015u -> "[ VT_UNKNOWN ] WPD_CATEGORY_CAPABILITIES.WPD_PROPERTY_CAPABILITIES_EVENT_OPTIONS"
            | _ -> sprintf "Variant type %u not found" tag.pid
        | "d8f907a6-34cc-45fa-97fb-d007fa47ec94" -> 
            match (tag.pid) with 
            | 2u -> "[ Required ] WPD_CATEGORY_STORAGE.WPD_COMMAND_STORAGE_FORMAT"
            | 4u -> "[ Required ] WPD_CATEGORY_STORAGE.WPD_COMMAND_STORAGE_EJECT"
            | 1001u -> "[ VT_LPWSTR ] WPD_CATEGORY_STORAGE.WPD_PROPERTY_STORAGE_OBJECT_ID"
            | 1002u -> "[ VT_LPWSTR ] WPD_CATEGORY_STORAGE.WPD_PROPERTY_STORAGE_DESTINATION_OBJECT_ID"
            | _ -> sprintf "Variant type %u not found" tag.pid
        | "516afd2b-c64e-44f0-98dc-bee1c88f7d66" -> 
            match (tag.pid) with 
            | 2u -> "[ VT_UI8 ] WPD_SECTION_OBJECT_PROPERTIES_V1.WPD_SECTION_DATA_OFFSET"
            | 3u -> "[ VT_UI8 ] WPD_SECTION_OBJECT_PROPERTIES_V1.WPD_SECTION_DATA_LENGTH"
            | 4u -> "[ VT_UI4 ] WPD_SECTION_OBJECT_PROPERTIES_V1.WPD_SECTION_DATA_UNITS"
            | 5u -> "[ VT_UNKNOWN ] WPD_SECTION_OBJECT_PROPERTIES_V1.WPD_SECTION_DATA_REFERENCED_OBJECT_RESOURCE"
            | _ -> sprintf "Variant type %u not found" tag.pid
        | "ef1e43dd-a9ed-4341-8bcc-186192aea089" -> 
            match (tag.pid) with 
            | 2u -> "[ Required ] WPD_CATEGORY_OBJECT_MANAGEMENT.WPD_COMMAND_OBJECT_MANAGEMENT_CREATE_OBJECT_WITH_PROPERTIES_ONLY"
            | 3u -> "[ Required ] WPD_CATEGORY_OBJECT_MANAGEMENT.WPD_COMMAND_OBJECT_MANAGEMENT_CREATE_OBJECT_WITH_PROPERTIES_AND_DATA"
            | 4u -> "[ Required ] WPD_CATEGORY_OBJECT_MANAGEMENT.WPD_COMMAND_OBJECT_MANAGEMENT_WRITE_OBJECT_DATA"
            | 5u -> "[ Required ] WPD_CATEGORY_OBJECT_MANAGEMENT.WPD_COMMAND_OBJECT_MANAGEMENT_COMMIT_OBJECT"
            | 6u -> "[ Required ] WPD_CATEGORY_OBJECT_MANAGEMENT.WPD_COMMAND_OBJECT_MANAGEMENT_REVERT_OBJECT"
            | 7u -> "[ Required ] WPD_CATEGORY_OBJECT_MANAGEMENT.WPD_COMMAND_OBJECT_MANAGEMENT_DELETE_OBJECTS"
            | 8u -> "[ Required ] WPD_CATEGORY_OBJECT_MANAGEMENT.WPD_COMMAND_OBJECT_MANAGEMENT_MOVE_OBJECTS"
            | 9u -> "[ Required ] WPD_CATEGORY_OBJECT_MANAGEMENT.WPD_COMMAND_OBJECT_MANAGEMENT_COPY_OBJECTS"
            | 10u -> "[ Required ] WPD_CATEGORY_OBJECT_MANAGEMENT.WPD_COMMAND_OBJECT_MANAGEMENT_UPDATE_OBJECT_WITH_PROPERTIES_AND_DATA"
            | 1001u -> "[ VT_UNKNOWN ] WPD_CATEGORY_OBJECT_MANAGEMENT.WPD_PROPERTY_OBJECT_MANAGEMENT_CREATION_PROPERTIES"
            | 1002u -> "[ VT_LPWSTR ] WPD_CATEGORY_OBJECT_MANAGEMENT.WPD_PROPERTY_OBJECT_MANAGEMENT_CONTEXT"
            | 1003u -> "[ VT_UI4 ] WPD_CATEGORY_OBJECT_MANAGEMENT.WPD_PROPERTY_OBJECT_MANAGEMENT_NUM_BYTES_TO_WRITE"
            | 1004u -> "[ VT_UI4 ] WPD_CATEGORY_OBJECT_MANAGEMENT.WPD_PROPERTY_OBJECT_MANAGEMENT_NUM_BYTES_WRITTEN"
            | 1005u -> " WPD_CATEGORY_OBJECT_MANAGEMENT.WPD_PROPERTY_OBJECT_MANAGEMENT_DATA"
            | 1006u -> "[ VT_LPWSTR ] WPD_CATEGORY_OBJECT_MANAGEMENT.WPD_PROPERTY_OBJECT_MANAGEMENT_OBJECT_ID"
            | 1007u -> "[ VT_UI4 ] WPD_CATEGORY_OBJECT_MANAGEMENT.WPD_PROPERTY_OBJECT_MANAGEMENT_DELETE_OPTIONS"
            | 1008u -> "[ VT_UI4 ] WPD_CATEGORY_OBJECT_MANAGEMENT.WPD_PROPERTY_OBJECT_MANAGEMENT_OPTIMAL_TRANSFER_BUFFER_SIZE"
            | 1009u -> "[ VT_UNKNOWN ] WPD_CATEGORY_OBJECT_MANAGEMENT.WPD_PROPERTY_OBJECT_MANAGEMENT_OBJECT_IDS"
            | 1010u -> "[ VT_UNKNOWN ] WPD_CATEGORY_OBJECT_MANAGEMENT.WPD_PROPERTY_OBJECT_MANAGEMENT_DELETE_RESULTS"
            | 1011u -> "[ VT_LPWSTR ] WPD_CATEGORY_OBJECT_MANAGEMENT.WPD_PROPERTY_OBJECT_MANAGEMENT_DESTINATION_FOLDER_OBJECT_ID"
            | 1012u -> "[ VT_UNKNOWN ] WPD_CATEGORY_OBJECT_MANAGEMENT.WPD_PROPERTY_OBJECT_MANAGEMENT_MOVE_RESULTS"
            | 1013u -> "[ VT_UNKNOWN ] WPD_CATEGORY_OBJECT_MANAGEMENT.WPD_PROPERTY_OBJECT_MANAGEMENT_COPY_RESULTS"
            | 1014u -> "[ VT_UNKNOWN ] WPD_CATEGORY_OBJECT_MANAGEMENT.WPD_PROPERTY_OBJECT_MANAGEMENT_UPDATE_PROPERTIES"
            | 1015u -> "[ VT_UNKNOWN ] WPD_CATEGORY_OBJECT_MANAGEMENT.WPD_PROPERTY_OBJECT_MANAGEMENT_PROPERTY_KEYS"
            | 1016u -> "[ VT_CLSID ] WPD_CATEGORY_OBJECT_MANAGEMENT.WPD_PROPERTY_OBJECT_MANAGEMENT_OBJECT_FORMAT"
            | 5001u -> "[ VT_BOOL ] WPD_CATEGORY_OBJECT_MANAGEMENT.WPD_OPTION_OBJECT_MANAGEMENT_RECURSIVE_DELETE_SUPPORTED"
            | _ -> sprintf "Variant type %u not found" tag.pid
        | "c53d039f-ee23-4a31-8590-7639879870b4" -> 
            match (tag.pid) with 
            | 2u -> "[ VT_UNKNOWN ] WPD_RENDERING_INFORMATION_OBJECT_PROPERTIES_V1.WPD_RENDERING_INFORMATION_PROFILES"
            | 3u -> "[ VT_UI4 ] WPD_RENDERING_INFORMATION_OBJECT_PROPERTIES_V1.WPD_RENDERING_INFORMATION_PROFILE_ENTRY_TYPE"
            | 4u -> "[ VT_UNKNOWN ] WPD_RENDERING_INFORMATION_OBJECT_PROPERTIES_V1.WPD_RENDERING_INFORMATION_PROFILE_ENTRY_CREATABLE_RESOURCES"
            | _ -> sprintf "Variant type %u not found" tag.pid
        | "7e1074cc-50ff-4dd1-a742-53be6f093a0d" -> 
            match (tag.pid) with 
            | 2u -> "[ VT_LPWSTR ] WPD_SMS_OBJECT_PROPERTIES_V1.WPD_SMS_PROVIDER"
            | 3u -> "[ VT_UI4 ] WPD_SMS_OBJECT_PROPERTIES_V1.WPD_SMS_TIMEOUT"
            | 4u -> "[ VT_UI4 ] WPD_SMS_OBJECT_PROPERTIES_V1.WPD_SMS_MAX_PAYLOAD"
            | 5u -> "[ VT_UI4 ] WPD_SMS_OBJECT_PROPERTIES_V1.WPD_SMS_ENCODING"
            | _ -> sprintf "Variant type %u not found" tag.pid
        | "8f052d93-abca-4fc5-a5ac-b01df4dbe598" -> 
            match (tag.pid) with 
            | 2u -> "[ VT_CLSID ] WPD_FUNCTIONAL_OBJECT_PROPERTIES_V1.WPD_FUNCTIONAL_OBJECT_CATEGORY"
            | _ -> sprintf "Variant type %u not found" tag.pid
        | "0d5fb92b-cb46-4c4f-8343-0bc3d3f17c84" -> 
            match (tag.pid) with 
            | 2u -> "[ Required ] WPD_CATEGORY_DEVICE_HINTS.WPD_COMMAND_DEVICE_HINTS_GET_CONTENT_LOCATION"
            | 1001u -> "[ VT_CLSID ] WPD_CATEGORY_DEVICE_HINTS.WPD_PROPERTY_DEVICE_HINTS_CONTENT_TYPE"
            | 1002u -> "[ VT_UNKNOWN ] WPD_CATEGORY_DEVICE_HINTS.WPD_PROPERTY_DEVICE_HINTS_CONTENT_LOCATIONS"
            | _ -> sprintf "Variant type %u not found" tag.pid
        | "01a3057a-74d6-4e80-bea7-dc4c212ce50a" -> 
            match (tag.pid) with 
            | 2u -> "[ VT_UI4 ] WPD_STORAGE_OBJECT_PROPERTIES_V1.WPD_STORAGE_TYPE"
            | 3u -> "[ VT_LPWSTR ] WPD_STORAGE_OBJECT_PROPERTIES_V1.WPD_STORAGE_FILE_SYSTEM_TYPE"
            | 4u -> "[ VT_UI8 ] WPD_STORAGE_OBJECT_PROPERTIES_V1.WPD_STORAGE_CAPACITY"
            | 5u -> "[ VT_UI8 ] WPD_STORAGE_OBJECT_PROPERTIES_V1.WPD_STORAGE_FREE_SPACE_IN_BYTES"
            | 6u -> "[ VT_UI8 ] WPD_STORAGE_OBJECT_PROPERTIES_V1.WPD_STORAGE_FREE_SPACE_IN_OBJECTS"
            | 7u -> "[ VT_LPWSTR ] WPD_STORAGE_OBJECT_PROPERTIES_V1.WPD_STORAGE_DESCRIPTION"
            | 8u -> "[ VT_LPWSTR ] WPD_STORAGE_OBJECT_PROPERTIES_V1.WPD_STORAGE_SERIAL_NUMBER"
            | 9u -> "[ VT_UI8 ] WPD_STORAGE_OBJECT_PROPERTIES_V1.WPD_STORAGE_MAX_OBJECT_SIZE"
            | 10u -> "[ VT_UI8 ] WPD_STORAGE_OBJECT_PROPERTIES_V1.WPD_STORAGE_CAPACITY_IN_OBJECTS"
            | 11u -> "[ VT_UI4 ] WPD_STORAGE_OBJECT_PROPERTIES_V1.WPD_STORAGE_ACCESS_CAPABILITY"
            | _ -> sprintf "Variant type %u not found" tag.pid
        | _ -> sprintf "Section %A not found" tag.fmtid
